OpenDreamProject/OpenDream

OpenDreamShared/Compiler/DM/DMParser.cs
Fixes #9 
AFAIK the BYOND compiler just ignores this.
=> Adds support for "as" usage in var declarations

OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
**Disclaimer: I am not 100% sure this works as intended**
String parsing is still a bit above my paygrade, but I _think_ this fixes #10 
The main thing I'm iffy on is whether or not `textBuilder.Append('\t');` is needed.
=> Fixes lexing multiline strings that contain whitespace

OpenDreamShared/Compiler/DM/DMParser.cs, OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
Currently, if you have a comment after a proc statement it will throw.
Ex: 
```
for(var/A in thing)
if(A + 2 > 5)
continue //Here is a comment. This would cause an exception.
return thing[A]
```
Also fixes #30
=> Fixes proc statements followed by comments & indented multiline comments

OpenDreamShared/Compiler/DM/DMParser.cs
Doing 
```
for(var/item/thing/T as() in some_list)
``` 
is the same as 
```
for(var/item/thing/T as anything in some_list)
```
Both define a loop without internal typechecking.
=> Adds support for as()

OpenDreamShared/Compiler/DM/DMParser.cs
Should partially fix #36 
According to the docs, if Type is not specified then `input()` treats it as an implicit `text` type. So `AsTypes()` can now return a default type if there is no `as` token.
=> Adds support for implicit as types

OpenDreamShared/Compiler/Lexer.cs
title
it fails in the `interfaceResource.ReadAsString()` and passes the null down the chain:
https://github.com/ZeWaka/OpenDream/blob/c86ab7441ac03349b6e5194180651d5675a93974/OpenDreamServer/Program.cs#L152
=> Throws exception when lexer can't find a source file

OpenDreamClient/Interface/DreamInterface.cs, OpenDreamClient/Interface/Prompts/MessagePrompt.cs, OpenDreamClient/Interface/Prompts/NumberPrompt.cs, OpenDreamClient/Interface/Prompts/PromptWindow.cs, OpenDreamClient/Interface/Prompts/TextPrompt.cs, OpenDreamServer/Dream/Procs/DreamProcInterpreterOpcodes.cs, OpenDreamServer/Net/DreamConnection.cs, OpenDreamShared/Net/Packets/PacketPrompt.cs, TestGame/code.dm
Title, adds in support for default input() values.
Throw a client console error if it tries to convert something that's not a number to a number. Previously, it just crashed (lol).
Converted a few of the variable settings to use object initializers.
Also threw in a suppression for #53
=> default value argument backend support for input()

OpenDreamServer/Dream/Objects/MetaObjects/DreamMetaObjectClient.cs, OpenDreamServer/Net/DreamConnection.cs
title
Returns localhost (`IPAddress.Any`) if there's no `RemoteEndPoint` (shouldn't happen unless connection failed/socket disposed)
=> Implements client.address

DMCompiler/DMStandard/_Standard.dm
The list quickly stops being alphabetical once you reach the procs implemented in DM, but let me know if you want to move it anyways.
=> Implement placeholder hearers()

DMCompiler/copy_standard.bat
Oops, I didn't test the nested directories. It'll also copy empty dirs now too just to be on the safe side.
=> Makes copy_standard.bat recursive

DMCompiler/DMStandard/Defines.dm, DMCompiler/DMStandard/Types/World.dm, OpenDreamServer/Dream/Objects/MetaObjects/DreamMetaObjectWorld.cs
http://www.byond.com/docs/ref/#/world/var/system_type
It checks for unix/macos rather than windows because the enum contains like 4 different entries for windows.
=> Implement world.system_type

OpenDreamClient/Interface/Elements/ElementBrowser.cs, OpenDreamClient/OpenDreamClient.csproj
title
https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes#10721-prerelease changed `CoreWebView2Ready` to `CoreWebView2InitializationCompleted`.
=> Upgrade dependencies

OpenDreamServer/Dream/Procs/Native/DreamProcNativeList.cs
Fixes the implementation to use the indices
Worked for:
=> Remove Ranged List NotImplementedException

OpenDreamServer/Dream/Procs/Native/DreamProcNativeRoot.cs
Properly handles json encoding of lists that don't have an associated value with values.
Fixes #90
=> Properly encodes assoc. lists with both associated and non-associated values

OpenDreamServer/Dream/DreamValue.cs
Implements a `DreamValue`-specific equality instead of just using the `object` version
profiling results:
```
byond: 11 dseconds
C#: 107 dseconds for both (profiler on)
C#: 91 dseconds for new (profiler off)
Boxing: 0.08% - 236ms/367ms DreamValue.Equals(Object)
Non-Boxing: 0.03% 92ms / 139ms DreamValue.Equals(DremaValue)
```
<details><summary><b>DA CODE</b></summary>
<p>
```cs
var/list/L = list()
var/testy = 50
for (var/i = 1, i <= 4000000, i++)
L += rand(1, 100)
var/start = world.timeofday
for (var/i = 1, i <= 4000000, i++)
if (testy == L[i])
testy = i
var/elapsed = world.timeofday - start
world << "[elapsed] dseconds"
```
</p>
</details>
Methodology from https://theburningmonk.com/2015/07/beware-of-implicit-boxing-of-value-types/
We might also want to look at: …
=> Eliminates boxing on equality for DreamValue

OpenDreamServer/Dream/DreamValue.cs
see title, fixes #95 / #97 
https://web.archive.org/web/20100317143155/http://msdn.microsoft.com/en-us/library/ms173147(VS.80).aspx / https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type
> By default, the operator `==` tests for reference equality by determining if two references indicate the same object...
> The `==` and `!=` operators can be used with classes even if the class does not overload them. However, the default behavior is to perform a reference equality check.
now is also faster: 80ds
=> fixes stupid reference equality in #95

OpenDreamShared/Dream/DreamPath.cs
title
See #95 for reasoning
relevant: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type
=> Removes boxing for DreamPath equality

OpenDreamRuntime.Tests/DMProject/code.dm, OpenDreamRuntime.Tests/UnitTest1.cs, OpenDreamRuntime/DreamRuntime.cs, OpenDreamRuntime/Procs/AsyncNativeProc.cs
The problem I noticed was that if a proc completes synchronously, we'd return `ProcStatus.Returned` on the first call to InternalResume but the task's continuation would still be scheduled (and would later call Thread.Resume again.)
Seeing as we've already got the result, we don't need to schedule the task at all and can just discard it.
=> add test for async proc call & fix for potential resumptions of stale proc states

OpenDreamRuntime.Tests/DMProject/code.dm, OpenDreamRuntime.Tests/UnitTest1.cs, OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
I made this work by having the CRASH proc return a special kind of exception. I also swapped around the args to Assert.AreEqual in my tests because I didn't realise it mattered before.
=> CRASH proc ceases execution of caller

DMCompiler/DMStandard/Types/Client.dm, OpenDreamClient/OpenDream.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectClient.cs, OpenDreamServer/Server.cs, OpenDreamShared/Net/ClientData.cs, OpenDreamShared/Net/Packets/IPacket.cs, OpenDreamShared/Net/Packets/PacketRequestConnect.cs, TestGame/code.dm
Implements `client.timezone`.
I made a new shared class to keep track of this, and info like it.
Me receiving my UTC offset:
=> Implementation of `client.timezone` and corresponding `ClientData`

OpenDreamRuntime/DreamMap.cs, OpenDreamRuntime/DreamRuntime.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectWorld.cs
Unsure on exact GC behavior regarding the deletion of the levels, please advise.
The actual z-removal works though. You're no longer able to traverse to the level in the test project.
If you are on a Z-level when it gets removed, your client just stays stuck and can't move. This is similar to BYOND's behavior, where it just crashes your client.
=> Implementation of z-level removal (`world.maxz--`)

OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Objects/DreamList.cs
Implements IEquatable<DreamValue> for DreamValue
Converts DreamList to use .Contains for ContainsValue
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=net-5.0#remarks
> Methods such as Contains, IndexOf, LastIndexOf, and Remove use an equality comparer for the list elements. The default equality comparer for type T is determined as follows. If type T implements the IEquatable<T> generic interface, then the equality comparer is the Equals(T) method of that interface; otherwise, the default equality comparer is Object.Equals(Object).
> Make certain the value type used for type T implements the IEquatable<T> generic interface. If not, methods such as Contains must call the Object.Equals(Object) method, which boxes the affected list element.
=> DreamList.ContainsValue speedup

OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectList.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectRoot.cs, OpenDreamRuntime/Objects/MetaObjects/IDreamMetaObject.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, TestGame/code.dm
title
partially solves #120 - won't be doing the icon bit now
```cs
var/list/L = list(1,2,3)
var/list/G = list(3,4,5)
var/x = 7
var/y = 8
world.log << json_encode(L | G)
world.log << json_encode(G | L)
world.log << json_encode(L | x)
world.log << json_encode(x | y)
world.log << json_encode(L | null)
world.log << json_encode(null | L)
```
to
```
[1,2,3,4,5]
[3,4,5,1,2]
[1,2,3,7]
15
[1,2,3,null]
null
```
=> Implements DreamList unions (aka `L1 | L2`)

OpenDreamShared/Compiler/DM/DMParser.cs
Test code:
```
verb/stupid_list()
var/thing[5]
usr << thing.len
```
Fixes #49
=> Implements var/thing[len] list syntax

OpenDreamRuntime/Objects/DreamObject.cs
Includes the typepath: 
`Unhandled exception. System.InvalidOperationException: DreamObject.InitSpawn (/obj/structure/closet/secure_closet/injection) called a yielding proc!`
=> Adds more info to yielding New() exceptions

OpenDreamClient/OpenDream.cs
Throwing unhandled exceptions for things that should just be errors is not kosher.
=> Don't crash the client if they input a verb arg

OpenDreamRuntime/Objects/DreamObjectDefinition.cs
Removes a bunch of allocations by pre-allocating the dictionary sizes for Variables and GlobalVariables. This works off of the assumption that these dictionaries are empty until `CopyVariablesFrom()` is called, and that this method is only called once. If this isn't the case then I can probably tweak it for less impressive improvements.
Basic Rider profiling (not the most accurate, mind you) shows this method going from ~3,000ms to ~1,000ms.
=> Shaves 2,000 ms off of maploading

OpenDreamShared/Dream/DreamPath.cs
Memory allocations go brrrrrrr.
I didn't bother profiling it but it's so bad even my IDE pointed it out.
=> Pre-allocate the stack in Normalize()

nuget.config
RemoteExecutor is a dependency of the engine tests which allows us to test NumericsHelpers and all its different code paths.
Hopefully in the future, we can replace this dependency with something else so we can remove this extra nuget repo. Until then, having it doesn't really affect anything.
=> Add dotnet-eng nuget repo. Fixes engine tests.

Content.Shared/ContentNetIDs.cs, Content.Shared/SharedDMISpriteComponent.cs
The most notable change is the removal of component NetIDs in favor of the `NetworkedComponent` attribute, which takes care of everything automatically when you put it in the shared component class.
=> Update RobustToolbox submodule to the latest version.

Content.Client/EntryPoint.cs, Content.IntegrationTests/Content.IntegrationTests.csproj, Content.IntegrationTests/ContentIntegrationTest.cs, Content.IntegrationTests/DMProject/code.dm, Content.IntegrationTests/DMProject/environment.dme, Content.IntegrationTests/DMProject/interface.dmf, Content.IntegrationTests/DMProject/map.dmm, Content.IntegrationTests/GameStartsTest.cs, Content.IntegrationTests/SetupCompileDM.cs, DMCompiler/Program.cs
The DMProject will be compiled once before any tests are ran, and used by default in all tests. When all tests have been run, the compiled file is deleted as part of cleanup. Specific tests can override the CVar to point to a different json file, but they will probably need to compile it themselves. Also, this PR doesn't include a workflow to run tests in CI yet.
As a side effect, clients don't connect to a server on EntryPoint by default anymore, just so integration tests using clients can work. However, you can pass `--connect --connect-address 127.0.0.1:25566` (replace address if needed) as program arguments to the client to auto-connect to the server. Your IDE has an option for this, 100 %.
This adds a simple example test where a server and client pair are started and connected to …
=> Integration tests now compile and use DMProject.

DMCompiler/Program.cs
And generally makes the compiler more arg-friendly.
Just toss in `--dump-preprocessor` and it Just Works:tm:
=> Adds a program arg to dump the preprocessor

DMCompiler/DMStandard/Defines.dm, DMCompiler/DMStandard/Types/Client.dm, DMCompiler/DMStandard/Types/World.dm
These should be deprecated once there's codebases actually targeting OpenDream, but until then this is needed for any modern SS13 code.
=> Adds DM_VERSION and DM_BUILD

Content.Client/EntryPoint.cs, Content.Client/Interface/DreamInterfaceManager.cs, Content.Client/Interface/DreamStylesheet.cs, OpenDream.sln.DotSettings
Adds a simple ~~awful-looking~~ stylesheet.
Despite it not looking great, it at least allows you to use most of Robust ViewVariables' functionality, which is perfect for debugging and the like. And hey, at least the stylesheet is now there and people can start messing with the current values, or add new styles.
=> [Robust] Add very simple stylesheet.

Content.Server/DMISpriteComponent.cs, Content.Server/LocalHostConGroup.cs, Content.Server/ServerContentIoC.cs
This allows clients connected through localhost to have all admin permissions when the server is compiled in DEBUG, therefore allowing you to access server-side ViewVariables and SCSI (once #321 is merged) when testing the server & client locally.
Ideally, in the future a more advanced system can be implemented that allows hosts to give some accounts certain permissions.
Also adds VV attributes to a few DMISpriteComponent properties.
=> [Robust] Add localhost congroup controller

OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Fixes a part of https://github.com/wixoaGit/OpenDream/issues/342
I didn't profile the memory usage but it is presumably better. Also might have gone overboard with the null checking but w/e.
=> Associative lists will no longer be allocated for non-associative lists

DMCompiler/DMStandard/Defines.dm, DMCompiler/DMStandard/Types/Atoms/_Atom.dm
The proc is already flagged as `opendream_unimplemented` so I don't feel bad adding placeholder values.
=> Adds blend_mode defines

DMCompiler/DMStandard/Defines.dm, DMCompiler/DMStandard/Types/Atoms/_Atom.dm, DMCompiler/DMStandard/Types/Client.dm, DMCompiler/DMStandard/Types/Image.dm, DMCompiler/DMStandard/Types/Sound.dm, DMCompiler/DMStandard/Types/World.dm, DMCompiler/DMStandard/_Standard.dm
Should be a sufficiently valid placeholder for everything except `locs`.
Not closing any issues because they still need, y'know, actual implementations at some point.
=> Adds placeholders for almost everything NTstation needs

OpenDreamShared/Compiler/DM/DMParser.cs
I'm not sure if it's just that easy, but if it _is_ then this'll knock another ~30 errors off of TG.
=> Adds support for braced switches

OpenDreamShared/Compiler/DM/DMLexer.cs
Move NTstation from 220 to 186 errors with one easy trick.
=> Adds italic, b, and bold as valid escape sequences

OpenDreamClient/Interface/DreamInterface.cs, OpenDreamShared/Compiler/DM/DMParser.cs, OpenDreamShared/Compiler/DMF/DMFParser.cs, OpenDreamShared/Compiler/Parser.cs, OpenDreamShared/Compiler/Token.cs
This pattern (`ReadOnlySpan<T> x = new T[] { ... }`) is optimized by Roslyn to create a Span from assembly image memory instead of allocating, if T : byte. I tested and it works for enums too.
This saves ~700 MB of allocations parsing /vg/.
=> Remove Check() parser array allocations.

.editorconfig, .gitattributes
This removes the .editorconfig LF forcing, and properly configures git to do CRLF conversion always.
This fixes all the crap of opening a file causing it to be edited despite only EOLs changing.
=> Fix newlines in project

DMCompiler/DM/DMExpression.cs, DMCompiler/DM/DMObject.cs, DMCompiler/DM/Visitors/DMObjectBuilder.cs, DMCompiler/DMStandard/Types/World.dm, OpenDreamShared/Compiler/DM/DMAST.cs, OpenDreamShared/Compiler/DM/DMParser.cs, OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
Closes #368 
Trying to access or override a var flagged as unimplemented will throw a compiler warning.
Ex: `var/test as opendream_unimplemented`
=> Implements unimplemented warnings for vars

OpenDreamShared/Compiler/DM/DMParser.cs
Eats modified types and throws an unimplemented warning.
Closes #34 and I'll make a new issue for implementing actual functionality when this is merged.
=> Implements modified types as an unimplemented warning

OpenDreamShared/Compiler/DM/DMParser.cs
This is valid DM: `for(A, A && !ismob(A), A=A.loc);`
The semicolon seems to have no effect.
=> Eat trailing semicolons after for() and while()

OpenDreamShared/Dream/ScreenLocation.cs, OpenDreamShared/Resources/DMIParser.cs
float.Parse uses default OS locale to parse float if it doesn't specify. In the Russian version of Windows, it expects the float separator to be "," instead of ".", which breaks the parsing of .dmi.
So I specified default culture for all float.Parse.
=> fix(client): specify default culture for float.Parse

OpenDreamClient/Interface/Controls/ControlBrowser.cs
Fix weird behavior when the WebView2 Runtime is missing by adding some error processing.
=> fix(webview2): process webview2 runtime missing error

DMCompiler/DM/DMProc.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, OpenDreamShared/Compiler/DM/DMAST.cs, OpenDreamShared/Compiler/DM/DMParser.cs
Fixes #408 
Adds support for label blocks and using continue/break in them.
This survived extremely basic testing but could probably use more rigorous BYOND parity testing.
=> Adds support for label blocks

OpenDreamShared/Compiler/DM/DMParser.cs
Paradise has a few places where they do something like `INVOKE_ASYNC(GLOBAL_PROC, /.proc/flick_overlay, I, speech_bubble_hearers, 30)` and that preceding `/` in `/.proc` causes problems.
~~I don't _think_ there's an open issue for this.~~ Fixes #392
=> Fixes preceding an upward search with a slash

DMCompiler/DM/Expressions/Dereference.cs
test case:
```
#include "map.dmm"
#include "interface.dmf"
/obj
inner
var/ele2 = 4
var/ele = 2
var/innerobj
var/obj/inner/innerobj_ty
proc/inner_proc()
return new /obj
proc/elefn()
return 3
/proc/new_obj()
return new /obj
/world/New()
ASSERT(new_obj().ele == 2)
ASSERT(new_obj()?.ele == 2)
ASSERT(new_obj().inner_proc().ele == 2)
ASSERT(new_obj()?.inner_proc()?.ele == 2)
var/obj/o2 = new /obj
ASSERT(o2.inner_proc().elefn() == 3)
ASSERT(o2?.inner_proc()?.elefn() == 3)
o2.innerobj_ty = new /obj/inner
ASSERT(o2:innerobj_ty.ele2 == 4)
var/list/l = newlist(/obj)
ASSERT(l[1].ele == 2)
ASSERT(l[1].elefn() == 3)
l[1].innerobj = new /obj/inner
ASSERT(l[1].innerobj.ele2 == 4)
var/o
// This is still not allowed
//world.log << "[o.ele]"
//world.log << "[o.elefn()]"
shutdown()
```
=> change direct to lax deref for certain expressions

README.md
I added https://github.com/wixoaGit/OpenDream/wiki/Compiler-Options to list the compiler options, and this PR links it in the readme.
The reason I'm using a wiki page is so we don't have to edit the readme every time we add a compiler arg.
=> Adds a link to the Compiler Options wiki page

OpenDreamClient/Audio/DreamSoundEngine.cs
OpenAL volume is in decibels, BYOND's volume goes from 0 to 100.
I fixed this issue by doing a funny logarithm volume scale.
In C#, `MathF.Log10(0)` is negative infinity, therefore resulting in completely muted audio.
DM Snippet for easy testing (works in testgame!)
```DM
verb/input_num()
var/v = input("A") as num
usr << sound("test.ogg", volume=v)
usr << "you entered [v]"
```
=> Fix sound volume.

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Fix text2num to make it works with Russian Windows's locale.
OpenDream doesn't work with Russian Window's locale because of broken text2num (right now it uses system locale to parse floats and expects "," separator instead of "."). To fix it InvariantCulture should be specified when float is parsed.
=> [RT] fix(text2num): specify default culture for Convert.ToSingle

DMCompiler/Compiler/DM/DMParser.cs
The closing `}` wasn't getting consumed in a fairly specific case.
Relevant DM:
```
proc/AStar(start,end,adjacent,dist,maxnodes,maxnodedepth = 30,mintargetdist,minnodedist,id=null, var/turf/exclude=null)
var/PriorityQueue/open = new /PriorityQueue(/proc/PathWeightCompare) //the open list, ordered using the PathWeightCompare proc, from lower f to higher
var/list/closed = new() //the closed list
var/list/path = null //the returned path, if any
var/PathNode/cur //current processed turf
//sanitation
start = get_turf(start)
if(!start)
return 0
//initialization
open.Enqueue(new /PathNode(start,null,0,call(start,dist)(end),0))
//then run the main loop
while(!open.IsEmpty() && !path)
{
//get the lower f node on the open list
cur = open.Dequeue() //get the lower f turf in the open list …
```
=> Fixes braced indented inner proc blocks

DMCompiler/DM/DMObject.cs, DMCompiler/DM/Expressions/Builtins.cs, DMCompiler/DM/Expressions/Dereference.cs, DMCompiler/DM/Expressions/Procs.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, DMCompiler/DMCompiler.cs, OpenDreamShared/Compiler/CompilerError.cs
Not quite as useful until we have location information stored in expressions, but it does point out unsupported `in world` loops.
=> Adds location support to CompilerWarnings

DMCompiler/Compiler/DM/DMParser.cs
1. `Expected dedent` in the switch() parsing has been reworded to match BYOND's error
2. Using `else if()` as a switch case throws that error too since it produces unexpected behavior in both BYOND and OD
=> Tweaks switch() errors

DMCompiler/DM/DMObjectTree.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamShared/Dream/DreamPath.cs
While compiling NTstation a path string of `"/"` is causing an exception because Elements is 0.
Not sure if this is the proper fix but it does stop the exception.
=> Fixes LastElement throwing an exception

DMCompiler/DM/Visitors/DMVisitorExpression.cs
Problematic code: 
`dat+="<B><A href='?src=\ref[src];show_channel=\ref[CHANNEL]'>[CHANNEL.channel_name]</A> [(CHANNEL.censored) ? ("<FONT COLOR='red'>***</FONT>") : ()]<BR></B>"`
It's the `()` for `ternary.C`
=> Fixes an exception in ternary null handling

DMCompiler/Compiler/DM/DMParser.cs
Makes this: `var/{flatX1=1;flatX2=flat.Width();flatY1=1;flatY2=flat.Height()}` compile.
Seems to work for this exact example, but I'm not sure if I have the right combo of `Whitespace()` and `Newline()` shenanigans for other potential cases.
Fixes #320
=> Parse some funky bracketed var decl syntax

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Code used to test:
```dm
/world/New()
..()
world.log << "Running"
sleep(-1)
world.log << "No exception"
```
Fixes #489. Does not reproduce byond behavior exactly, just stops the exception
=> Fix exception with negative sleeps

DMCompiler/Compiler/DM/DMAST.cs, DMCompiler/Compiler/DM/DMPath.cs, DMCompiler/DM/DMExpression.cs, DMCompiler/DM/DMProc.cs, DMCompiler/DM/Visitors/DMObjectBuilder.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, DMCompiler/DM/Visitors/DMVisitorExpression.cs
test case:
```
#include "map.dmm"
#include "interface.dmf"
var/c = 999
/proc/init_static()
return dynamic_value()
/proc/dynamic_value()
static_proc()
return --c
/proc/static_proc_shadowed()
var/static/inner_c = 700
return inner_c
/proc/static_proc()
// Inner static definitions must be recursively located
while (1)
var/static/inner_c = init_static()
inner_c++
return inner_c
/obj
var/const/c = 5
subobj1
var/static/s = dynamic_value()
var/global/g = dynamic_value()
subobj2
var/static/s = dynamic_value()
var/global/g = dynamic_value()
/world/New()
var/obj/subobj1/o1 = new
var/obj/subobj1/o2 = new
var/obj/subobj2/o3 = new
//world.log << "[static_proc()]"
//world.log << "[static_proc_shadowed()]"
//world.log << "[o1.s] [o1.g] [o1.c]"
//o1.s -= 90
//world.log << "[o2.s] [o2.g]"
//world.log << …
```
=> parse variable declaration modifiers + add static vars

DMCompiler/Compiler/DM/DMParser.cs, OpenDreamShared/Dream/DreamPath.cs
1. PathString's getter was relatively quite expensive. StringBuilder is actually a worse option when you're only concatenating a few strings. Replaced it with a regular `string.Join()` and shaved off a small amount of both time and memory usage.
2. Reorganized the dozen or so procStatement method calls to be primarily sorted by frequency, then moved `If()` last because although it's by far the most common it's also by far the most expensive of them.
Altogether this shaves about 5 seconds off my compile time, making us officially 4x faster at compiling than byond.
=> Two compiler optimizations

DMCompiler/DMCompiler.cs, OpenDreamRuntime/DreamManager.cs, OpenDreamShared/Json/DreamCompiledJson.cs, OpenDreamShared/Json/DreamObjectJson.cs
Fixes issue #536
Example from tgstation:
=> Don't save nulls to global list in the compiler

OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/DreamMapManager.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/DreamProcIdentifier.cs
Does a few things:
1. Makes sure a turf's loc is set before init to fix issues in New()
2. Adds the ability to modify an actual variable value. Fixes (partially) #556
3. Made Atom's OnVariableSet() a switch
4. `src` can be set to a DreamObject. Fixes #557
=> Fixes a few exceptions

OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamServer/server_config.toml
This partially addresses https://github.com/wixoaGit/OpenDream/issues/447 but not to the point where I'd call it fixed.
It also fixes #560 
At the moment you need to either get lucky with your connect attempt lining up with sufficient yielding, or pass the *client* each of the cvars in `server_config.toml` like you pass the json to the server. I'm going to ask around in SS14 Discord about the possibility of adding a `client_config.toml` for use when not using the launcher.
=> Makes `spawn()` and `sleep()` actually yield

OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs
Makes the stack slightly less boxed:tm: , i still have to like, actually unbox IDreamProcIdentifier and DreamProcArguments ( latter is much easier), for now i just added a new DreamValueType, that stores them directly. once i figure out what to do, im gonna fix it. Either way the game should be slightly faster.
haven't tested on SS13, test game seems to run fine, i didnt notice any runtime errors from the small amount of testing i did.
=> Turns object _stack[] into DreamValue _stack[]

OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectList.cs
The default behavior is to set it to 0 if it's not a number.
=> Fixes setting list.len to non-numbers

OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectClient.cs
1. Fixes setting `client.images` to a non-list. It'll probably need to be tweaked when the var is actually implemented.
2. Made `CreateOverlayAppearance()` better at coping with unexpected value types.
=> Fix some issues with appearances and client images

OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Not all of them, just most of them.
Values are derived from BYOND's handling of `null` being passed except where otherwise noted.
=> Vibe checks a ton of `GetValueAsString()` uses

DMCompiler/DMStandard/_Standard.dm
For some crazy reason the args are unordered, as stated in the docs.
I also think I improved the handling for bad args to more closely replicate BYOND.
Fixes #547
=> Makes `range()` and `orange()` unordered

DMCompiler/Compiler/DM/DMLexer.cs, DMCompiler/Compiler/DM/DMParser.cs
for long escapes read the entire word before making a choice
allows \himself \herself to take priority over \him and \her
=> escape sequence priority change

DMCompiler/DM/Expressions/Procs.cs
Bad DM code has too much of this. If we ever make a clone of C# pragmas we could consider having it default as an error.
=> Make bad ..() calls a warning instead of an error

DMCompiler/DM/Expressions/LValue.cs
Code:
```
/proc/wumbo(c = "c")
var/b = 2
world.log << initial(b)
b = 3
world.log << initial(b)
world.log << initial(c)
c = 5
world.log << initial(c)
```
Compiler:
```
Compiling environment.dme
Warning at code.dm:10:25: calling initial() on a local variable returns the current value
Warning at code.dm:12:25: calling initial() on a local variable returns the current value
Warning at code.dm:13:25: calling initial() on a local variable returns the current value
Warning at code.dm:15:25: calling initial() on a local variable returns the current value
Compilation succeeded with 4 warnings
Saved to C:/Users/main/Documents/GitHub/OpenDream/OpenDream/TestGame/environment.json
Total time: 00:00
```
BYOND output:
OD output:
```
[INFO] world.log: 2
[INFO] world.log: 3
[INFO] world.log: c
[INFO] …
```
=> Adds support for calling initial() on a local var

OpenDreamClient/Audio/DreamSoundChannel.cs, OpenDreamClient/Audio/DreamSoundEngine.cs, OpenDreamClient/Interface/BrowsePopup.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/DreamStylesheet.cs, OpenDreamClient/Interface/DummyDreamInterfaceManager.cs, OpenDreamClient/Interface/InterfaceElement.cs, OpenDreamClient/Interface/Prompts/AlertWindow.cs, OpenDreamClient/Interface/Prompts/InputWindow.cs, OpenDreamClient/Interface/Prompts/MessagePrompt.cs, OpenDreamClient/Interface/Prompts/NumberPrompt.cs, OpenDreamClient/Interface/Prompts/PromptWindow.cs, OpenDreamClient/Interface/Prompts/TextPrompt.cs, OpenDreamClient/Resources/DreamResourceManager.cs, OpenDreamClient/Resources/ResourceTypes/DMIResource.cs, OpenDreamClient/Resources/ResourceTypes/ResourceSound.cs
title
Reasons for not sealing:
NumberPrompt: people might want to make a binary-only or some other weird prompt??
TextPrompt: Could keep this single line, and extend another one to be multiline? unsure what TextPrompt and what MessagePrompt should cover
InputWindow: This can be instantiated, so it's not abstract.
=> Seals some classes and cleans up some unused imports

OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamRuntime/Rendering/ServerAppearanceSystem.cs
Includes a fix necessary for OD to work with the SS14 watchdog.
Combined with https://github.com/wixoaGit/OpenDream/pull/585 it is now possible to host a server that the SS14 launcher can connect to.
=> Bumps RT version

DMCompiler/DM/DMProc.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, OpenDreamShared/Compiler/CompilerError.cs
Ideally nothing should ever outright kill compilation (except maybe a cap on error count like byond's) so I did this.
Also removes an unused constructor for CompileErrorException.
Not sure what other existing places should be changed to use this exception & handle it.
=> Adds a new exception type

DMCompiler/DM/DMProc.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/Objects/DreamObjectDefinition.cs, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Procs/AsyncNativeProc.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/NativeProc.cs, OpenDreamShared/Dream/Procs/ProcAttributes.cs, OpenDreamShared/Json/DreamProcJson.cs
They're not used by the runtime but all of them (minus src) do get set in the runtime on the DMProc.
=> Adds the remaining verb settings

OpenDreamRuntime/DreamMapManager.cs, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamShared/Dream/DreamPath.cs
I can't really tell if the methods should be kept for switch cases that check the type. Seems like it'd just tempt people to use it elsewhere IMO.
Anyways in _most_ cases the Try version should be used and changing the code will better replicate BYOND handling of bad values.
=> Marks `GetValueAs[Type]()` obsolete, removes some usages

DMCompiler/DM/Expressions/Dereference.cs
For some reason I was convinced that calling `initial()` on a list index actually worked somehow, but it's just another case of https://github.com/wixoaGit/OpenDream/pull/581 where it just returns the current value.
Added a warning like we did for that case too.
Closes #522
=> Implements `initial(list[idx])`

DMCompiler/DM/Visitors/DMObjectBuilder.cs
This outputs 5 in BYOND and now OD:
```
var/global/G1 = 5
var/global/G2 = G1
/proc/main()
world.log << G2
```
=> Fixes setting a global to a global

DMCompiler/DM/Expressions/Builtins.cs
You get the idea. Same as the `initial()` PRs.
=> Implements `issaved()` for a list index

DMCompiler/DM/Visitors/DMVisitorExpression.cs, OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Procs/DMProc.cs
`EnumeratorStack` now only allocs when it's needed (we should copy maxstack logic for these at some point).
Every `DreamList` no longer tries to resolve `IDreamManager` in its constructor, instead the first one does and caches the list definition in a static var. Resolves are relatively expensive.
The two arraypool returns are now in a method and it's been added to `HandleException()`
Misc additions of `sealed`, etc.
=> Reduce `DreamList` allocs + misc cleanup

DMCompiler/DMStandard/Defines.dm
I tried every flavor of the `SEE_` macros without underscores and these are all of the valid ones we were missing.
=> Adds `SEEMOBS` and `SEETURFS`

DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Visitors/DMVisitorExpression.cs
I'm not entirely sure this is the most correct way to do this, but it fixes #611 
Also changed a random bit of code to a switch and fixed a typo.
=> Fixes `||=` not including path info

OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs
- Lists can now allocate the correct size initially
- `EnumerateListing()` now returns a string array and as a bonus I made it append `/` to dirs like the ref says `flist()` does.
- `public static DreamList Create(IEnumerable<object> collection)` is now `public static DreamList Create(string[] collection)` since they're all string arrays anyways
- `del()` no longer throws an exception. `OnObjectDeleted()` tries to access the `loc` variable, so it needs to not be `Deleted` yet.
=> Nuke `list()` allocs and fix `del()`

DMCompiler/DM/Expressions/LValue.cs
You know the drill.
I'm mildly surprised this is the BYOND behavior.
=> Implements `initial()` on global fields

DMCompiler/DM/DMProc.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
The list, dict, and array are allocated as-needed and as their necessary size. The number of named vars is passed to accommodate this.
=> Reduces `PushArguments` allocs

Tools/package_client_build.py, Tools/package_server_build.py
Copies the scripts over from https://github.com/space-wizards/space-station-14/tree/master/Tools which are needed to package game builds. Mainly so players connecting through the launcher actually have a client to download.
I made minimal changes to the scripts to accommodate our renaming. I'm not 100% sure everything is functional until I've finished sorting out the test server, hence this being a draft.
=> Adds the packaging scripts from SS14

DMCompiler/Compiler/DMM/DMMParser.cs, DMCompiler/DM/Expressions/Builtins.cs, DMCompiler/DM/Expressions/Procs.cs, DMCompiler/DMCompiler.cs, OpenDreamRuntime/DreamMapManager.cs, OpenDreamShared/Json/DreamMapJson.cs
Things this does:
- DMMParser has been edited to use normal compiler errors/warnings in several places
- The maps are now parsed & serialized _before_ compilation is considered successful, since it can fail
- The JSON is no longer saved if map parsing fails
- DMMParser now passes type info to DMExpression.Create()
- DMMParser can now cope with duplicate var overrides in a modified type, and will create a warning about it. The last parsed value will be used as the true override, not sure if this matches BYOND behavior.
- TryAsJsonRepresentation() now throws an unimplemented warning when it's unimplemented
- TryAsJsonRepresentation() for ProcCall has been stubbed
- Fixed a null reference exception with printing unimplemented warnings for global procs
- Trying to load multiple maps is now a …
=> Error tolerance refactor for map parsing/saving

DMCompiler/DMStandard/Defines.dm
example usecase:
```
#idef OPENDREAM
var/rustg = "rustg_x64.dll"
#else
var/rustg = "rustg.dll"
#endif
```
=> Adds an OPENDREAM define

.github/workflows/conflict-labeler.yml
The problem with the old merge conflict action was that the lack of any notification for the PR author made it largely useless.
This action is directly copied from BeeStation here: https://github.com/BeeStation/BeeStation-Hornet/blob/master/.github/workflows/extra_pr_labels.yml 
The workflow notifies the PR author by leaving a comment like so: https://github.com/BeeStation/BeeStation-Hornet/pull/6125#issuecomment-1032996734
It also adds the Merge Conflict label. When the conflicts are fixed it'll remove the label.
=> Adds a merge conflict Github Action

OpenDreamRuntime/DreamConnection.cs
This came up during the whole trying to get Para's Declare Ready to work.
=> Make `HandleMsgTopic()` cope with non-ints

OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/IAtomManager.cs, OpenDreamRuntime/Objects/DreamObjectDefinition.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs
Per the ref you can do `overlays += /path/of/type`
http://www.byond.com/docs/ref/#/atom/var/overlays
According to Nadrew, this doesn't actually instantiate the type and is equivalent to `initial()`ing the relevant vars
=> Adds support for creating an overlay from a typepath

DMCompiler/Compiler/DM/DMLexer.cs, DMCompiler/Compiler/DM/DMParser.cs
1. Fixes whitespace between the first proccall param and first comma.
2. Adds the unicode escape chars.
=> Two small fixes

DMCompiler/Compiler/DM/DMAST.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/DMProc.cs, DMCompiler/DM/Expressions/Builtins.cs, DMCompiler/DM/Visitors/DMASTSimplifier.cs, DMCompiler/DM/Visitors/DMVisitorExpression.cs, DMCompiler/DMStandard/UnsortedAdditions.dm, DMCompiler/DMStandard/_Standard.dm, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamShared/Dream/Procs/DreamProcOpcode.cs, TestGame/code.dm
Hi!
I'm not really a C# programmer, more of a C++ person, but I thought of this project again and decided to try to help out.
This PR implements the (seldom used) ``/proc/addtext(...)`` proc. Beyond that though, I've added a new opcode for doing the mass concatenation of a set of ``DreamValues``. I have not tried to make Add() expressions optimize into that, but doing so might be a good idea; right now it may be that calling addtext() on many concatenations is faster. I have had pleasant experiences [implementing such things](https://github.com/Altoids1/Joao/pull/10) in my own programming language.
=> Implements the addtext() proc

DMCompiler/DM/Visitors/DMObjectBuilder.cs
I don't think there is an issue for this but it does fix a bug with paradise.
=> Fix proc definitions not passing current obj properly

DMCompiler/DM/Expressions/Binary.cs
Closes #524
DM code: `(T = get_turf(H)).z` where `T` is the local `var/turf/T`
=> Fixes dereferencing an assignment

DMCompiler/DMCompiler.cs, OpenDreamShared/Compiler/Location.cs
IMO it's a good idea to differentiate between explicit warnings/errors raised internally by OD and actual unknown loc warnings/errors. There's probably more places that should be changed but the unimplemented warning is the most apparent.
Ex:
```
Compiling paradise.dme
Warning at <internal>: Unimplemented proc & var warnings are currently suppressed
```
=> Adds `Location.Internal`

DMCompiler/DM/DMProc.cs
1. Loop stacks only allocate when needed, and set their capacity to 3 initially (start, continue, end)
2. Loop stacks will now throw a compiler error instead of an exception if you pop them while they're null. I'm not sure what in baycode is causing this but the compiler should *never* really throw exceptions.
=> Hardens the loop stack against exceptions, reduces allocs

DMCompiler/DMStandard/Types/Icon.dm, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectIcon.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectRegex.cs, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeIcon.cs, OpenDreamShared/Resources/DMIParser.cs
See #141 
~~This is some messy 3am coding, opening as a draft to make my life easier.~~
=> Implements DreamMetaObjectIcon, Width(), Height()

DMCompiler/Compiler/DM/DMParser.cs
SET_ADJ_IN_DIR() was being parsed incorrectly because it was getting to
```
var/turf/neighbor = get_step(source, direction); \
if(!neighbor) { \
if(source.smoothing_flags & SMOOTH_BORDER) { \
junction |= direction_flag; \
}; \
}; \
```
the ending bracket of if(!neighbor) {...}; then skipping the else statement because it only checked for a newline when the next token was a semicolon. now it checks for a newline and a semicolon.
=> fixes if statement bracket bodies ending in ;

DMCompiler/Compiler/DM/DMParser.cs
Paradise:
```
/proc/is_surgery_tool(obj/item/W as obj)
return (	\
istype(W, /obj/item/scalpel)			||	\
istype(W, /obj/item/hemostat)		||	\
istype(W, /obj/item/retractor)		||	\
istype(W, /obj/item/cautery)			||	\
istype(W, /obj/item/bonegel)			||	\
istype(W, /obj/item/bonesetter)
)
```
=> Cope with whitespace in ExpressionPrimary

DMCompiler/Compiler/DM/DMParser.cs
1. Adds `switch` and `spawn` to the list of tokens you can use in a typepath
2. Copes with NOP switch cases like
```
if("No")
; // do nothing
```
3. Fixes an issue with modified types
=> Fixes misc baystation issues

OpenDreamClient/EntryPoint.cs
This is a relatively new API addition. It means that you can still pass `--cvar net.predict=true` to force it on for testing, which is pretty nice.
=> Use OverrideDefault to disable net.predict.

DMCompiler/Compiler/DM/DMParser.cs
Make it more clear the compiler is raising an error for "else if" on a switch intentionally.
=> Change switch elseif error message

DMCompiler/DM/Visitors/DMProcBuilder.cs
Fixes this crash, not really sure if I need to do anything else.
```
/proc/main()
for(n=1,,n++)
world<<n
break
```
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at DMCompiler.DM.DMExpression.Create(DMObject dmObject, DMProc proc, DMASTExpression expression, Nullable`1 inferredPath) in C:\Users\Wrexbe2\RiderProjects\OpenDream\DMCompiler\DM\DMExpression.cs:line 37
at DMCompiler.DM.DMExpression.Emit(DMObject dmObject, DMProc proc, DMASTExpression expression, Nullable`1 inferredPath) in C:\Users\Wrexbe2\RiderProjects\OpenDream\DMCompiler\DM\DMExpression.cs:line 42
at DMCompiler.DM.Visitors.DMProcBuilder.ProcessStatementForStandard(DMASTProcStatementForStandard statementForStandard) in …
```
=> Fix for without condition

DMCompiler/Compiler/DM/DMParser.cs
Make these work
```
/proc/main()
var
A;B;C;
```
```
/proc/main()
var
A; B; C;
```
```
/proc/main()
var
A;/*this is A*/ B;C;
```
=> Fix semicolons between variable declarations

DMCompiler/Compiler/DM/DMAST.cs, DMCompiler/Compiler/DM/DMPath.cs, DMCompiler/DM/DMObject.cs, DMCompiler/DM/Visitors/DMObjectBuilder.cs, DMCompiler/DMStandard/Types/Atoms/_Atom.dm, DMCompiler/DMStandard/Types/Image.dm
Fixes #742 and fixes #770 by implementing some duplication detection in `DMObjectBuilder`. 
While investigating `global.vars`, I realized that DMObjectBuilder just doesn't do any dupe checking for ANY variable it makes, so I added that.
In addition, I noticed that the `IsGlobal` and `IsTopLevel` booleans for VarDeclInfo weren't really useful for anything, since both end up being grammatically synonymous with being a static.
Adding this new error detection actually *discovered* a couple duped definitions in the DMStandard, so I cleaned those up too.
- Fixed duplicated definitions of statics or properties not causing a compile error
- Fixed duplicated definition of `global.vars` not causing an error, despite its special implementation
- Removed duplicate definitions in the DMStandard files …
=> Fixes duplicate definitions of statics and object properties not causing a compile-time error

DMCompiler/Compiler/DM/DMLexer.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
I don't know what ancient TI-BASIC stans are still using this operator in Current Year, but, whatever, it's supported now.
It looks like it's completely equivalent to != so I just implemented it as being read the same way. An easy patch.
=> Implements the <> operator

DMCompiler/DMStandard/Types/Atoms/_Atom.dm, DMCompiler/DMStandard/Types/Client.dm, DMCompiler/DMStandard/Types/Particles.dm
It's pretty much all unimplemented but this was preventing Yogs from compiling so, here ya go
- All of the variables that exist for `/particles` now exist in DMStandard, albeit as `opendream_unimplemented` spam.
=> Fleshes out the DMStandard file for /particles (plus /client.script and /atom.infra_luminosity)

DMCompiler/DMStandard/Types/Client.dm, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectClient.cs
Fixes #181
Right now we're really just waiting for RobustToolbox to implement something rigorous.
For now, we're just MD5ing the ckey.
In the future, I'd like to implement some sort of suite of security warnings to caution against using `computer_id` and other security-insecure things like this. Probably after the warning rework, whenever that happens.
=> Adds primitive implementation for /cilent.computer_id

DMCompiler/DMStandard/UnsortedAdditions.dm
Adds unimplemented stubs for:
- `findlasttextEx_char`
- `findtextEx_char`
- `nonspantext_char`
- `splicetext_char`
- `splittext_char`
=> Stub remaining _char variants of string procs

DMCompiler/DM/Visitors/DMObjectBuilder.cs
Global initialisers effectively act like one-line procs with an implicit return; as such, basically anything you could put in a global proc works with them, except for circular reference loops. Currently, it's bizarrely restrictive compared to DM; this PR changes that.
Fixes #796.
=> Make global initialisers more permissive

Content.Tests/DMProject/Tests/Text/EmbeddedExpressionPassesErrors.dm, Content.Tests/DMProject/Tests/Text/EndOfEmbeddedExpression.dm, Content.Tests/DMProject/Tests/Text/ExpectedEmbeddedExpression.dm, Content.Tests/DMProject/Tests/Text/HoleEmbeddedExpression.dm, DMCompiler/Compiler/DM/DMParser.cs
- Errors inside embedded expressions are no longer printed twice.
- Putting multiple expressions inside interpolation brackets now emits an error. (e.g. `"["a""b"]"` emits `Expected end of embedded expression`)
- Adds unit tests for bad embedded expressions (expressionless but non-empty/multiple expressions)
=> Improve error catching for embedded expressions

Content.Tests/DMTests.cs, DMCompiler/Compiler/DM/DMAST.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/DMExpression.cs, DMCompiler/DM/DMObject.cs, DMCompiler/DM/DMObjectTree.cs, DMCompiler/DM/DMVariable.cs, DMCompiler/DM/Expressions/Dereference.cs, DMCompiler/DM/Visitors/DMObjectBuilder.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, DMCompiler/DM/Visitors/DMVisitorExpression.cs, DMCompiler/DMCompiler.cs, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/IDreamManager.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
Fixes #738, fixes #702, and fixes #535.
This bugfix stuff comes with a refactor of `DMObjectBuilder` into the `static class` it probably should be.
As a treat, this PR also has a commit that amends Content.Test so that it actually prints the message of any unexpected runtime into the log file, instead of just declaring that there was a runtime. Should be helpful :)
- `const` now works as an effective keyword, preventing writing of values, within both procs and object definitions.
- Assignments now consistently remember the type of what they're assigning to (for implicit `new` calls)
- Variable overrides in object definitions now work correctly, remembering their initial type and preferring overrides that occur later in the source code, as per DM parity.
- `opendream_compiletimereadonly` …
=> Fixes writing to constants, adds readonly opendream pseudo-type, and makes var overrides respect their var's type

DMCompiler/DM/Visitors/DMObjectBuilder.cs, DMCompiler/DMStandard/Types/Client.dm, DMCompiler/DMStandard/Types/World.dm, OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectClient.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectWorld.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Fixes #805.
At first I thought this would just be an easy thing where I can, like, slap some stuff in DMStandard and call it a bug fixed.
However, while testing that solution, I found some bugginess in how var/vars works for all types, including /datum and everything else.
The classes that inherit from `DreamList` were not overriding some methods that procs like `json_encode` were using to find the associative values of the list, so I also fixed that.
- `json_encode()` is now better at encoding `vars` and `global.vars`.
- Fixed `vars` accesses not including any variables which have not been locally overwritten for the DMObject that is accessed.
- `json_encode()` no longer causes stack overflows when encoding data with cyclical or deep references.
- `/client` and `/world` now have a `vars` …
=> Adds var/vars to /world and /client, fixes several bugs with all var/vars implementations

DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs
Example:
- tgstation.dme has `#include "_maps\basemap.dm"`
- basemap.dm has `#include "map_files\generic\CentCom.dmm"`
- so `currentLexer.SourceName` is `_maps\basemap.dm`
- but `Path.GetDirectoryName` does not treat `\` as a separator and just returns the empty string
- so it does not find `_maps/map_files/generic/CentCom.dmm`
Used the apparent pattern from elsewhere in the file.
=> Fix #include directory logic when compiling on Linux

Content.IntegrationTests/Content.IntegrationTests.csproj, Content.Tests/Content.Tests.csproj
Tested on Linux, don't know if other platforms were affected.
`dotnet build` then `dotnet test --no-build Content.Tests` would work, but `dotnet test Content.Tests` wouldn't, because `dotnet build Content.Tests` alone was removing the copied DMStandard files.
Per ike, instead use the CopyDMStandard targets from DMCompiler.
=> Fix `dotnet test Content.Tests` not copying DMStandard

Content.Tests/DMProject/Tests/Builtins/world_config.dm, Content.Tests/DMTests.cs, DMCompiler/DM/DMObjectTree.cs, DMCompiler/DMStandard/Types/World.dm, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DreamProcAttribute.cs, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeWorld.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs
"env" is implemented but "admin" and "ban" are not. Pursuant to #289 and #290.
To test those changes, the following test suite fixes were made:
- Reset `DMObjectTree.Globals` between compilations so references to `world` are correct
- Reset `DreamManager.Globals` between runs to match
- Add runtime when dividing by zero; Const3.dm previously passed because of global confusion
- Use relative paths to `.dm` files to make test explorer easier to read
=> Implement world.GetConfig and SetConfig for environment variables

OpenDreamRuntime/Resources/DreamResourceManager.cs
BYOND automatically creates nonexistent dirs, so now we do too.
`CreateDirectory()` won't error if the dir already exists so there's no reason to add a check.
=> Fixes `fcopy()` not working if the dest directory doesn't exist

Content.Tests/DMProject/Tests/Regex/regex_l_test.dm, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectRegex.cs
It could stand to be more robust (mainly parsing an arbitrary number of preceding escapes) but it's good enough for most usecases
=> Implement regex `\l`

DMCompiler/DM/Visitors/DMASTSimplifier.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Previously, our exponent implementation would use the double-precision version of `Pow()`, despite this being a single-precision language. That has been fixed.
NOTE that our trig functions (plus `/proc/log()` and so on) still make use of the double-precision variants. **This is intentional,** as BYOND has the same bug and changing this literally breaks a few unit tests. I put a warning near where the trig functions are defined to stop anyone else who may think of the same thing.
- Fixed some unnecessarily-precise floating point operations throughout the codebase.
=> Removes some unnecessary/off-parity double-to-float conversions in the code

DMCompiler/Compiler/DMPreprocessor/DMMacro.cs
Properly escapes strings inside stringified macro arguments.
Fixes #799.
=> Fix macro params stringifying incorrectly

OpenDreamClient/Interface/Controls/ControlOutput.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/DreamManager.Connections.cs, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Resources/DreamResource.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs
- Make `world << browse(...)` send to all clients instead of erroring.
- Fix `browse('file')` without options causing an error. In the default skin (see #851) this would go to a default browser control, but in most skins it will probably do nothing.
Also:
- Fix tab characters being invisible in output controls by replacing them with 8 spaces. This isn't exactly like DM but it's better than them being invisible.
- Add `DreamResource.ToString` so it doesn't need to be special-cased in `DreamValue.ToString`.
=> Improve browse() functionality

Content.Tests/DMProject/Tests/Text/StringInterpolation6.dm, Content.Tests/DMProject/Tests/Text/StringInterpolation7.dm, DMCompiler/Compiler/DM/DMParserHelper.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Implements the \s and \th macros, with the only difference being that \th does not confirm it is directly after an expression and not replacing non-floats with 0.
=> Implement \s and \th macros

DMCompiler/DMStandard/Defines.dm, DMCompiler/DMStandard/Types/World.dm, OpenDreamRuntime/DreamManager.Connections.cs, OpenDreamRuntime/IDreamManager.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectWorld.cs
world.address and world.port are implemented, after a regression during RobustToolbox porting last year caused them to become commented out.
Makes #735 at least compile by setting up the associated `opendream_unimplemented`. Also went ahead and added every other one I could find in the ref; yell if I missed any.
Fixes #804.
- world.address and world.port have been added back in.
- Several world vars and procs now exist as unimplemented.
=> Implements world.address & friends, adds remaining opendream_unimplemented world vars/procs

Content.Tests/DMProject/Tests/Procs/late_proc_define.dm, DMCompiler/DM/DMObject.cs, DMCompiler/DM/DMObjectTree.cs, DMCompiler/DM/Expressions/Procs.cs, DMCompiler/DM/Visitors/DMObjectBuilder.cs
Fixes #869.
At first I thought that this would be arduous to set up, with the need for events or whatever, but it turns out that all that was needed was some short-circuiting during Object variable instantiation. :)
To elaborate a little, the superduper proc that instantiates all statics at runtime boot is only generated at the very end of DMObjectBuilder, after even DMProcBuilder has done its own work. So there was no real need to change any ordering, since by that point, all static declarations are already scanned.
This means that we can just, defer evaluating the static declaration's righthand-side until that point, no biggie. This is really just like, a five-line change; there's more diff than that here because I added a test, more comments, and did some minor code reorganization, in …
=> Fixes statics not allowing calls to late-defined procs

Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixAdd.dm, Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixInvert.dm, Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixMultiply.dm, Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixScale.dm, Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixSubtract.dm, Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixTranslate.dm, Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixTurn.dm, Content.Tests/DMProject/Tests/Builtins/Matrix/Shared/MatrixEquals.dm, Content.Tests/DMProject/Tests/Operators/equivalence.dm, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectList.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMatrix.cs, OpenDreamRuntime/Objects/MetaObjects/IDreamMetaObject.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamShared/Dream/IconAppearance.cs
Here, `operator~=` was implemented by rewriting things a little so that equivalence is handled within MetaObjects rather than relying on snowflake behaviour hard-wired into the operator itself. This should allow for easier support for operator overriding whenever we get that implemented.
I also went ahead and added correct `json_encode()`ing for /matrix.
Adding this new operator means I could also toss out a weird helper proc lying in our test suite, since this operator acts equivalently (heh) to it.
- Added support for the ~= operator for `/matrix`s.
- Using ~= instead of == on values that lack any special behaviour for that operator no longer causes an unimplemented exception.
- Fixed json_encode() not encoding /matrix values correctly.
- Added more unit testing for ~= and ~! operators. …
=> Adds operator~= and proper json_encode()ing for /matrix

DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/DMCompiler.cs, OpenDreamRuntime/DreamManager.cs
Fixes #793 by storing the path of the interface file relative to the json file, and adding a check to server initialisation that ensures the existence of the interface file.
=> Fix #793 - Relative pathing for interface and fileexists check

Content.Tests/DMProject/Tests/Preprocessor/whitespace_with_macro_functor.dm, DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs
Fixes #846.
This was a huge and confusing rabbit hole for me that took up an unhealthy portion of my evening, but here you go.
Added a unit test based on 846's snippet so we don't have to deal with this again.
- Macro calls no longer consume an extra token whenever parsed.
=> Fixes macro calls always consuming an extra token whenever parsed

DMCompiler/DMCompiler.cs
Whoops.
If you don't have `./` in the input to `Path.GetDirectoryName()` it returns an empty string, which throws an error for `Path.GetRelativePath()`. As such, calling `DMCompiler environment.dme` would throw an error.
=> Fix a little bug with file paths

Content.Tests/Content.Tests.csproj, Content.Tests/DMProject/Tests/Builtins/Replacetext.dm, OpenDream.sln.DotSettings, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
`replacetext()` can now take a `/regex` as a Needle and doesn't chop off the beginning and end of a string when using a non-default Start/End.
Also added a unit test to test some uses of the proc.
=> Improve `replacetext()` implementation

OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
`usr << browse(null, "window=windowname")` can be used to close a window. This wasn't working because the browse opcode didn't recognize `null` as a valid first argument.
=> Fix `browse()` being used to close popups

Content.Tests/DMProject/Tests/Savefile/BasicReadAndWrite.dm, DMCompiler/Compiler/DM/DMAST.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/DMProc.cs, DMCompiler/DM/Visitors/DMASTSimplifier.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, DMDisassembler/DMProc.cs, OpenDream.sln.DotSettings, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectClient.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMob.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectSavefile.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectWorld.cs, OpenDreamRuntime/Objects/MetaObjects/IDreamMetaObject.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
Savefiles now work again. This was achieved by turning statements containing only a left/right shift into an "output" or "input" statement. These statements can work on `DMReference` values instead of just DreamValues, allowing for special behavior with something like `savefile["ABC"] << 10`.
=> Reimplement savefiles

OpenDreamRuntime/DreamMapManager.cs
`x` and `y` on areas would not be set because they initialize to zero, and the code setting them checked if `currentPosition > newPosition` before setting them.
Also implemented `z`
=> Fix area coordinate vars

OpenDreamRuntime/Procs/DllHelper.cs
File missing and generic failure to load DLL now have separate error messages, plus fixes a bad parameter on the error message for a missing export.
=> Clears up a couple errors on external DLL loading

DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/DMCompiler.cs, DMCompiler/Program.cs
Purpose: serve /tg/station's need to sometimes `#define CBT`, `CIBUILDING`, `AUTOWIKI`, `TGS` at build time, currently satisfied by generating a `.m.dme` file with the `#define`s prepended.
Interface:
- `--define FOO` to define a macro with no expansion, for `#ifdef`
- `--define FOO=10+7` to define a macro which expands to some tokens, for `#if`
Also:
- Exit DMCompiler with status 1 if the command-line arguments were invalid
- Fix multiple-file inputs being processed in reverse order
=> Add `--define` flag to DMCompiler

Content.Tests/DMProject/Tests/Procs/typesof_invalid.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
=> Fixes `typesof()` for non-paths

Content.Tests/DMProject/Tests/Call/AsyncReturn.dm, Content.Tests/DMProject/Tests/Call/StackOverflow.dm, Content.Tests/DMProject/Tests/Call/SyncReturnInAsync.dm, Content.Tests/DMProject/Tests/Const/Const2.dm, Content.Tests/DMProject/Tests/Regex/regex_defer.dm, Content.Tests/DMProject/Tests/Sleeping/New.dm, Content.Tests/DMTests.cs, OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/Procs/AsyncNativeProc.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
This allows them to properly call procs in the current thread.
I've introduced `AsyncNativeProc.State.CallNoWait` here, which calls procs in the current thread but will force the called proc to have `waitfor=0` behaviour. This is something BYOND does in a few places.
I suppose the question is... is this a good approach, or do we want a `SyncNativeProc`?
~~This does require a test... a unit test will probably work since it doesn't defer~~
=> regex.Replace and replacetext are now AsyncNativeProcs and unit tests can be async

DMDisassembler/DMDisassembler.csproj, DMDisassembler/DMProc.cs, DMDisassembler/Program.cs, OpenDreamRuntime/Procs/ProcDecoder.cs, OpenDreamShared/Dream/Procs/ProcDecoder.cs
The debugger will benefit from being able to collect all `DebugLine` instructions in the code, but to do this it needs to disassemble the procs without executing them. Instead of just copy-pasting disassembly code, move much of it to a new `ProcDecoder`. Some if it may eventually be reusable in the runtime's `DMProc`, depending on memory/speed needs.
=> Move meat of DMDisassembler into OpenDreamRuntime

Content.Tests/DMProject/Tests/Builtins/Max.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
`max(null, ...)` would error because of attempts to compare null with numeric values. This now special-cases null `value` and null `max` properly.
Unit tests coming soon.
=> Fix issues with max(null, ...)

Content.Tests/DMProject/Tests/List/CreateAssociativeList.dm, DMCompiler/Compiler/DM/DMAST.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Visitors/DMVisitorExpression.cs
I wrap `DMASTIdentifier` nodes with `DMASTIdentifierWrapped` if they are surrounded in brackets.
Spooky... is this workable?
=> list(a = x, (b)= y) support

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Incorrect times would be returned if the timestamp was larger than an int could hold
=> Fix `time2text()` for larger values

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
It was previously throwing ArgumentException due to the same key being added twice. Taking the later value matches BYOND's behavior.
=> Fix json_encode() if an assoc list has duplicate keys

DMCompiler/DMStandard/Types/Client.dm, DMCompiler/DMStandard/Types/World.dm
Picked up that these were missing after doing some work on proc overrides.
- Fixed /world/proc/Error, /world/proc/Topic, and /client/proc/Del not being defined.
=> Adds /world/proc/{Error,Topic} and /client/proc/Del() to standard

DMCompiler/DMStandard/UnsortedAdditions.dm
`Error at code\databases\_quickdatabase.dm:56:121: Invalid property "_binobj" on type /database/query`
=> Stub `var/_binobj` on `/database/query`

OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Fix `arglist(null)` and other similarly non-list values
=> Fix `arglist(null)`

OpenDream.sln.DotSettings, OpenDreamShared/Resources/DMIParser.cs
[This line](https://github.com/OpenDreamProject/OpenDream/blob/5d8d904108e0c14987975a5be12fd5379819ea7c/OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectIcon.cs#L46) was allocating ~12 GB during Paradise initialization. This brings it down to ~2.1 GB.
This can certainly be brought down further, but it's a good start.
=> Reduce `DMIParser.ParseDMI()` allocations

OpenDream.sln.DotSettings, OpenDreamClient/Audio/DreamSoundEngine.cs, OpenDreamClient/Audio/IDreamSoundEngine.cs, OpenDreamClient/Rendering/DreamIcon.cs, OpenDreamClient/Resources/DreamResourceManager.cs, OpenDreamClient/Resources/ResourceTypes/DMIResource.cs, OpenDreamClient/Resources/ResourceTypes/DreamResource.cs, OpenDreamClient/Resources/ResourceTypes/ResourceSound.cs, OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectIcon.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeIcon.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamRuntime/Resources/ConsoleOutputResource.cs, OpenDreamRuntime/Resources/DreamResource.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs, OpenDreamShared/Dream/IconAppearance.cs, OpenDreamShared/Network/Messages/MsgRequestResource.cs, OpenDreamShared/Network/Messages/MsgResource.cs, OpenDreamShared/Network/Messages/MsgSound.cs, OpenDreamShared/Resources/DMIParser.cs
These changes fix up the `/icon` implementation quite a bit and lay a lot of the foundation needed for more complex operations.
- Icons can now contain icon states from multiple different images
- Icons can now generate their final .dmi file with the `GenerateDMI()` method
- These .dmi files can be sent to the client for use & display
- Resources now internally use IDs rather than file paths
Fixes #719
=> Proper `/icon` support

Content.Tests/DMProject/Tests/Preprocessor/Pragma/pragma_warning.dm, Content.Tests/DMProject/Tests/Preprocessor/Variadic/variadic_macro_functor.dm, Content.Tests/DMProject/Tests/Preprocessor/Variadic/variadic_must_be_last.dm, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/Compiler/DM/DMParserHelper.cs, DMCompiler/Compiler/DMM/DMMParser.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs, DMCompiler/DM/DMExpression.cs, DMCompiler/DM/DMObject.cs, DMCompiler/DM/DMObjectTree.cs, DMCompiler/DM/DMProc.cs, DMCompiler/DM/Expressions/Builtins.cs, DMCompiler/DM/Expressions/Dereference.cs, DMCompiler/DM/Expressions/LValue.cs, DMCompiler/DM/Expressions/Procs.cs, DMCompiler/DM/Visitors/DMObjectBuilder.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, DMCompiler/DM/Visitors/DMVisitorExpression.cs, DMCompiler/DMCompiler.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm, DMCompiler/Program.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamShared/Compiler/CompilerError.cs, OpenDreamShared/Compiler/Parser.cs, OpenDreamShared/Compiler/ParserHelper.cs, OpenDreamShared/Compiler/Token.cs
The syntax for `#pragma` that I am going with is probably `#pragma errorName Value`, where errorName can be either the error code or enum name for the error code, and Value is either `disabled`, `notice`, `warning`, or `error`.
This will allow us to vary the behaviour of the compiler, adding more warnings for bad behaviour, with users having the option to forbid the bad behaviour entirely.
- Argument parsing is now a bit smarter, and supports setting arguments to values.
- Fixed OD accepting macro functors that had several variadic arguments.
- New directive unlocked! `#pragma`, which allows both us and the user to decide the elevation of various error emissions.
=> Implements compiler configuration through new preproc directive: `#pragma`

OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
The code for this proc was commented during the transition to RobustToolbox. It has been replaced with the RT equivalent.
=> Reimplement `shutdown()`

DMCompiler/DMCompiler.cs
Maps can emit warnings, such as `Skipping type '/mob/living/simple_animal/cow'` when an invalid type is encountered,
The compiler would previously treat these like errors and not include them in the output.
=> Include maps with warnings in the output json

OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMovable.cs
Until a more complete implementation comes around.
Fixes close-up interactions in Paradise by fixing `/atom/movable.Adjacent()`
=> Make `/atom/movable.locs` return `list(src.loc)`

DMCompiler/DM/DMProc.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, DMCompiler/DMCompiler.cs, DMDisassembler/DMProc.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/DreamEnumerators.cs, OpenDreamRuntime/Procs/ProcDecoder.cs, OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
There is now a CreateFilteredListEnumerator which creates an enumerator that behaves like CreateListEnumerator's, except it will only enumerate DreamObjects of a certain type.
This removes the need to perform this filtering in the bytecode, cutting out 4 opcodes for every filtered for-loop.
=> Optimize for loops with implicit `istype()`s

.github/workflows/compiler-test.yml
We already run unit tests in both Windows and Linux in the other GitHub Actions workflow.
=> Stop running unit tests in the compiler CI action

.github/workflows/compiler-test.yml
Just another check to prevent compiler regressions. Uses my 64-bit rustg branch instead of actual Paradise master so we don't have to worry about Para breaking OD compilation.
=> Compile Paradise in CI

OpenDreamRuntime/Procs/Native/DreamProcNativeIcon.cs
TIL that native procs ignore the DM stub arg values.
=> Fix default `Blend()` arg values

DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/Compiler/DM/DMParserHelper.cs, OpenDreamShared/Compiler/Parser.cs
Whoops!
I noticed this, not in Yogs but in a stripped version of it where I had accidentally caused a brace block to not have its closing brace.
This resulted in the parser spinning indefinitely, creating a 200 MB/s memory leak. This fixes that :^)
- Fixed infinite loop in the compiler when a braced block could never find its end brace.
- Parsers now only attempt to record the first 50,000,000 warning/error emissions.
=> Fixes infinite spin / memory usage bug when a braced block can't find its ending brace

DMCompiler/Compiler/DMM/DMMParser.cs, DMCompiler/DM/DMObject.cs, DMCompiler/DM/DMObjectTree.cs, DMCompiler/DM/DMProc.cs, DMCompiler/DM/DMVariable.cs, DMCompiler/DM/Expressions/Builtins.cs, DMCompiler/DM/Expressions/Constant.cs, DMCompiler/DM/Visitors/DMObjectBuilder.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, DMCompiler/DM/Visitors/DMVisitorExpression.cs, OpenDream.sln.DotSettings, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Objects/DreamObjectDefinition.cs, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamRuntime/Procs/ProcDecoder.cs, OpenDreamShared/Dream/Procs/DreamProcOpcode.cs, OpenDreamShared/Json/DreamObjectJson.cs
The `PushPath` opcode has been split into 4 opcodes:
- `PushType`
- This existed before; it pushes an object type to the stack.
- `PushProc`
- This pushes a proc to the stack using its ID
- `PushProcStub`
- Pushes a `DreamValueType.DreamProcStub` DreamValue to the stack. This represents `/datum/proc`-like paths which point to all the procs of a type.
- `PushVerbStub`
- Like `PushProcStub` but for `/datum/verb` paths.
The compiler now tries to determine if a path points to a type, proc, or proc/verb-stub instead of this happening at runtime. This paves the way to removing heavy DreamPath usage.
=> Remove `PushPath` opcode

OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/Objects/DreamObjectDefinition.cs, OpenDreamRuntime/Objects/DreamObjectTree.cs
Verb inheritance was broken in #974 as part of the change to how `/atom.verbs` is constructed. This makes objects inherit verbs from their parents again.
=> Fix verb inheritance

DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, OpenDream.sln.DotSettings, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/DreamProcArguments.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeList.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Optimizes several procs by using an `IEnumerator<DreamValue>` to enumerate all of their given arguments instead of concatenating them into a new list.
- `cmptext()`
- `isarea()`
- `isloc()`
- `ismob()`
- `ismovable()`
- `isturf()`
- `max()`
- `min()`
- `typesof()`
- `/list.Remove()`
=> Optimize procs that enumerate over all arguments

Content.Tests/DummyDreamMapManager.cs, OpenDream.sln.DotSettings, OpenDreamRuntime/DreamMapManager.cs, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/IDreamManager.cs, OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectWorld.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DreamEnumerators.cs
Fixes #633 
A list of all atoms is now held in `DreamMapManager` instead of a DreamList on the `world` object. This speeds up the creation/deletion of atoms.
There is also now a special enumerator for `world.contents` which greatly speeds up loops like `for(var/atom/A in world)` by preventing an unnecessary copy of the huge list.
The `CreateFilteredEnumerator` opcode during Paradise initialization,
Before:
After:
=> Optimize `world.contents`

OpenDreamClient/Resources/ResourceTypes/DMIResource.cs, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Objects/DreamIcon.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectIcon.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeIcon.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs, OpenDreamRuntime/Resources/IconResource.cs
The server now caches the results of `DMIParse.ParseDMI()` instead of calling it again for every icon operation and `icon_states()` call. Based off of file extension, `DreamResourceManager.LoadResource()` will create an `IconResource` class holding the (lazily-loaded) texture and DMI info.
Paradise init before:
After:
=> Cache DMI parsing on the server

OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Objects/DreamObjectDefinition.cs, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Procs/AsyncNativeProc.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/InitDreamObject.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs, OpenDreamRuntime/Procs/NativeProc.cs, OpenDreamRuntime/Procs/ProcScheduler.cs
Every single proc call would create a new `ProcState`. When you've got hundreds of millions of proc calls, this adds up to a lot of memory usage. I made it so finished states could be reused so new ones doesn't need to be made. This cuts about 4GB of memory allocations during Paradise init.
- `ProcState` is now `IDisposable` and has `Dispose()` called when the state is no longer being used.
- `ProcState` now has an `Initialize()` method meant to prepare a state to be used again.
- `DMProcState._dreamValuePool` now uses an ArrayPool that isn't thread-safe for performance reasons. All DM runs on the main thread anyways.
Paradise init before:
after:
=> Pool all the types of `ProcState`

DMCompiler/DM/Visitors/DMVisitorExpression.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/DebugAdapter/DreamDebugManager.cs
I moved the part of `HandleInstruction()` that handled function breakpoints to a less-often called method. `HandleInstruction()` will also now only be called while stepping is actively happening, since `DreamThread.StepMode` can only change from `null` outside of `InternalResume()`.
=> Optimize `HandleInstruction()`

OpenDreamRuntime/Objects/DreamIcon.cs, OpenDreamRuntime/Procs/DMProc.cs
I don't see a reason for this safeguard to exist. The only time you'd want to copy the thread's enumerators when spawning is if you want to enumerate them inside that spawn. It isn't possible to even attempt that from DM so I removed the exception. This fixes `/mob/living/say()` in Paradise.
I also fixed an overlooked uninitialized field introduced in a recent icon rework.
=> Remove spawn-in-loop safeguard

DMCompiler/DMStandard/DefaultPragmaConfig.dm
BYOND doesn't care about attempts to undefine nonexistant macros, it doesn't even print any messages about it. I switched it from being an error in OD to a warning.
=> Make missing `#undef` directives a warning by default

Content.Tests/DMProject/Tests/Statements/Control Flow/empty_blocks.dm, DMCompiler/Compiler/DM/DMAST.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Visitors/DMASTSimplifier.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, DMCompiler/DMCompiler.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm, OpenDreamShared/Compiler/CompilerError.cs, OpenDreamShared/Compiler/Parser.cs
Fixes #751 by doing a *bunch* of facelifting of how set statements are constructed.
In fixing this, I ended up shotgun-debugging a lot of things surrounding how `set` statements are constructed. This PR also include some additional documentation added to various things, as I looked at them or touched them during development of this.
* Fixes `set` declarations not respecting commas, indented blocks, nor bracing.
* Blocks now very consistently evaluate their `set` statements first and foremost, before anything else, in a way that makes sense
* Use of the `in` keyword is now properly prohibited for all set use cases except 'src'
* `set src` now properly gives an unimplemented warning
* Slightly optimizes `DMASTProcBlockInner` by reducing empty array allocations.
* Removes …
=> Improves the grammar, functionality, and code quality of set declarations

OpenDreamClient/Interface/Controls/ControlBrowser.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamShared/Network/Messages/MsgOutput.cs
OpenDream would encode things like `json_encode("\"")` as `"\u0022"`, instead of the `"\""` that BYOND does. This fixes that.
This also runs `HttpUtility.JavaScriptStringEncode()` on a browser's ` << output()` before executing it in JavaScript to more properly escape its special characters.
=> Fix json encoding (`json_encode()`) of special characters

OpenDream.sln.DotSettings, OpenDreamClient/DreamClientSystem.cs, OpenDreamClient/Input/DreamCommandSystem.cs, OpenDreamClient/Input/DreamMacroManager.cs, OpenDreamClient/Interface/BrowsePopup.cs, OpenDreamClient/Interface/Controls/ControlButton.cs, OpenDreamClient/Interface/Controls/ControlChild.cs, OpenDreamClient/Interface/Controls/ControlLabel.cs, OpenDreamClient/Interface/Controls/ControlWindow.cs, OpenDreamClient/Interface/Controls/InterfaceControl.cs, OpenDreamClient/Interface/DMF/DMFParser.cs, OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs, OpenDreamClient/Interface/Descriptors/InterfaceDescriptor.cs, OpenDreamClient/Interface/Descriptors/MacroDescriptors.cs, OpenDreamClient/Interface/Descriptors/MenuDescriptors.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/DummyDreamInterfaceManager.cs, OpenDreamClient/Interface/InterfaceElement.cs, OpenDreamClient/Interface/InterfaceMacro.cs, OpenDreamClient/Interface/InterfaceMenu.cs
This adds support for `winset()`s that create new interface elements at runtime (macros, controls, and menus).
Fixes #759
=> Add support for runtime-created interface elements

OpenDream.sln.DotSettings, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectArea.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectClient.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectDatum.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectList.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMovable.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectSavefile.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectTurf.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectWorld.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeWorld.cs
`DreamList` would cache its ObjectDefinition to prevent an IoC resolve every time it was created. This led to an incorrect value in situations where the object tree was reset, such as in unit tests.
This changes it so that you create lists through `IDreamObjectTree.CreateList()` instead, always using an up-to-date ObjectDefinition.
=> Dont cache DreamList's ObjectDefinition

Content.Tests/DMProject/Tests/Operators/bitshift_assign.dm, DMCompiler/DM/DMProc.cs, DMCompiler/DM/Expressions/Binary.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/ProcDecoder.cs, OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
Fixes #922.
I just went ahead and added new opcodes for these, in symmetry with basically all of the other compound assignments.
&&= and ||= also could use some clean-up but I'm going to elect to leave that for after the Reference refactor gets merged, or whatever.
- Using `<<=` and `>>=` on complicated references no longer fails to compile.
- OD now "correctly" evaluates `null << 1` as `0`.
=> Fixes `<<=` and `>>=` use on complicated references, fixes `null << 1` not being `0`

OpenDreamShared/Dream/IconAppearance.cs
This reduces its memory allocations by ~100MB by removing a string concatenation, and shaves off ~50ms execution time during Paradise init.
Doesn't seem to have much of an effect on operations with the appearance dictionary.
=> Use the `HashCode` helper struct for hashing `IconAppearance`

OpenDreamClient/Interface/Prompts/InputWindow.cs, OpenDreamClient/Interface/Prompts/MessagePrompt.cs
Message prompts lost the ability to edit multiple lines of text during the switch to RobustToolbox due to RT not having a control capable of doing it. Now it does, so I switched it from using a `LineEdit` to a `TextEdit`.
=> Give message prompts a multi-line text editor

OpenDreamRuntime/Objects/DreamList.cs
DreamFilters were losing their type information because a compile time optimisation was replacing the serialisation manager's `CreateCopy()` with a static typed `CreateCopy<DreamFilter>()`. 
This just forces it to be dynamic, allowing filter parameters to work again.
=> Fix a bug with DreamFilters

DMCompiler/DMStandard/Types/Atoms/_Atom.dm, DMCompiler/DMStandard/Types/Client.dm, OpenDreamClient/Input/DreamCommandSystem.cs, OpenDreamClient/Interface/Controls/ControlInfo.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/InterfaceMacro.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/Input/DreamCommandSystem.cs, OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectClient.cs, OpenDreamShared/Network/Messages/MsgUpdateAvailableVerbs.cs
Several little things surrounding verbs and macros have been fixed
* /client verbs can now be used
* Verb commands are now space and case-insensitive
* Lowercase macros work now
* Display verbs alphabetically on the client
This combined with #1041 will be everything needed to get unmodified Paradise/SS13 controls working.
=> Several verb fixes

DMCompiler/Compiler/DM/DMParser.cs
This is no longer relevant now that we support try/catch
=> Remove outdated try/catch unimplemented-warning

Content.Tests/DMProject/Tests/Loop/For.dm, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DreamEnumerators.cs
Turns out the `for (i in 1 to 3)` variation of a for loop will leave `i` as `3` after the loop is finished (or unchanged if the end bound is lower than the start bound).
This differs from `for (i in list(...))` which will leave `i` as `null` after it's finished. IDreamValueEnumerator is now responsible for assigning the DMReference to account for this difference.
=> Some enumeration fixes

OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
The implementation of try/catch brought a change that made C# stack traces no longer show in DM errors. This makes `DMRuntime` (now `DMThrowException`) used only in `throw ...` statements so that the original C# exception can otherwise be kept throughout.
=> Show C# stack traces in DM errors again

DMCompiler/DMStandard/DefaultPragmaConfig.dm
Targets are full of these and it just creates warning spam.
=> Demote `#pragma EmptyBlock` to `notice`

OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
`TryGetValueAsFloat` returns false for an argument of `DreamValue.Null`, so negation fails instead of coercing null -> `0.0` like in DM. This fixes that.
An alternative approach would be to special-case `this == Null` in `TryGetValueAsFloat`, but that feels messy and unpredictable.
=> Fix negating null values

Content.Tests/DMProject/Tests/Builtins/flist.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Closes #1088 
At first I considered just checking if the dir exists first, but then I realized most flist() calls will presumably be for existing dirs, so that's added unnecessary overhead to every call whereas try/catch only adds overhead on calls for nonexistent dirs.
=> Fix `flist()` on nonexistent dirs

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
`TryGetValueAsFloat` returns false for an argument of `DreamValue.Null`, so clamp fails instead of coercing null -> `0.0` like in DM. This fixes that.
An alternative approach would be to special-case `this == Null` in `TryGetValueAsFloat`, but that feels messy and unpredictable.
=> Fix null arguments to clamp

DMCompiler/DMStandard/Types/Regex.dm
It's documented in the unicode notice for `regex.Find()`: https://www.byond.com/docs/ref/#/regex/proc/Find
=> Stub `regex.Find_char()`

DMCompiler/DMStandard/_Standard.dm, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Rewrites the `block()` builtin as a native proc
Performance before:
After:
=> Rewrite `block()` builtin in C#

OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
This was lost somewhere in the middle of adding try/catch support. Now it shows again.
=> Show the `CRASH()` message in the exception

OpenDreamClient/Interface/InterfaceMacro.cs
+UP and +REP are now replaced prior to SHIFT+, CTRL+, etc. This means that `SHIFT+UP` will properly become `SHIFT` with a `+UP` modifier, rather than `UP` (which is nonexistent) with a `SHIFT+` modifier.
=> Reorder +UP/+REP replacement in keybinds

DMCompiler/DMStandard/_Standard.dm
In BYOND, `jointext(string, *)` just returns the string passed to the function entirely unmodified, ignoring any further arguments (as far as I can tell, anyway). This PR replicates that as well as raises an error for passing something that isn't a string or list, like `jointext(12, null)`, just like in BYOND.
=> Fix jointext for string values

DMCompiler/DMStandard/_Standard.dm
Allows the `turn()` proc to call the (stubbed/unimplemented) `icon.Turn()` proc, as in BYOND.
=> Add turn() "support" for icons

OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMob.cs
Rather than erroring, trying to output a sound to a clientless mob now silently returns early, as in BYOND.
=> Make clientless mob sound output fail silently

Content.Tests/DummyDreamMapManager.cs, OpenDreamRuntime/DreamMapManager.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Large speedup for `for (var/area/A in world)` and `for (var/turf/T in world)` loops by enumerating a list containing only those types of atoms rather than all atoms.
Does as suggested in #327, though not for all atom types.
=> Optimize `in world` loops for `/area`s and `/turf`s

Content.Tests/DummyDreamMapManager.cs, DMCompiler/DMStandard/Types/Atoms/_Atom.dm, OpenDreamRuntime/DreamMapManager.cs, OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectArea.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMovable.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectTurf.cs
The /movables in a map cell are now tracked. `/turf.contents` is now a special list that uses that to prevent the need to do an entity lookup every time it's used.
Closes #1067
=> Create a special list tracking turf contents

DMCompiler/DMStandard/Types/Atoms/Movable.dm, DMCompiler/DMStandard/Types/Atoms/_Atom.dm, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs
Speed up `/atom/proc/<init>` and `/atom/movable/proc/<init>` by setting the built-in list vars inside their meta objects.
=> Speed up `/atom` and `/atom/movable` init times

DMCompiler/DMStandard/UnsortedAdditions.dm, DMCompiler/DMStandard/_Standard.dm
Winshow is effectively just a shorthand for using winset to set `is_visible=true`. This implements it as literally just that.
=> Add basic winshow implementation

Content.IntegrationTests/DMProject/code.dm, Content.Tests/DummyDreamMapManager.cs, OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamClient/Rendering/DreamIcon.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/DreamMapManager.cs, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeHelpers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamRuntime/Rendering/DMISpriteComponent.cs, OpenDreamRuntime/Rendering/ServerAppearanceSystem.cs, OpenDreamShared/Dream/ColorHelpers.cs, OpenDreamShared/Dream/ColorMatrix.cs, OpenDreamShared/Dream/DreamFilter.cs, OpenDreamShared/Dream/IconAppearance.cs, Resources/Prototypes/Shaders/dreamshaders.yml, Resources/Shaders/colormatrix.swsl, TestGame/code.dm
This was supposed to be me doing something very simple to dip my toes into the graphics side of this project, but lucky for me, this has been a total trap. After a few days of losing my mind, here's something that only works with novel RT code.
- Setting `/atom.color` to a color matrix now works.
- The color filter (instantiated by `filter(type="color",..)` now works.
=> Implements color matrices, allows `/atom.color` to be set with one

OpenDreamClient/EntryPoint.cs, OpenDreamShared/OpenDreamCVars.cs
Fixes #1023
Copies the one that @wixoaGit gave as an example on the issue.
User agent being shown in the logs:
```
[INFO] web.cef: CEF Version: 102.0.5005.63
[DEBG] web.cef: CEF command line: "C:\Projects\OpenDream\bin\Content.Client\OpenDreamClient.exe" --browser-subprocess-path="C:\Projects\OpenDream\bin\Content.Client\Robust.Client.WebView.exe" --no-sandbox --user-agent="Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6
.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0) " --lang=en-US --log-file="C:\Projects\OpenDream\bin\Content.Client\debug.log" --resources-dir-path="C:\Projects\OpenDream\bin\Content.
Client\runtimes\win-x64\native\cef_resources" --locales-dir-path="C:\Projects\OpenDream\bin\Content.Client\r …
```
=> Add Trident/7.0 to browser's user agent

Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixInvert.dm, Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixLint.dm, Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixUndocumented.dm, DMCompiler/DM/DMExpression.cs, DMCompiler/DM/Expressions/Procs.cs, DMCompiler/DM/Visitors/DMVisitorExpression.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm, DMCompiler/DMStandard/Defines.dm, DMCompiler/DMStandard/Types/Matrix.dm, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMatrix.cs, OpenDreamRuntime/Procs/DreamProcArguments.cs, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeMatrix.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamShared/Compiler/CompilerError.cs, OpenDreamShared/Dream/MatrixOpcodes.cs
Fixes #1055, but not completely, since I skipped over the undocumented matrix opcodes that our targets do not use.
Amy recently pointed out that Paradise (and apparently also Goon) use this esoteric /matrix signature whose documentation only exists as an incomplete blog post written by Lummox 8 years ago.
Being as we target them, here is some support for that. Despite my laziness, I did end up converting some /matrix procs into natives to make it easier for these odd signatures to call into them.
While I was here, I also added linting against /matrix() calls within the compiler. We now correctly compiletime when /matrix() is called with too many arguments, as BYOND does. In addition, I've added a new pragma for detecting other bad /matrix calls (such as calling with only 5 arguments, or …
=> Implements all of the undocumented matrix constructors that targets use, adds compiletime linting of `/matrix()` calls

DMCompiler/DMStandard/_Standard.dm
A temporary implementation until we properly track ref-counts.
Related to #858
=> Stub `refcount()` with a fake ref count

OpenDreamClient/Interface/Controls/ControlBrowser.cs
Fixes #1125 
TG's usage won't work until https://github.com/OpenDreamProject/OpenDream/pull/1121 is also merged.
Tested it with the following tossed in a verb (requires the other aforementioned PR to work):
`usr << browse("<a href=\"byond://winset?size=100x10&command=.quit\">Quit</a>", "window=quitbutton")`
=> Embedded `winset`

DMCompiler/Compiler/DM/DMLexer.cs
We're in that weird transitionary 514 -> 515 period where supporting both functionalities is somewhat desirable.
In the future we need to properly separate these before ~~goonstation~~ some SS13 codebase manages to rely on the distinction
=> "Implement" `call_ext()`

OpenDreamShared/Dream/ColorMatrix.cs
The sole intent of this is to make equality non-allocating in the Renderer PR, and fix a massive memory churn.
If we ever actually want to have a normal equality method for this struct, it should implement `IEquatable<>`. This function is solely to shoo away the C# boxing demons and unambiguously *force* no allocation.
Should save some several gigabytes of churn when running target codebases.
=> Adds a fast-path equality method to `ColorMatrix`

DMCompiler/DMStandard/Types/Atoms/Movable.dm
This code called Entered and Exited on *all the contents of an entered turf,* which is incorrect and led to problems. It should only call Crossed/Uncrossed instead.
=> Fix incorrect Entered/Exited code

OpenDreamRuntime/DreamValue.cs
DreamValue wasn't treating deleted DreamObjects as null when checking their equality.
This would lead to the following code example giving `0` instead of `1`:
```
var/list/L = list(new /datum)
del L[1]
world.log << (null in L)
```
=> Null out deleted DreamObjects before comparing DreamValues

Content.Tests/DMProject/Tests/List/RemoveKey.dm, OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectList.cs
Removing a key from a list using `-=` wouldn't remove the value associated with it if one existed.
=> Remove associated values from list when removing the key

OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectImage.cs
`new /image(new /datum)` creates a default image
`atom.appearance = null` and `image.appearance = null` is ignored
`atom.overlays |= new /datum` appears to do nothing, but still adds an entry to the list. Meaning it's probably an empty appearance.
=> Fixes a few cases where invalid appearance sources had differing behavior

OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
A `/client` can also be used as the first argument in an `input()` call.
=> Fix using a client as the first arg to `input()`

OpenDreamClient/Interface/Controls/ControlButton.cs, OpenDreamClient/Interface/Controls/ControlInfo.cs
The margin on buttons was causing some clipping issues on smaller sizes.
OpenDream before:
OpenDream after:
BYOND:
=> Fix margin on DMF buttons

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
These currently spam the console with errors. We can safely ignore them since they're just a visual effect.
=> Silently ignore unimplemented animation arguments

Content.Tests/DMProject/Tests/Text/StringInterpolation7.dm, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
For some mystical byond comprehension reason byond will convert 4.52 to 4. should fix that without creating any extra bugs.
=> Fixes \th interpolation

OpenDreamClient/Rendering/DreamIcon.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectImage.cs, OpenDreamShared/Dream/IconAppearance.cs
`/image` has this undocumented "feature" where setting the dir in the constructor (but not afterwards) will force overlays to have that direction, rather than inheriting a direction from their owner. I also fixed a bug in `/image.appearance = value`, the image's `dir` is supposed to stay as it is.
Fixes many overlays in Nebula. I don't see any changes on Paradise but it probably has an effect in a more niche use somewhere.
=> Fix a bug with overlay dir inheritance

OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/DreamMapManager.cs, OpenDreamRuntime/IDreamManager.cs, OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectArea.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMob.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMovable.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectObj.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectWorld.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/DreamEnumerators.cs, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
I split up the `AllAtoms` list into a different list for each type of atom (`/area`, `/turf`, `/atom/movable`, `/obj`, and `/mob`). This speeds up the `IndexOf()` that happens every time an atom is deleted.
I also turned the `Datums` list into a hash set to speed up the removal when a datum is deleted.
Resolves #387 by implementing the idea.
This intends to fix the runaway garbage subsystem queue problem that happens after running a server for multiple hours.
=> Optimize `del()`

DMCompiler/DMStandard/Types/Datum.dm
unimplemented stub for savefiles https://secure.byond.com/docs/ref/#/datum/proc/Read
=> Stub `Read()`

OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs
A one-off error was keeping global regexes from advancing forward
=> Fix `/regex.next` var

Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixMultiply.dm, Content.Tests/DMProject/Tests/Builtins/turn.dm, DMCompiler/DMStandard/Types/Matrix.dm, DMCompiler/DMStandard/_Standard.dm, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectIcon.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMatrix.cs, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeIcon.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeMatrix.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamShared/Dream/AtomDirection.cs
This rewrites three procs that were previously written in DM to be written in C#.
This is mainly done for performance reasons, but also comes with many other benefits including more comprehensive debugging, better failure modes, access to actual types, and all the various goodies.
Builds off work done in #1064
See self-review for more annotations on specific code sections.
Dev testing and unit tests all passed.
| Impl  | Operation (800,000 loops) | Time |
| ------------- | ------------- | ------------- |
| DM | Matrix.Multiply | 77ds |
| C# | Matrix.Multiply | 65ds |
**15.6%** increase in perf 
| Impl  | Operation (800,000 loops) | Time |
| ------------- | ------------- | ------------- |
| DM | Matrix.Turn | 80ds |
| C# | Matrix.Turn | 49ds |
**38.75%** increase in perf
| Impl  | …
=> Rewrite `turn()`, `/matrix.Turn`, and `/matrix.Multiply` builtins in C# 

Content.Tests/DMProject/Tests/Builtins/turn.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
It was attempting to cast an int to a DreamValue directly. I also fixed a bug where it could return 0.
This was triggered by this code in Paradise, which is probably another bug in itself that needs looked into (`dir` was 0):
```
/obj/structure/disposalpipe/segment/Initialize(mapload)
. = ..()
if(icon_state == "pipe-s")
dpdir = dir | turn(dir, 180)
else
dpdir = dir | turn(dir, -90)
update()
```
=> Fix `turn()` with an invalid first arg

OpenDreamClient/Rendering/DreamViewOverlay.cs
Makes it easier to get an overview of which parts of the rendering is slow. Also changes the lookup flags to use approximate lookups, seeing as lookup area is already arbitrarily scaled up.
=> Add profiler groups to dream overlay

OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs
Resources have IDs now so we can remove this hack.
=> Use IDs when creating DreamResource refs

Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixUndocumented.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
`matrix(mat, angle, MATIRX_ROTATE)` specifically. With an unit test to make sure it works.
Also fixed an error message in the MATRIX_ROTATE part of the constructor code. Previously it always printed the uninitialized angle 0 instead of the actual argument it got.
=> One missed undocumented matrix() constructor

OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Objects/DreamObject.cs
Using a client in a string (such as `"[usr.client]"`) will now give you the client's key instead of its type (`"/client"`)
Fixes a bunch of places where "/client" would appear instead of player's usernames in Paradise.
=> Fix `/client` stringification

OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs, Resources/Prototypes/Shaders/dreamshaders.yml, Resources/Shaders/drop_shadow.swsl, TestGame/code.dm
Implements the `drop_shadow` filter, necessary for the ambient occlusion effect used in SS13.
Still want to finish the offset var and inset shadows.
Checks an item in #830
=> Add drop_shadow filter

OpenDreamClient/Resources/DreamResourceManager.cs
Trying to send a file to a path like `foo/bar/page.html` currently fails. ~~This PR makes it so the `foo` and `foo/bar` directories are created properly.~~ This PR strips `foo/bar/` from the path and creates `page.html` directly in the base cache directory, just like BYOND.
=> Support for subdirectory paths for browse_rsc

OpenDreamRuntime/DreamValue.cs
Shaves off 3.3 seconds in Paradise init profiling. Also see https://github.com/OpenDreamProject/OpenDream/issues/1204
=> Optimize `DreamValue.Equals()`

OpenDreamClient/Interface/DMF/DMFParser.cs
For example `command=.observe_round` failed to parse. I'm unsure if this is the correct way to do this or if it should be more general / in other places too.
=> Parsing of DMF attributes that are hidden verbs

OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/InterfaceMacro.cs
PR adds support for the `ANY` keybind in BYOND.
Remaining issues:
- Both here and in BYOND the ANY macro and the specific macro (if there are both) fire. However, in BYOND it seems that the order of them firing is determined by the position in the dmf macro definition while in this implementation the ANY macro always fires first. However, this is a fairly minor issue and I sure hope no one relies on it. (clueless)
- The ANY keybind does only a rudimentary check for keyboard focus unlike regular keybinds which go through RT's whole pipeline. This might result in some differences in behaviour but I was not able to spot anything specific right now.
Misc changes:
- keybind modifiers (ctrl, shift, alt) should now work as far as I can tell
- the REP+UP check now correctly looks at the …
=> Support for ANY macro keybind

OpenDreamClient/Input/DreamCommandSystem.cs, OpenDreamClient/Interface/Controls/ControlMap.cs
You can shift-click atoms now, and `.winset` strips out the outer quotes which fixes hotkey mode on Paradise.
=> Fix shift-clicking and the `.winset` command

OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/DreamMapManager.cs
Cache the results of `CreateAppearanceFromDefinition()` since these values never change.
Before:
After:
=> Optimize `CreateAppearanceFromDefinition()`

OpenDreamShared/Dream/ScreenLocation.cs
Ignores any whitespace inside screen_loc. Fixes cyborgs on Paradise.
=> Ignore all whitespace in screen_loc

Resources/manifest.yml
Launcher will use this in the next version to disable Steam Overlay and fix all the bugs with it.
=> Specify multiWindow in content manifest

Content.Tests/DMProject/Tests/Builtins/text2path.dm, DMCompiler/DM/DMProc.cs, DMCompiler/DM/Visitors/DMObjectBuilder.cs, OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamShared/Json/DreamProcJson.cs
Implements `text2path` for proc paths. In order to do this correctly we need to know whether a proc was declared as `proc/` or `verb/` so this information is now passed from the compiler and stored in proc classes. Proc path stringification now also correctly uses `"proc/"` and `"verb/"` based on this.
Also fixes incorrect values for `text2path("")` and `text2path("/")`
=> Implementation of text2path for proc paths and related fixes

DMCompiler/DMStandard/Types/Client.dm, OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/IDreamManager.cs, OpenDreamRuntime/Objects/DreamList.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectArea.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectClient.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Rendering/ServerScreenOverlaySystem.cs
This moves `/atom.overlays`, `/atom.underlays`, `/area.contents`, `/client.screen`, and `args` into their own special DreamList types. This allows them to handle more operations than just adding/removing, and allows for the removal of the events on DreamList.
Resolves #1210
Fixes #1089
=> Get rid of DreamList event handlers

OpenDreamRuntime/EntryPoint.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectSavefile.cs
Flushing every savefile change to disk is a fairly costly operation.
=> Don't flush savefile changes until shutdown

OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMovable.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectTurf.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeHelpers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Optimizes pieces of code that get an atom's position by getting their position directly instead of going through `GetVariable()`.
Similarly optimizes `IsObjectVisible()` too by getting an atom's invisibility through its appearance directly. This brings its total runtime during Paradise init from ~1000ms to ~250ms on my computer.
=> Optimize getting an atom's position and `IsObjectVisible()`

DMCompiler/DM/Visitors/DMProcBuilder.cs, OpenDreamRuntime/DreamThread.cs
Woopsie.
I also marked it as implemented. There's additional behavior on both the compiler side and the runtime to support printing the description as help text and doing some funky arg parsing in the process, but I've literally never seen it before so I think we can safely downgrade the unimplemented warning to a TODO.
See https://www.byond.com/docs/ref/#/verb/set/desc for what I'm talking about.
=> Fix accessing `verb.desc` and mark it as implemented

DMCompiler/Compiler/DM/DMParserHelper.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm, OpenDreamShared/Compiler/CompilerError.cs
Invalid text macros like `"\a vendomat"` now have the error code `OD2500` instead of `OD0000`
Also makes it a warning by default, since this passes without error in BYOND
=> Add a new `MissingInterpolatedExpression` pragma

OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectIcon.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeIcon.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamRuntime/Procs/NativeProc.cs
The existence of this constructor makes it too easy to provide the wrong value and create an invalid DreamValue.
`_NativeProc_TurnInternal()` and `DreamProc.GetField()` were both incorrectly using this constructor.
=> Remove `new DreamValue(object)` constructor

Content.Tests/DMProject/Tests/Regex/regex_advance.dm, Content.Tests/DMProject/Tests/Regex/regex_proc_replacement.dm, Content.Tests/DMProject/Tests/Regex/regex_start.dm, DMCompiler/DMStandard/Types/Regex.dm, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectRegex.cs, OpenDreamRuntime/Procs/AsyncNativeProc.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs
- fix of keyword arguments for regex `Find` and `Replace` (docs say they are Start and End but they are actually start and end)
- fix of some cases where start greater than string length resulted in a runtime
- fix of regex.Find `next` advancement persisting between different haystack strings
- some off by one error that resulted in the last match not being found if it was at the end of the string I think?
- implemented proc replacement for global regexes
- in order to do the previous `CallNoWait`'s task creation source now runs continuations asynchronously. Without this the continuations are run in `SetResult` which together with `_inResume` leads to the second proc invocation not running at all
- unit tests for the above
=> Regex fixes and additions

OpenDreamRuntime/Resources/DreamResourceManager.cs
dm ref for `text2file` says "If the file does not exist, one will be created."
previously it doesn't if there's an uncreated directory in the way.
- Expect: `root/folder_that_doesnt_exist_yet/thing.txt` to be created when I give it as a path
- What actually happens: `System.IO.DirectoryNotFoundException: Could not find a part of the path 'root/folder_that_doesnt_exist_yet/thing.txt'`
so, create it first. GetParent only returns `null` if the `absoluteFilePath` is the root of the entire filesystem. Reasonable to not create the directory if that is the case.
=> text2file: create parent directories for path arg

DMCompiler/DM/DMProc.cs
The return value of the implicit `sleep(-1)` call in procs with `set background = 1` wasn't being popped.
=> Fix runaway stack growth with background procs

Content.Tests/DMProject/Tests/Loop/GlobalLoop.dm, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Loops like `for (var/datum/foo/D)` were enumerating every `/datum` instance rather than every `/datum/foo` instance.
=> Fix type filter for global datum loops

OpenDreamClient/Interface/Controls/ControlBrowser.cs, OpenDreamRuntime/DreamConnection.cs
Values with spaces were being cut off after the first space. This broke the close button in TGUI because it uses an embedded winset formatted as `byond://winset?command=uiclose 1234_1234`.
=> Wrap embedded winset parameters in quotes

OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/IDreamManager.cs, OpenDreamRuntime/Objects/DreamObject.cs
`ref()` IDs for DreamObjects were using `ReferenceIDs.Count` which led to them being reused when a DreamObject is deleted.
I also optimized `locate()` for DreamObjects by creating a second ID->DreamObject dictionary.
Fixes #338
=> Don't reuse DreamObject ref IDs

Content.Tests/DMProject/Tests/List/ListJoin.dm, DMCompiler/DMStandard/Types/List.dm, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeList.cs
Massively improves its performance, especially on large lists.
=> Rewrite `/list.Join()` in C#

Content.Tests/DMProject/Tests/Expression/String/multi_arg.dm, DMCompiler/Compiler/DM/DMParser.cs
Fixes one of the two compilation errors in latest TG and adds it to the unit test.
I tried finagling the token checks in several different ways but this just ended up being the simplest that didn't break any tests.
=> Fix `...` parsing

OpenDreamRuntime/DreamValue.cs
Essentially the only difference between `TryGet` and `MustGet` now is whether it returns false or throws an `InvalidCastException`.
=> Make a bunch of `GetValueAs` calls unsafe

Content.Tests/DMProject/Tests/Expression/Constants/data/test.txt, Content.Tests/DMProject/Tests/Expression/Constants/resource.dm, Content.Tests/DMProject/Tests/Expression/Constants/resource_not_exists.dm, DMCompiler/DM/Expressions/Constant.cs
1. Support relative resource paths: resource paths can be set relatively to the .dm source file.
2. Emit compile error when resource file doesn't exist
3. Test loading of resource files
fix #1087
=> feat(DMCompiler, Constant): support relative resource paths

Content.Tests/DMProject/Tests/Builtins/Matrix/MatrixNew.dm, DMCompiler/DMStandard/Types/Matrix.dm, OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMatrix.cs
Rewrites /matrix.New to be in C#
This is mainly done for performance as well as better failure modes/parity and general code safety.
Natural continuation of #1117 & #1236
Dev testing was fairly comprehensive and unit tests all pass.
| Impl  | Operation (1,200,000 loops) | Time |
| ------------- | ------------- | ------------- |
| DM | Matrix.New | 84ds |
| C# | Matrix.New | 52ds |
**~38.1%** increase in perf 
<details>
<summary>Details</summary>
<pre>
/world/New()
..()
sleep(5)
var/t = world.timeofday
for (var/i in 1 to 1200000)
one()
world.log << "elapsed: [world.timeofday - t]ds"
var/global/Glob = null
/proc/one()
var/matrix/M = matrix(1,2,3,4,5,6)
var/matrix/N = matrix()
var/matrix/B = matrix(M)
Glob = B</pre>
</details>
=> Rewrites /matrix.New to be in C#

OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs
`/atom.transform` attempts to clone the transform by initializing it with the current value as an argument. This caused problems if you attempted to read it before setting it since the current value would be `null`. Now it instead creates a new matrix from the current appearance's transform which doesn't have this problem.
=> Fix `/atom.transform` read-before-assign

OpenDreamRuntime/Objects/DreamIcon.cs
This shaves off ~160MB of allocations and ~200-400ms of execution time on `DreamIcon.GenerateDMI()`
=> Pool the DreamIcon pixel arrays

OpenDreamRuntime/Procs/DMProc.cs, OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
Brought my Paradise init down to 41.9 seconds.
=> Put `AggressiveInlining` on operand reading methods

OpenDreamRuntime/Objects/Types/DreamList.cs
In this code snippet there won't be two `/proc/foo` values in the list despite `+=` being used instead of `|=`
```
mob.verbs += /proc/foo
mob.verbs += /proc/foo
```
Fixes #165
=> Ignore duplicate values being added to the `verbs` lists

OpenDreamRuntime/Procs/DebugAdapter/DreamDebugManager.cs
This makes it easier to find a global from the huge list. In the future it may be better to only show globals used by the current proc.
=> Show globals in alphabetical order in the debugger

Content.Tests/DMProject/Tests/List/AssocListAdd.dm, OpenDreamRuntime/Objects/Types/DreamList.cs
Adding two associative lists with either `+` or `+=` wasn't keeping the associative values from the second list.
=> Fix adding two associative lists

OpenDreamClient/Resources/ResourceTypes/DreamResource.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Also make the client's `DreamResource` non-abstract to fix a bug with sending resources the client hasn't already received.
=> Allow `usr << ftp()` to send /icon

OpenDreamRuntime/Objects/DreamIcon.cs, OpenDreamRuntime/Objects/Types/DreamObjectIcon.cs, OpenDreamShared/Resources/DMIParser.cs
Fix some /icon bugs related to blending other icons, drawing frames, and generating DMI metadata.
The socks now rotate.
=> Fix some /icon bugs

OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
`OutputReference` was pushing null onto the stack, which is incorrect and led to stack errors.
=> Remove `OutputReference` opcode's push

Content.Tests/DMProject/Tests/Builtins/params2list.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Fixes some weird uses of `params2list()` and adds a test case for them.
Fixes the mining shuttle console on Paradise.
=> Fix some uses of `params2list()`

Content.Tests/DMProject/Tests/Builtins/Replacetext.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Fixes the "Requirements" section of Paradise's crafting menu.
=> Add support for negative Start/End values in `replacetext()`

OpenDream.sln.DotSettings, OpenDreamShared/Resources/DMIParser.cs
DMIs created with `/icon` now have working animation frame delays.
The title screen on Paradise doesn't flash 5 times a second anymore.
=> Include frame delays in generated DMIs

DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/DM/Expressions/Constant.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm, OpenDreamShared/Compiler/CompilerError.cs
The compiler now does a case-insensitive search for both the directory and file of a resource. I also added an `AmbiguousResourcePath` warning that tells you when there are multiple files that match a resource's path.
Fixes #591
=> Perform a case-insensitive search for resource files

Content.Tests/DMProject/Tests/Savefile/override_datum.dm, DMCompiler/DMStandard/Types/Datum.dm
It will not get #1303 fixed, but it will stop the compiler from complaining about it not existing.
=> Add missing `Write(savefile)` to OD `/datum`

DMCompiler/DMStandard/Types/Atoms/_Atom.dm, OpenDreamClient/EntryPoint.cs, OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamRuntime/AtomManager.cs, OpenDreamShared/Dream/ViewAlgorithm.cs
I implemented the view algorithm using Lummox's description of it in [this forum post](https://www.byond.com/forum/post/2130277#comment20659267).
I haven't hooked it up to the `view()` procs yet,  but I made the client use it to decide what turfs to render. Results appear to be equal to BYOND's.
The algorithm itself is agnostic to whether it's running on the client or server, so getting it to work on the server is just a matter of filling an array with information about a tile's opacity and luminosity.
=> Implement the view algorithm

DMCompiler/DMStandard/Types/Atoms/Mob.dm, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamRuntime/Objects/Types/DreamObjectMob.cs, OpenDreamShared/Rendering/DreamMobSightComponent.cs, OpenDreamShared/Rendering/SightFlags.cs
Implement enough of `/mob.sight` to allow observers to see through walls. Having either `SEE_OBJS` and `SEE_MOBS` currently acts like both are enabled.
#72
=> Implement `SEE_TURFS` and `SEE_OBJS`/`SEE_MOBS`

Content.Tests/DMProject/Tests/Statements/Control Flow/label_before_var.dm, DMCompiler/Compiler/DM/DMParser.cs
- Fixes #1032 
So, turns out the code that I removed finds a statement if the label does not correspond to a properly scoped block (by indentation or bracing), it takes the next statement after the label and wraps it in its own scope. Which has the undesirable effect of moving local variables one wrong scope down and causing other issues related to the parser eating tokens when it should not. - The variable declaration in #1032 instead becomes an assignment expression.
While this would be true for named loops, it seems to be largely inconsequential and the best practice is to intent the loop body anyway. Plus the AST-nodes for the loops do not have any kind of polymorphism to distinguish them from other proc statement nodes. The solution to straight-up remove the feature had no regression …
=> Remove unncessary single-statement labels

DMCompiler/DMStandard/Types/Client.dm, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/Objects/Types/DreamObjectClient.cs
Allows you to set `/client.eye` to an /atom/movable object. BYOND also supports /turf here, but I left that unimplemented currently since turfs aren't an entity we can attach to.
Makes AI playable and the slime management console usable.
Fixes #1165
=> Implement `/client.eye`

OpenDreamClient/Rendering/DreamViewOverlay.cs
I don't know why this isn't caught by the try/catch, but it isn't and it causes a segfault for me when I'm not running in the debugger.
=> Fix null deref in client when appearance hasn't loaded

OpenDreamClient/Audio/DreamSoundChannel.cs, OpenDreamClient/Audio/DreamSoundEngine.cs, OpenDreamClient/Audio/IDreamSoundEngine.cs, OpenDreamClient/EntryPoint.cs, OpenDreamClient/Resources/ResourceTypes/ResourceSound.cs
At the end of every engine update, look for any audio channels that have finished and dispose of them. This seems to fix the AL memory errors that would start after a few minutes and prevent audio from playing.
Also fixed a few nullability warnings in the audio code.
=> Dispose finished audio channels

Content.Tests/DMProject/Broken Tests/Operators/valid_and_null.dm, Content.Tests/DMProject/Broken Tests/Operators/valid_and_null_assign.dm
Salvaged the runtime operator tests from op overloads work I did.
Right now both of these fail, so added them to the broken tests folder.
=> Add a couple broken tests for operators

Content.Tests/DMProject/Tests/Text/StringInterpolation7.dm, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
=> Implement `\th` for more non-float types

Content.Tests/DMProject/Tests/Text/ref.dm, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/IDreamManager.cs
type IDs are accurate for major types but does not fully adhere to [*the list*](https://gn32.uk/f/byond-typeids.txt) but otherwise make \ref return a string formatted like `[0x1000000]`
=> Make \ref[] format the same as byond

Content.Tests/DMProject/Tests/List/AssocListCombine.dm, OpenDreamRuntime/Objects/Types/DreamList.cs
=> Copy associated values when using `|=` with two lists

OpenDreamRuntime/Objects/Types/DreamObjectClient.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
According to the DM reference,
> If no name is specified and the value is a list, this is the same as calling stat on each item in the list.
I also fixed setting `/client.statpanel` since most of the logic was already there. The setter was just commented out.
=> Add support for a /list value in `stat()`

DMCompiler/Compiler/DM/DMAST.cs, DMCompiler/Compiler/DM/DMParser.cs
Fixes statements like `usr << (browse(...))`
Adds a new `GetUnwrapped()` method to `DMASTExpression` that returns the expression inside a `DMASTExpressionWrapped`
Fixes #1333
=> Fix wrapped output statements

DMCompiler/DM/DMObject.cs, DMCompiler/DM/DMProc.cs, DMCompiler/DM/Visitors/DMObjectBuilder.cs, DMCompiler/DM/Visitors/DMVisitorExpression.cs, DMCompiler/DMStandard/_Standard.dm, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/IDreamManager.cs
Aims to fix var/proc ordering issues by removing the late-var-def and late-object-def events in DMObjectBuilder and replacing them with these 9 steps in `BuildObjectTree()` (as copy-pasted from code comments):
1. Define every type in the code. Collect proc and var declarations for later.
2. Define every proc and proc override (but do not compile!). Collect static vars inside procs for later.
3. Create the static vars inside procs
4. Define vars
5. Attempt to resolve all vars that referenced other not-yet-existing vars
6. Apply var overrides
7. Create each types' initialization proc
8. Compile every proc
9. Create & Compile the global init proc
There is still only one pass over the entire AST, the relevant pieces are added to lists for processing later.
Passes all the existing unit tests, …
=> Split DMObjectBuilder into several steps

DMCompiler/Compiler/DM/DMParser.cs
Previously, a phrase like "a/b/operator/c" would be interpreted by Path() as an imminent `a/b/operator/()` divison overload, to be followed by a `c` identifier token.
This was causing compile errors in Yogs, where NTSL makes use of a legit type called operator.
This allows Yogs to compile :^)
- Using `operator` as a type name is now allowed and behaves similarly to BYOND.
=> Fixes "operator" not working as a valid type name

OpenDreamRuntime/Objects/Types/DreamList.cs, OpenDreamRuntime/Objects/Types/DreamObjectImage.cs
Fixes `overlays.Copy()` which fixes `cut_overlays()` in SS13
Also made `/mutable_appearance.overlays`/`underlays` more accurate to BYOND behavior
=> Implement `DreamOverlaysList.GetValues()`

DMCompiler/DMStandard/Types/Atoms/Mob.dm, DMCompiler/DMStandard/Types/Client.dm, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/Objects/Types/DreamObjectClient.cs
The DM reference lies here. It says `/mob/Login()` sets `/client.statobj` but it's actually `/client/New()` that does this. Not calling `..()` in mob's Login will still result in `statobj` being set. This is not the case in client's New.
Fixes stat panels in modern Paradise.
=> Fix default `/client.statobj` assignment

Content.Tests/DMProject/Tests/List/ListCut.dm, OpenDreamRuntime/Objects/Types/DreamList.cs
`/list.Cut()` was not removing the values associated with what was being removed.
=> Remove associative values in `/list.Cut()`

OpenDreamClient/Interface/DreamInterfaceManager.cs
Using the window name can be problematic since that can contain slashes. The DM reference says it generates a unique name anyways.
=> Use random filenames for `browse()`

DMCompiler/DMStandard/Types/World.dm
- defines `timezone`, see #1301 
- defines `executor`, see #1353 
It will not fix or close those issues, but it should not block any code using those from compiling
=> Define two missing `world` vars

DMCompiler/DM/Visitors/DMVisitorExpression.cs
The expression `(injures[injure]).len` is now treated as `(injures[injure]):len`
=> Make `(L[1]).property` dereferences fuzzy

OpenDreamClient/Interface/BrowsePopup.cs, OpenDreamClient/Interface/Controls/ControlBrowser.cs, OpenDreamClient/Interface/Controls/ControlButton.cs, OpenDreamClient/Interface/Controls/ControlChild.cs, OpenDreamClient/Interface/Controls/ControlGrid.cs, OpenDreamClient/Interface/Controls/ControlInfo.cs, OpenDreamClient/Interface/Controls/ControlInput.cs, OpenDreamClient/Interface/Controls/ControlLabel.cs, OpenDreamClient/Interface/Controls/ControlOutput.cs, OpenDreamClient/Interface/Controls/ControlTab.cs, OpenDreamClient/Interface/Controls/ControlWindow.cs, OpenDreamClient/Interface/Controls/InterfaceControl.cs, OpenDreamClient/Interface/Controls/ScalingViewport.cs, OpenDreamClient/Interface/DMF/DMFParser.cs, OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs, OpenDreamClient/Interface/Descriptors/InterfaceDescriptor.cs, OpenDreamClient/Interface/Descriptors/MacroDescriptors.cs, OpenDreamClient/Interface/Descriptors/MenuDescriptors.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/DreamStylesheet.cs, OpenDreamClient/Interface/DummyDreamInterfaceManager.cs, OpenDreamClient/Interface/InterfaceElement.cs, OpenDreamClient/Interface/InterfaceMacro.cs, OpenDreamClient/Interface/InterfaceMenu.cs, OpenDreamClient/Interface/Prompts/AlertWindow.cs, OpenDreamClient/Interface/Prompts/InputWindow.cs, OpenDreamClient/Interface/Prompts/MessagePrompt.cs, OpenDreamClient/Interface/Prompts/NumberPrompt.cs, OpenDreamClient/Interface/Prompts/PromptWindow.cs
We've been treating ID and name as the same thing which isn't correct. These are now separate and uses of `Name` have been switched to `Id` where I think is appropriate.
This fixes attempts to reparent existing macros with names different from their id. That and a change to wincloning macro sets fixes non-hotkey mode in modern Paradise.
I also made every file in the `Interface/` folder use file-scoped namespaces.
=> Split ID and name attributes in skin controls

Content.Tests/DMProject/Tests/Tree/upward_search_path2.dm, DMCompiler/DM/DMObjectTree.cs
`DMObjectTree.UpwardSearch()` was not returning the correct value if you were searching for a type instead of a proc.
=> Fix upward path searches for types

OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Objects/Types/DreamObjectWorld.cs, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeWorld.cs
I tried making this use RT's `IBaseServer.Restart()` method but that led to a lot of exceptions and a broken server. I checked the implementation and was met by this:
```cs
// FIXME: This explodes very violently.
Cleanup();
Start(Options, _logHandlerFactory);
```
So I'm just gonna have this shutdown for now.
=> Make `/world.Reboot()` shutdown the server

OpenDreamRuntime/DreamConnection.cs
Setting the mob or key in `/mob/Logout()` would lead to calling `/mob/Logout()` again.
=> Fix potential infinite recursion in `/Logout()`

OpenDreamClient/DreamClientSystem.cs, OpenDreamClient/EntryPoint.cs, OpenDreamClient/Rendering/ClientScreenOverlaySystem.cs, OpenDreamClient/Rendering/DreamIcon.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamClient/Resources/ResourceTypes/DMIResource.cs, OpenDreamShared/Dream/ViewAlgorithm.cs, OpenDreamShared/Resources/DMIParser.cs
Appearance was nullable but wasn't marked as such. It causes a lot of exceptions when appearances haven't loaded yet.
=> Fix nullability of a bunch of DreamIcon stuff

OpenDreamClient/Interface/Controls/ControlInfo.cs, OpenDreamClient/Interface/Controls/VerbPanelGrid.cs
Verb panels now dynamically adjust the amount of columns depending on the available size. The size of the buttons will stretch horizontally, and they can now be scrolled.
(every proc turned into a verb for demonstration)
=> Improve verb panel layout

OpenDreamClient/Rendering/DreamViewOverlay.cs
This has apparently been broken since #1369
Atoms with `render_target` set weren't having their atom rendered.
=> Fix rendering the original atom of render targets

DMCompiler/DM/Visitors/DMObjectBuilder.cs
Moves `parent_type` handling from step 6 to step 1. It's now treated as part of the object definition rather than a var override, so every step from there on out is aware of the object's correct parent.
=> Move `parent_type` handling to the first step in DMObjectBuilder

OpenDreamRuntime/Procs/Native/DreamProcNativeWorld.cs
In Paradise this was causing `/proc/load_admins()` to stop early which broke admin assignment.
=> Make unsupported uses of `world.GetConfig()`/`world.SetConfig()` warnings instead of errors

OpenDreamRuntime/Objects/Types/DreamObjectWorld.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamShared/OpenDreamCVars.cs
Implements reading and writing to world.params.
To add them at ServerLaunch use `--cvar opendream.world_params="a=1;b=2;c=3"`
Closes https://github.com/OpenDreamProject/OpenDream/issues/1360
=> Implement world.params

OpenDreamClient/Rendering/DreamViewOverlay.cs, Resources/Shaders/blendoverlay.swsl, Resources/Shaders/drop_shadow.swsl
Title! Working on this PR was one hell of a rabbit hole, starting off as a simple investigation of the blending function used in `blendoverlay.swsl`, and eventually escalating towards viciously tearing apart both OD and Byond in Renderdoc to figure out what's going on, and to figure out how to get a bit closer to parity with our relatively limited knowledge of OpenGL (And we've gotta say: DX9 *really* spoiled us). We're genuinely surprised this ultimately ended up being a small PR!
The bulk of this PR's work is making the `blendoverlay.swsl` simply use the default blend mode, as the `normal` blend mode causes particularly funky behavior with alpha blending, most notable being that the transparency of an object ends up bleeding through to whatever it's layered over.
However, that on it's …
=> Blending parity - brings OD's normal alpha blending a lot closer to Byond's

DMCompiler/DM/DMProc.cs, OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Procs/AsyncNativeProc.cs, OpenDreamRuntime/Procs/NativeProc.cs, OpenDreamShared/Json/DreamProcJson.cs
This method would create a string DreamValue with a null if the field didn't have a value.
I added a debug assert in the string constructor so this can be caught closer to the source in the future.
=> Fix invalid DreamValues in `DreamProc.GetField()`

OpenDreamRuntime/DreamManager.cs
Doing `locate("\[abc]")` is no different from doing `locate("abc")`
=> Fix `locate()` with a tag surrounded by brackets

OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamClient/Rendering/DreamPlane.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamRuntime/Objects/Types/DreamObjectFilter.cs, OpenDreamShared/Dream/ColorMatrix.cs, OpenDreamShared/Dream/DreamFilter.cs, Resources/Shaders/alpha.swsl
* Fix plane masters with a `render_target` value (actually render to the render target instead of ignoring it)
* Ignore positional offsets when rendering plane masters with a `render_target`
* Fix `/dm_filter` var setting
* Reset the texture shader parameters each frame since different render targets can be used between frames
* Make the alpha filter use the average of RGB multiplied by A instead of just A
* Mix an overlay's color with their parent if it doesn't have `RESET_COLOR`
Achieves working emissives in Paradise, and fixes rendering bugs in others
=> Several rendering fixes

OpenDreamClient/Interface/Controls/ControlChild.cs, OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs, OpenDreamClient/Interface/Descriptors/InterfaceDescriptor.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs
Squashes some errors in DMF parsing for goonstation.
Major stumbling block remains `on-show` not being implemented.
Things fixed:
- bad ID in Left/Right on a Splitter would cause a dict key miss, now just prints an error.
- Accidentally using name instead of ID as a window key in `WithVisible()` was causing wincloned windows to duplicate ID
- Elements with empty IDs now get a random GUID instead. Not a perfect solution, but the chance of collision is miniscule.
=> Misc DMF Parsing Fixes

OpenDreamRuntime/Objects/Types/DreamObjectAtom.cs
Entities didn't have their name and description set properly because these properties were used before they were initialized.
=> Move atom name and desc property init earlier

OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamClient/Rendering/DMISpriteComponent.cs, OpenDreamClient/Rendering/DreamIcon.cs
Fix the AABBs of some entities extending all the way to `(0, 0)`. This was the cause of airlocks/mobs/others appearing in the right click menu when they shouldn't.
=> Fix icon AABB calculation

DMCompiler/DMStandard/UnsortedAdditions.dm, DMCompiler/DMStandard/_Standard.dm, OpenDream.sln.DotSettings, OpenDreamClient/Interface/Controls/ControlChild.cs, OpenDreamClient/Interface/Controls/InterfaceControl.cs, OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/InterfaceElement.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/DreamManager.Connections.cs, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamShared/Network/Messages/MsgWinGet.cs
Implements `winget()`. Currently only supports the `size` and `is-disabled` properties.
I didn't use RT's serialization manager to read the property because I want to move UI away from using it. It's not great for setting singular properties and reading properties that are constantly changing like `size` and `splitter`.
Also implemented the CHILD control's `splitter` property. This PR is enough to get the "Fit Viewport" verb working.
Fixes #192
=> Minimal `winget()` implementation

OpenDreamShared/Dream/ScreenLocation.cs
Important for preventing `TOP:-70,0` from treating the `TOP:` as a secondary control
=> Add some keywords to ScreenLocation's keywords list

OpenDreamClient/Rendering/DreamViewOverlay.cs, TestGame/renderer_tests.dm
Previously, unless you were using keep together or RESET_ALPHA, the overlay's alpha value was completely ignored. Now it will multiply the parent's alpha value by the provided alpha value. This is the behaviour that byond exhibits, as when I place an object sandwhiched between another object and its overlay, decreasing the alpha of the behind object will decrease the alpha of the overlay.
I noticed this was an issue when sent a screenshot of kilostation, as our decals on Beestation use an alpha of 50 which is set at the overlay object level rather than the sprite level.
**BYOND:**
<details>
</details>
**OpenDream:**
Without the alpha variable set:
WIth the alpha variable set (Alpha of 50 was used):
Without the overlay alpha variable, but with the parent alpha:
With the overlay alpha and …
=> Alpha applying to overlays properly

OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/Objects/Types/DreamList.cs
`world.contents` should be in the order `Mobs + Movables + Areas + Turfs`
This fixes map init in BeeStation
=> Fix `world.contents` order

OpenDream.sln.DotSettings, OpenDreamClient/Interface/Controls/ControlBrowser.cs, OpenDreamClient/Interface/Controls/ControlChild.cs, OpenDreamClient/Interface/Controls/ControlWindow.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs
Several interface fixes that get modern tgui-chat/tgui-panel working
* Try/Catch any exceptions in BeforeBrowseHandler because exceptions there freeze CEF
* Using `id` in a global winset will target a specific element
* Having only 1 pane in a CHILD control will have that pane take up the whole space (though the splitter can still be grabbed, this needs to be disabled later)
* Only care about visible controls when determining the available space for a control with size `0x0`
New state of [auxmos-removed BeeStation](https://github.com/itsmeowForks/BeeStation-Hornet/tree/db2b4b439a98af9b56cb75c9b8cce8f8493f2a7f):
=> Several interface fixes

OpenDreamRuntime/Objects/Types/DreamList.cs
Fixes #1363
Implementing `ContainsValue` for `ClientScreenList` was necessary because the base implementation from `DreamList` searches the `_values` field, while `ClientScreenList` doesn't use that at all in favor of `_screenObjects`.
=> Fixed screen.Remove() - Fixes #1363

OpenDreamRuntime/Objects/DreamIcon.cs, OpenDreamShared/Resources/DMIParser.cs
Using an invalid dir/frame should just not insert an icon state
=> Handle invalid dir/frame index in `/icon.Insert()`

DMCompiler/DMStandard/Types/Atoms/_Atom.dm, DMCompiler/DMStandard/Types/Client.dm, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Objects/DreamObjectDefinition.cs, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Objects/Types/DreamList.cs, OpenDreamRuntime/Objects/Types/DreamObjectAtom.cs, OpenDreamRuntime/Objects/Types/DreamObjectClient.cs, OpenDreamShared/Dream/IconAppearance.cs
An implementation of vis_contents that does not much more than get them rendering.
vis_flags is currently ignored and clicking is incorrectly routed to the parent atom.
Gets BeeStation's airlocks rendering (though there's a bug with the alpha filter keeping them from masking when open):
Resolves #296
=> Basic implementation of `atom.vis_contents`

OpenDreamRuntime/AtomManager.cs, OpenDreamShared/Dream/AtomDirection.cs
`atom.dir`'s maximum value is 255. Also, setting it to 0 or below/a non-number will ignore the assign entirely, keeping the current value.
=> Handle out-of-range `atom.dir` sets

OpenDreamRuntime/Objects/Types/DreamObjectRegex.cs
These weren't being replaced correctly if an escape code came somewhere before
=> Fix `\l` and `\L` parsing in regex

OpenDreamRuntime/Objects/Types/DreamObjectRegex.cs
There would be an out-of-bounds exception if there was an unfinished escape code at the end of a regex. That's still an invalid regex, so this just gives it a nicer error message.
=> Handle possible out-of-bounds in regex parsing

OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/Objects/Types/DreamObjectAtom.cs
The behavior for this var in atoms and images is the same, so I moved the setter and getter to `SetAppearanceVar()` and `GetAppearanceVar()`
Makes the var work on images and appearance values.
=> Move `atom.transform` handling to the appearance var helpers

Content.Tests/DMProject/Tests/Expression/Constants/resource.dm, DMCompiler/DM/Expressions/Constant.cs
Compile-time resources always use forward slashes in their paths
```dm
world.log << "[file("a/b.dmi")]"
world.log << "[file("a\\b.dmi")]"
world.log << "['a/b.dmi']"
world.log << "['a\\b.dmi']"
```
Outputs:
```
a/b.dmi
a\b.dmi
a/b.dmi
a/b.dmi
```
=> Always use forward slashes in compile-time resources

DMCompiler/DM/Visitors/DMVisitorExpression.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm, OpenDreamShared/Compiler/CompilerError.cs
I didn't have time to revisit static typing so I did this instead.
Lints for `client.foo` and suggests `client?.foo`.
I consider this a stylistic pragma and a disabled-by-default pragma because it'll throw a lot of false positives since SS13 will nullcheck clients in various ways like `if(client && client.foo)` (even though `if(client?.foo)` is faster).
But with how often I've been seeing null client bugs in SS13 lately, I still consider this a useful lint.
=> Adds a pragma for unsafe client accesses

Content.Tests/DMProject/Tests/List/ListFind.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeList.cs
They are treated as their default values.
=> Handle non-number `Start` and `End` args in `list.Find()`

OpenDreamRuntime/Objects/Types/DreamList.cs, OpenDreamRuntime/Rendering/ServerAppearanceSystem.cs
Avoid adding an appearance to the appearance list when trying to remove a nonexistent overlay from an overlays/underlays list. This cuts down on the amount of expensive operations done when dealing with appearances.
=> Don't register an appearance when removing an overlay

OpenDreamRuntime/Objects/Types/DreamList.cs
This doubles the internal array's size instead of setting the size exactly. This means doing `list.len++` repeatedly does not lead to lots of unnecessary array allocations and copies.
Cuts tg's total init allocations in half.
Before:
After:
=> Use `EnsureCapacity()` instead of `Capacity` when resizing lists

OpenDreamRuntime/Objects/DreamIcon.cs, OpenDreamShared/Resources/DMIParser.cs
This was allocating huge amounts on tg
Before:
After:
Spending 20 seconds on this is still crazy, this will need changing later.
=> Remove allocations in `DMIParser.GetExportedDirectionCount()`

OpenDreamClient/Input/MouseInputSystem.cs, OpenDreamClient/Rendering/DreamPlane.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs
Every `RenderInRenderTarget()` call flips the resulting texture. This means to show it right-side-up we have to flip it again. The renderer would try to be smart and avoid flipping when the amount of `RenderInRenderTarget()` uses were even, though there were many difficult to fix mistakes resulting from that. I instead made it flip the texture on every call so the resulting texture is always right-side-up.
I also made planes with render targets apply their color var after the whole plane has been rendered.
With this and #1435, tgstation now renders pretty well.
=> Fix renderer flipping bugs

DMCompiler/Compiler/DM/DMAST.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/DMObjectTree.cs, DMCompiler/DM/Expressions/Binary.cs, DMCompiler/DM/Expressions/Builtins.cs, DMCompiler/DM/Visitors/DMObjectBuilder.cs, DMCompiler/DM/Visitors/DMVisitorExpression.cs
Two important changes to global var init order:
1. All global vars (except lists) are initialized in the order they appear in the code, except globals inside procs are all lumped together and start at the appearance of the first one.
2. Proc global vars that reference other global vars are moved to the end of init. I achieved this by making global vars not available on the first pass, which makes them handled by the late-var-def system.
=> Fix global init order

Content.Tests/DMProject/Tests/Text/StringInterpolation9.dm, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
```dm
world.log << "\a ["thing"]"
world.log << "\a ["Thing"]"
```
Outputs:
```
[INFO] world.log: a thing
[INFO] world.log: Thing
```
=> Fix `\a` on strings

DMCompiler/Compiler/DM/DMParser.cs
`sleep 50` is the same as `sleep(50)`
=> Support sleep calls without parentheses

OpenDreamRuntime/Objects/Types/DreamList.cs
C#'s list `Contains()` method usies a `GenericEqualityComparer` which allocates. This removes ~600MB total allocations during BeeStation init bringing it down to 7.3GB.
=> Use a for loop in `DreamList.ContainsValue()`

OpenDreamClient/Input/MouseInputSystem.cs, OpenDreamClient/Interface/Controls/ScalingViewport.cs, OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamClient/Rendering/ClientImagesSystem.cs, OpenDreamClient/Rendering/ClientScreenOverlaySystem.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/Input/MouseInputSystem.cs, OpenDreamRuntime/Objects/Types/DreamList.cs, OpenDreamRuntime/Rendering/ServerAppearanceSystem.cs, OpenDreamRuntime/Rendering/ServerClientImagesSystem.cs, OpenDreamRuntime/Rendering/ServerScreenOverlaySystem.cs, OpenDreamShared/Dream/IconAppearance.cs, OpenDreamShared/Input/SharedMouseInputSystem.cs, OpenDreamShared/Rendering/SharedAppearanceSystem.cs, OpenDreamShared/Rendering/SharedClientImagesSystem.cs, OpenDreamShared/Rendering/SharedScreenOverlaySystem.cs
This handles the server-client EntityUid separation. Basically just needed to change everything in OpenDreamShared.
The one thing I didn't change but it seems to work fine is `DreamMobSightSystem` - the `SubscribeLocalEvent` complains if I change the unused `EntityUid` argument to a `NetEntity`.
This is right before v159 where some render handle stuff got moved and I got bored of fixing stuff. There's also the removal of ComponentReference in v160.
This upgrades us to last week though, which I see as a win.
TestGame runs fine, ditto for Paradise.
=> Upgrade RobustToolbox to v158

OpenDreamRuntime/Input/DreamCommandSystem.cs
Change the list of executing repeating commands to a hash set. This prevents unremovable duplicates.
=> Fix stuck repeating commands

DMCompiler/DMStandard/Types/Atoms/_Atom.dm, OpenDreamRuntime/Objects/DreamObjectTree.cs
Descendants of `/atom` have their name var set to their type name (with spaces instead of underscores) by default.
=> Set default atom names

DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/DM/Expressions/Constant.cs, DMCompiler/DMCompiler.cs
=> Add support for `#define FILE_DIR`

OpenDreamRuntime/Objects/DreamObjectTree.cs
Prevents nested lists from being parsed as key/value pairs.
=> Fix compilation of nested lists in DMMs

Content.Tests/DMProject/Tests/Preprocessor/Pragma/warning_quote.dm, DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs, OpenDreamShared/Compiler/Lexer.cs
`#warn` directives shouldn't try to process the tokens. Fixes #1439 and adds test
=> fix #warn choking on apostrophe

.github/workflows/compiler-test.yml, DMCompiler/DMCompiler.csproj
Move DMCompiler's build path to be beside the server and client.
=> Move DMCompiler's build output path

DMCompiler/DMCompiler.cs, DMCompiler/Program.cs, OpenDreamClient/States/Connecting/ConnectingControl.xaml.cs, OpenDreamClient/States/Connecting/ConnectingState.cs, OpenDreamClient/States/DreamUserInterfaceStateManager.cs, OpenDreamClient/States/InGameState.cs, OpenDreamClient/States/MainMenu/MainMenuControl.xaml, OpenDreamClient/States/MainMenu/MainMenuControl.xaml.cs, OpenDreamClient/States/MainMenu/MainMenuState.cs, OpenDreamServer/Program.cs
When the client is compiled in Debug:
And the compiler:
`Warning OD0000 at <internal>: This compiler was compiled in the Debug .NET configuration. This will impact compile speed.`
Nothing for the server because there's nowhere to obviously place it, and the people this targets likely aren't compiling the server in Debug and client in Release.
=> Add a performance warning when OpenDream is compiled in Debug

OpenDreamRuntime/Procs/Native/DreamProcNativeWorld.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs
=> Make `world.Export()`'s returned CONTENT a resource value

OpenDreamRuntime/Procs/DllHelper.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamRuntime/Resources/DreamResource.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs
Combining `RootPath` with every file operation was necessary before we set our CWD to the game's directory, but not anymore. This fixes problems that arise when you give OpenDreamServer a relative path to the json.
=> Fix incorrect usages of `RootPath`

OpenDreamRuntime/Procs/Native/DreamProcNativeHelpers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Closes #1456 
Implements null arg support and non-default `world.view` size support.
=> Improved `range` support in `view()` procs

OpenDreamClient/Interface/InterfaceElement.cs
Prevents bad values in one element/winset from breaking everything else
=> Catch exceptions in `PopulateElementDescriptor()`

OpenDreamClient/States/MainMenu/MainMenuControl.xaml, OpenDreamClient/States/MainMenu/MainMenuControl.xaml.cs, OpenDreamServer/Program.cs
The removal of `server_config.toml` in #1502 ended up changing the default server port from 25566 to 1212. I can't find another way to change the default port, and re-adding the file introduces issues with `dotnet publish` so I'm taking the path of least resistance and changing the default port on the client to 1212.
=> Set default port to 1212

global.json
This fixes builds failing when .NET 8 is installed.
=> Create global.json to lock .NET version

Content.IntegrationTests/Content.IntegrationTests.csproj, Content.Tests/Content.Tests.csproj, OpenDreamClient/OpenDreamClient.csproj, OpenDreamServer/OpenDreamServer.csproj, OpenDreamShared/OpenDreamShared.csproj
`Robust.Properties.targets` already imports `Robust.DefineConstants.targets` and `Robust.Analyzers.targets`
=> Remove duplicate csproj imports

OpenDreamClient/Interface/Controls/ControlBrowser.cs
Should make `isByond` pass in TGUI, but I haven't tested it.
=> Set hostname to localhost

OpenDreamClient/Input/MouseInputSystem.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs
Properly resets the interface before attempting to load a new one. This fixes an error that would leave the client in a broken state when reconnecting without restarting the client.
=> Fix an error on the client upon reconnect

DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/Compiler/DM/DMParserHelper.cs, DMCompiler/Compiler/DMM/DMMParser.cs, DMCompiler/Compiler/DMPreprocessor/DMMacro.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs, OpenDream.sln.DotSettings
Lines ending with just `\r` are treated as newlines.
Multiple consecutive `\r` characters are also handled now.
Also some general cleanup in the preprocessor, especially in the lexer which no longer inherits `TextLexer`
Fixes #1492
=> Handle lone-carriage-return line endings

.github/workflows/test-tgs.yml
Run a test in TGS tailored to test exclusively OpenDream functionality against the trigger commit
=> Setup tgstation-server CI

OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/Objects/Types/DreamObjectAtom.cs, OpenDreamRuntime/Objects/Types/DreamObjectImage.cs
Gives a copy of the appearance. Also fixes #1090 by finishing the last 2 check boxes.
There were a ton of errors regarding this in tg init
=> Fix getting an appearance's `appearance` var

OpenDreamRuntime/Procs/DebugAdapter/Protocol/ProtocolMessage.cs, OpenDreamRuntime/Procs/DebugAdapter/Protocol/Request.cs
#1541 removed an empty constructor that Rider marked as unused but turned out to be necessary for the JSON deserializer. Similar for a `public` -> `protected` constructor.
=> Fix the debugger

OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/EntryPoint.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs
Adds support for temporary savefiles (fixes #1449)
Allows multiple savefile datums pointing at the same file to remain synchronised
Reduces memory usage by reducing duplication of savefiles and closing resources when they're no longer in use
Moves savefile flushing to be between ticks, except when `flush()` is called manually.
=> Add support for tmp savefiles, fix multiple handles for savefiles, clean up

OpenDreamPackageTool/ServerPackaging.cs, OpenDreamRuntime/OpenDreamRuntime.csproj
Contains fixes for packet splintering, ValueTasks, records/structs and other goodness.
=> Update `Byond.TopicSender` to v8.0.1

Content.Tests/DMProject/Tests/Text/LongString.dm, DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
#1555 broke instances of delimiters appearing in long strings, they were being excluded from the final string.
=> Fix `"` appearing in long strings

Content.Tests/RuntimeTests.cs, DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/DMCompiler.cs
We only need to make sure that all opcodes are unique when we prepare a deployment and not on a compiler run. This also tells us that the ODRT is valid too when deploying, as we don't have to rely on the compiler telling us that it is.
=> Move duplicate opcode check to a unit test

OpenDreamRuntime/Rendering/ServerAppearanceSystem.cs
The PVS thread has to get atom appearances when creating component states, so this needs to be thread-safe
=> Make ServerAppearanceSystem thread-safe

Content.Tests/DMProject/Tests/Regex/regex_defer.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs
infinite loop on goon squashed
=> Fix `next` getting set on `/regex.Replace()`

OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamClient/Rendering/ClientImagesSystem.cs, OpenDreamClient/Rendering/DMISpriteComponent.cs, OpenDreamClient/Rendering/DMISpriteSystem.cs, OpenDreamClient/Rendering/DreamIcon.cs, OpenDreamShared/Resources/DMIParser.cs
Moved `UpdateAnimation()` from using `DateTime.Now` to `IGameTiming.CurTime`. This provides a decent speed boost since getting `DateTime.Now` thousands of times a frame is apparently slow.
=> Optimize `DreamIcon.UpdateAnimation()`

OpenDream.sln.DotSettings, OpenDreamClient/Rendering/DreamPlane.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs
There's no need to duplicate a new shader when the values end up with the default rendering behavior. This about halves the allocations per frame when observing on Paradise (~2MB per frame to ~1MB per frame).
=> Avoid allocating shaders when values are default

OpenDreamPackageTool/ServerPackaging.cs
It was "Zip" (capitalized) instead of "zip" so the server couldn't find it on a case-sensitive file system.
=> Fix Content.Client.zip name from packaging

OpenDreamRuntime/EntryPoint.cs, OpenDreamRuntime/ServerContentIoC.cs, OpenDreamRuntime/ServerInfoManager.cs, OpenDreamShared/OpenDreamCVars.cs
Partially ports https://github.com/space-wizards/space-station-14/pull/12781
Only ports the cvars that actually get displayed in the launcher, and didn't port any SS14-specific changes.
=> Ports infolinks

OpenDreamRuntime/Objects/DreamIcon.cs
BYOND seems to just copy the source RGB if the destination is 0 alpha, rather than doing multiplication by the source alpha.
```dm
/world
fps = 25
icon_size = 32
view = 1
/mob/verb/Y()
set name = "Y"
var/atom/movable/Z = new (loc)
var/icon/A = icon('transparent.dmi', "nothing")
A.Blend(icon('transparent.dmi', "thing"), ICON_OVERLAY)
Z.icon = A
```
BYOND result:
OpenDream result (old) - see how it's desaturated/darker?
OpenDream result (new) - no longer desaturated.
=> Fix overlay blending multiplying for transparent alpha

OpenDreamClient/Rendering/DreamPlane.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs
Planes with no atoms but a plane master were being thrown out and recreated every frame, render targets and all. This ~~fixes~~ heavily reduces the constant stuttering on the client.
=> Don't release planes with a plane master

DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm, OpenDreamShared/Compiler/CompilerError.cs
When assigning a value in an `if()` or `switch()` statement, the compiler will emit an `AssignmentInConditional` warning.
Closes https://github.com/OpenDreamProject/OpenDream/issues/576
=> Adds a warning when assigning a value in a conditional

OpenDreamClient/Interface/Controls/ControlBrowser.cs, OpenDreamClient/Interface/Controls/ControlInfo.cs, OpenDreamClient/Interface/DMF/DMFParser.cs, OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs
More DMF fixes, increase goon's interface parity
=> `on-show` and `on-hide` for INFO and BROWSER plus handle winset `attribute=;`

OpenDreamClient/Rendering/DreamViewOverlay.cs
Four bytes per sprite were being allocated every frame to get the bytes in a hash code. I replaced a `BitConverter.GetBytes(int)` call with bit operations to get rid of those allocations.
=> Reduce allocations per frame

DMCompiler/Compiler/DM/DMAST.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/DMExpression.cs, DMCompiler/DM/Expressions/Binary.cs, DMCompiler/DM/Expressions/Builtins.cs, DMCompiler/DM/Expressions/Dereference.cs, DMCompiler/DM/Expressions/Procs.cs, DMCompiler/DM/Expressions/Ternary.cs, DMCompiler/DM/Visitors/DMASTSimplifier.cs, DMCompiler/DM/Visitors/DMExpressionBuilder.cs
It's just like rust enums no wayyyy
This PR tackles mainly nullability by refactoring the existing Dereference operation to be safer with the help of the type system. 
The previous implementation used a struct called `Operation`, which held an enum value for what kind of operation the struct described as well as metadata about the operation. This resulted in a struct where pretty much every additional metadata was optional and had to be asserted at the time of checking `Kind`, which wasn't very elegant.
I refactored dereference operations by binding the metadata into types with one shared superclass called `Operation`. 
The subclasses are there to describe all kinds of different metadata that they need. To get the metadata, you can use type patterns to extract the data. This completely …
=> Refactor dereference operations into tagged unions

OpenDreamClient/EntryPoint.cs
Set the `display.windowmode` CVar to 0 during pre-init.
=> Disable fullscreen on the client

OpenDreamRuntime/Procs/ProcScheduler.Delays.cs
Was trying to figure out why goon was slow, came across non-optimal code. Was compelled.
Switches the `spawn()` and `sleep()` task scheduler to use a priorityqueue instead of unsorted adds to a list.
This should change the time complexity as: best/avg/worst
`spawn()`/`sleep()` becomes `O(log2(n)`)/`O(log2(n))`/`O(log2(n))` from `O(1)`/`O(1)`/`O(1)`
tick processing becomes `O(1)`/`O((n_T)log2(n))`/`O(nlog2(n))` from `O(n)`/`O(n)`/`O(n)` where `n_T` is the number of tasks that would resume this tick, and `n` is just the number of tasks queued. 
Best case is `O(1)` because we always gotta check the first task unless the task list is empty, but we gotta check that too so O(1), and PQ.Peek() is `O(1)`. Dequeue is `O(log2(n))`
=> Optimise ProcScheduler.Delays

OpenDreamClient/Rendering/AtomGlideSystem.cs, OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamShared/Dream/IconAppearance.cs
If `glide_size` is changed mid-movement the client will now use that updated speed. I also changed the GlideSize field on appearances from a byte to a float, so non-integer sizes work.
In Paradise, this fixes gliding for anything with a movespeed other than 1. This includes slower mobs, walking, and crawling.
=> Handle `glide_size` being updated mid-glide

OpenDreamClient/Rendering/DMISpriteComponent.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs
This had an `IEntityManager.TryGetComponent<TransformComponent>()` call, which is slow for how often this gets called. Now the `TransformComponent` is an argument, and the calling code uses an EntityQuery which speeds it up.
=> Optimize `DMISpriteComponent.IsVisible()`

OpenDreamRuntime/Procs/DreamEnumerators.cs
Was throwing on `for(var/client/C)` when no clients were connected because accessing `.Current` when the enumerator is finished throws.
=> Tiny fix to enumerators

OpenDreamClient/DreamClientSystem.cs, OpenDreamClient/Rendering/DreamPlane.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs
Some renderer optimizations with a focus on memory allocation rate.
1. Split `DrawIconAction()` (now `DrawIcon()`) into several methods (`ProcessKeepTogether()`, `DrawIconFast()`, and `DrawIconSlow()`) so it no longer holds any lambdas. The C# compiler was allocating the lambdas' closures even though the closures weren't used in a majority of cases. Now they're only allocated when necessary.
2. `DrawIcon()` now draws the icon directly instead of returning two actions for drawing the icon and its mouse map. This allows for less lambda usage.
3. Deprecated RT component methods were replaced with their system equivalent.
Before:
After:
Large majority of allocations now are in shader setup, `GetBlendAndColorShader()`
=> Halve the renderer's allocation rate

OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/Procs/DMProc.cs
Fixes #1261
When using named arguments in `image()` or `new /image()`, using a string in the second positional argument will now place an implicit `null` in between the first and second arg. This is what BYOND does:
BYOND does this even when there are no named arguments being used. For the sake of performance I'm just ignoring that here in the hopes no one depends on such niche behavior. This does mean keeping the argument-skipping behavior in DreamObjectImage's initializer.
=> Fix edge-case positional/named argument handling in `image()`

Content.Tests/DMProject/Tests/Special Procs/nameof/nameof.dm, DMCompiler/DM/DMExpression.cs, DMCompiler/DM/DMProc.cs, DMCompiler/DM/Expressions/Builtins.cs, DMCompiler/DM/Expressions/Constant.cs, DMCompiler/DM/Expressions/Dereference.cs, DMCompiler/DM/Expressions/LValue.cs, DMCompiler/DM/Visitors/DMExpressionBuilder.cs
Throwing is bad. Unwinding isn't healthy for tracking code errors. I refactored `GetNameof()` to return an optional string, which gets checked in the actual `Nameof` expression. There we can emit the error. 
The arguments for `GetNameof` felt unnecessary since `dmObject` was unused, `proc` was used only once in `Local`, so I cut the arguments from the method. Let me know if I should keep it.
`nameof()` is also usable in constant contexts (eg. switch cases), so I added an override for `TryAsConstant()`.
Also a few l-values didn't have any nameof support, so I added it in this PR.
=> Tweak `Nameof` slightly, add `GetNameof()` support to more expressions

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Fixes #1604 
Also handles `roll(null)`
=> Fix `roll(sides)`

OpenDreamShared/Dream/VerbSystem.cs
`.` prefix is the same as `hidden = true`
=> Fix hidden verb logic

OpenDreamRuntime/Objects/DreamIcon.cs
Default value of 0,0 when the icon passed to `new /image()` is null throws an error.
=> Fix min icon size in GenerateDMI()

.github/workflows/pr-labeler.yml
if it's the on push master event, the ref is always master. We don't want to check size label on push to master, so we force it to only happen on pull request events (ie, creation and commits), where the branch name is set properly
=> Fix PR labeler

.github/boring-cyborg.yml
The compiler tag used incorrect paths
=> Fix automatic `Compiler` label

OpenDreamClient/Interface/Controls/ControlChild.cs, OpenDreamClient/Interface/Controls/ControlWindow.cs, OpenDreamClient/Interface/Controls/InterfaceControl.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs
also adds a couple properties goon uses. There are literally a ton more to add though.
=> Parse multiple properties in a single `winget()`

DMCompiler/DM/DMProc.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs, OpenDream.sln.DotSettings
=> Update an old ForcedError

OpenDreamClient/ClientVerbSystem.cs
It would error when your eye didn't have a `MobSightComponent`
=> Fix an error in the client's verb system

Content.Tests/DMProject/Tests/Statements/EmptyBlock.dm, Content.Tests/DMProject/Tests/Statements/EmptyBlockSuppressed.dm, DMCompiler/Compiler/DM/DMAST.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Visitors/DMASTSimplifier.cs, DMCompiler/DM/Visitors/DMProcBuilder.cs
Just a lone semicolon that represents a statement with nothing in it. Allows for suppressing EmptyBlock emissions.
```dm
/proc/main()
if (TRUE) // Has no body, considered an empty block.
```
```dm
/proc/main()
if (TRUE)
; // A null statement. Not considered an empty block.
```
=> Add "null statements" to the compiler

OpenDreamRuntime/EntryPoint.cs
Unfortunately we can't use arbitrary images, so the main icon will have to be left to server owners to set after they get it uploaded to Discord through [here](https://github.com/space-wizards/asset-dump/tree/master/discord-app-assets).
=> Set the default secondary icon in Discord Rich Presence

DMCompiler/DM/Builders/DMProcBuilder.cs, OpenDreamClient/ClientVerbSystem.cs, OpenDreamRuntime/Objects/Types/DreamObjectMovable.cs, OpenDreamRuntime/ServerVerbSystem.cs
Makes a verb accessible only if the object is inside your mob's contents (non-recursive)
=> Implement `set src = usr.contents`

OpenDreamRuntime/Objects/Types/DreamObjectImage.cs
The /image initializer wasn't copying its default appearance. This meant modifications to one /image would affect every other /image too.
=> Fix /image objects sharing appearances

OpenDreamClient/Interface/Controls/ControlBrowser.cs, OpenDreamClient/Interface/Controls/ControlChild.cs, OpenDreamClient/Interface/Controls/ControlInfo.cs, OpenDreamClient/Interface/Controls/ControlMap.cs, OpenDreamClient/Interface/Controls/ControlWindow.cs
- Don't attempt to execute empty `on-show`, `on-hide`, `on-close`
- Fix ControlChild child count check
=> Some interface fixes

OpenDreamClient/Interface/Controls/ControlBrowser.cs, OpenDreamClient/Interface/Controls/ControlTab.cs, OpenDreamClient/Interface/Controls/ControlWindow.cs, OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs
Adds some minimal support for the TAB control
Shown in the ability to select between Desktop/Laptop in [Console](https://github.com/Nadrew/console):
=> Add support for the TAB control

DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
This would have given an error on line 2 rather than 4:
```dm
var/a = "A\
B\
C"
#error Error here
```
That's fixed now.
=> Fix incorrect line counter when lexing line-spliced strings

DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
An extra character was being skipped after line splices inside strings
=> Fix a character skip after string line splices

DMCompiler/Compiler/DM/DMParser.cs
BYOND v515 added support for overloading the stringify operator:
```dm
/datum/proc/operator""()
return "foo" // "[new /datum]" will give you "foo"
```
I added support for this on the compiler, though it won't ever get executed.
=> Add support for defining stringify overloads

DMCompiler/DMStandard/Types/Sound.dm
A new sound property added in v515. Not implemented, but won't error if used.
=> Define `/sound.pitch`

OpenDreamRuntime/Procs/DMProc.cs
I saw that #1554 fixed a bug with the PopReference opcode being used where it shouldn't have been (the reference had already been popped from the stack). An assert in `PopDrop()` would have made this easier to catch.
=> Add a debug assert in `DMProcState.PopDrop()`

OpenDreamClient/Interface/Controls/ControlMap.cs, OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs
Setting a MAP control's `icon-size` property now sets the size given to each tile. This makes these settings work:
32x32:
128x128:
=> Implement MAP's `icon-size` property

Content.Tests/DMProject/Tests/Builtins/LocateIn.dm, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
=> `locate() in` plus test

OpenDreamClient/Interface/Controls/ControlBrowser.cs
Fixes the `&&0&0` thing in goon.
Basically, you can call `output(list2params(list_of_things), "clientbrowserelement:javafunction")` which will call `javafunction(list, of, things)` on the clientside. We weren't handling that, and only handling the case where there was single param.
=> Fix clientside ouptut parsing of list2params

.github/workflows/compiler-test.yml, DMCompiler/DMCompiler.cs
I removed modified /tg/station (which hasn't been relevant for a while now) and replaced it with a fixed commit of /tg/station and Goonstation. This should help ensure we don't break anything in those codebases that currently works.
=> Update the compiler test workflow's repositories

Content.Tests/DMProject/Tests/Builtins/__IMPLIED_TYPE__.dm, Content.Tests/DMProject/Tests/Dereference/implied_initial.dm, Content.Tests/DMProject/Tests/Stdlib/istype_implied.dm, DMCompiler/DM/Builders/DMExpressionBuilder.cs, DMCompiler/DM/Expressions/Builtins.cs, OpenDreamRuntime/Procs/DMProc.cs
Implements `__IMPLIED_TYPE__` for assignments and `istype()`
Closes #1710
Closes #1711
Also fixes an issue with typepath dereferences and adds a test.
=> `__IMPLIED_TYPE__` implementation

Content.Tests/DMProject/Tests/Call/LateralPointlessOverride.dm, Content.Tests/DMProject/Tests/Call/PointlessParentCall.dm, DMCompiler/DM/Expressions/Procs.cs
MSO pointed this out, I thought we already accounted for it but we didn't.
=> Don't emit `PointlessParentCall` if lateral overrides exist

Content.Tests/DMProject/Tests/Operators/scope_proc_name.dm, Content.Tests/DMProject/Tests/Operators/scope_proc_pointless.dm, DMCompiler/Compiler/CompilerError.cs, DMCompiler/DM/Builders/DMExpressionBuilder.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm
Wixoa's testing indicates that, oddly enough, this only seems to work for `name`
Added a `PointlessScopeOperator` pragma for other uses. I'll update the wiki when this is merged.
=> Implement `::` for procs

README.md
Now puts you in the #rules channel rather than #development
=> Update the Discord invite in the README

DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Builders/DMProcBuilder.cs
I moved the emission of EmptyProc from compilation to parsing. Just a workaround to a larger problem though.
=> Fix EmptyProc applying to code existing before it was enabled

DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
Long strings (raw or not) weren't having their lines counted by the lexer so token locations would be off. This would say the warning was on line 2:
```dm
var/str = {"A
B
C"}
#warn Message
```
Now it's correctly on line 4
=> Fix line counting with long strings

OpenDreamRuntime/Procs/DMProc.cs
Exceptions now include file paths in their stack traces in addition to the line number.
=> Include source file in exceptions

OpenDreamClient/Input/MouseInputSystem.cs
A change to RT caused this entity lookup to no longer work. Giving it the `Approximate` flag fixes it.
=> Fix right-click menu entity lookup

OpenDreamClient/Interface/Controls/ControlInput.cs, OpenDreamClient/Interface/Controls/ControlWindow.cs, OpenDreamClient/Interface/DMF/DMFLexer.cs, OpenDreamClient/Interface/DMF/DMFParser.cs, OpenDreamClient/Interface/DMF/DMFWinSet.cs, OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/InterfaceElement.cs, Resources/OpenDream/DefaultInterface.dmf
Implements the `thing.attribute=value?thing.attribute=newvalue:thing.attribute=othervalue` syntax. 
Implements `thing.attribute=[[whatever.attribute as escaped]]`
oh also I made it so you don't need to explicitly implement `TryGetProperty` for every property, they are now backed by the data field annotations.
=> winset ternaries and embedded wingets

Content.Tests/DMProject/Tests/Savefile/BasicReadAndWrite.dm, OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs
Reverts OpenDreamProject/OpenDream#1709
turns out it was a BYOND bug, go figure
=> Revert "Converts empty strings to `null` in savefile serialization"

OpenDreamShared/Dream/IconAppearance.cs
`new IconAppearance(IconAppearance)` was creating lists twice for several fields. I moved the first creation from the field initializer to the other constructor. This cuts ~900MB of allocations during Goonstation init.
=> Avoid double-instantiating lists in IconAppearance

.github/workflows/compiler-test.yml
Now that these codebases use OD in their CI workflows, we should test against their latest master on our end to minimize breaking changes (or to find them so we can adequately communicate them).
=> Use master SS13 branches in CI

OpenDreamClient/Interface/Controls/ControlBrowser.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs
The `usr://` scheme was breaking Javascript that expected the URL to be the `http://` scheme.
I also removed the `res://` scheme since nothing used it. If we want to explore using RobustToolbox's resource management with BROWSER controls we can revisit it later.
=> Remove `usr://` custom scheme in BROWSER controls

.github/workflows/compiler-test.yml
Adds Nebula's dev branch to CI to make sure support for at least one Bay-based codebase doesn't break with changes.
=> Add Nebula dev branch to OpenDream CI

OpenDreamRuntime/DreamThread.cs
Closes #1787 
The "hidden" field is inaccessible in BYOND and will always return `null`.
Per wixoa's suggestion, this pr.
=> Attempting to read the "hidden" field on a proc will return null and emit a warning

Content.Tests/DMProject/Tests/Builtins/rgb2num.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Closes #1794
Im not sure this is technically the correct way to fix this, but it seems fine?
=> rgb2num accepts null

OpenDreamRuntime/Objects/Types/DreamObjectMob.cs
Doing `mob.client = null` does not do anything.
Fixes trying to observe a round on tg, due to this code:
```dm
observer.key = key
observer.client = client
```
=> Ignore attempts to set `mob.client = null`

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
The DM reference says this tests for "mobs, objs, turfs, or areas" but turns out it tests for /atom/movable too.
=> Return true for any atom type in `isloc()`

DMCompiler/DMStandard/Defines.dm
Actually defines ANIMATE_CONTINUE and ANIMATE_SLICE
Moves easing flags up next to the animation flags
Moves EASE_IN and EASE_OUT to easing flags instead of blockin em in with the animation flags.
Broke my unit tests REEEEEEEEEEEE
=> Animate Defines Cleanup

.github/workflows/lint.yml, OpenDreamClient/Rendering/DreamViewOverlay.cs
implements linting using rider's annotation tool, resharper. these lints aren't annotated using standard github pattern as there is a Ton of them, and resharper outputs them in SARIF. the best fitting tool for this seems to be the codeql security analysis tool, which is odd for a linter, but i think it still provides handy annotation
oh no! new bad code!! (only shows new inspections on the pr, not existing ones)
new commit addresses the issue, the issue is flagged as fixed and minimised
=> lint using resharper

Content.Tests/DMProject/Tests/Expression/InferredType.dm, DMCompiler/DM/Expressions/Binary.cs, DMCompiler/DM/Expressions/Builtins.cs
Fixes  #1752
also fixes `locate()` doing the same. There are probably some other built-ins that will need the same, I guess we can just fix them as they come up.
=> Fix inferred type expressions

DMCompiler/DMCompiler.cs
Fixes #1803
If a file passed through compiler arguments doesn't exist, it will now fail compilation and post an error instead of causing an exception.
=> Adds error message to missing file arg

OpenDreamRuntime/Objects/Types/DreamList.cs
Fixes #1737 
Substantially improves goon's client performance since all lights aren't duplicated on _every single move_
=> Can't duplicate in `vis_contents`

DMCompiler/DMStandard/Types/Atoms/Movable.dm
Couple minor DM std fixes to prevent runtimes when calling `Move()` while `loc` is `null`
=> Fix `Move()` from `null`

OpenDreamClient/Interface/Controls/ControlBrowser.cs, OpenDreamClient/Resources/DreamResourceManager.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/DreamManager.Connections.cs, OpenDreamShared/Network/Messages/MsgBrowseResource.cs, OpenDreamShared/Network/Messages/MsgBrowseResourceRequest.cs, OpenDreamShared/Network/Messages/MsgBrowseResourceResponse.cs, TestGame/code.dm
For BYOND, calling `browse_rsc()` should be basically free if the resource already exists on the client. For OD, we were sending the whole file every time. This was very bad for goonstation's performance when a client joined, because it would basically send 40mb of crap every time and hang the client while it was doing so.
Note that `browse()` is supposed to block until `browse_rsc()` is complete, while `output()` is not (according to searches of the BYOND discord).
It's hard to test how much impact this will have locally, but from my testing it should probably shave off like 60 seconds from subsequent joins. Now we just need to sort out the shedload of appearances that get sent.
=> Make `browse_rsc()` respect cache

DMCompiler/Compiler/CompilerError.cs, DMCompiler/DM/Expressions/Builtins.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm
This adds a new opinionated lint, PickWeightedSyntax / 3203, that is thrown whenever the "weighted" pick syntax, such as `pick(4;0, 3;1, 2;2, 1;3)`, is used.
It's disabled by default.
=> Add new optional lint for weighted pick() syntax

DMCompiler/Compiler/DM/AST/DMAST.ExpressionUnary.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Builders/DMExpressionBuilder.cs, DMCompiler/DM/Expressions/Unary.cs
Parses pointers but does not implement them.
No unit test since they're not implemented yet anyways.
Confirmed Daedalus `master` now compiles without errors.
=> Pointer Parsing

OpenDreamClient/Resources/DreamResourceManager.cs, OpenDreamRuntime/DreamConnection.cs, TestGame/code.dm
if a file was already ready for sending, we were erroring. We shouldn't have been.
Also made a similar check on the client, where `browse_rsc()` calls that were duplicated were sending requests twice.
=> Fix duplicate `browse_rsc()` calls

OpenDreamClient/Input/ContextMenu/ContextMenuItem.xaml.cs, OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamClient/Rendering/DMISpriteSystem.cs, OpenDreamClient/Rendering/DreamIcon.cs, OpenDreamClient/Rendering/DreamPlane.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs
The texture for an atom is now only re-rendered once its appearance or animation frame changes. This same texture is reused between frames instead of performing the entire render process again. This leads to massive improvements in client performance, in both render times and allocation rate.
Observing this same spot on Paradise brought allocations per frame down ~350KB (~20.5MB per second at 60FPS!). FPS is more difficult to get a hard number for, but this brought it much closer to a stable 60FPS on my laptop's integrated graphics.
Before:
After:
~~Did a lot of playing around with things that led to some dirty code, so I'd like to clean things up some before merging. There are also some minor bugs (there are so many magic numbers & steps in the renderer) and I need to test how this plays …
=> Cache icon renders between frames

Content.Tests/DMProject/Tests/Preprocessor/fexists_fail.dm, Content.Tests/DMProject/Tests/Preprocessor/fexists_pass.dm, DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs
=> Handle `fexists()` in the preprocessor

OpenDreamClient/Rendering/DreamIcon.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs
Changes in #1825 led to keep-together groups always skipping the full render path.
=> Fix color/filter rendering on keep-together icons

OpenDream.sln, OpenDreamClient/Input/MouseInputSystem.cs, OpenDreamClient/Interface/Controls/ControlChild.cs, OpenDreamClient/Interface/Controls/ControlInfo.cs, OpenDreamClient/Interface/Controls/ControlMap.cs, OpenDreamClient/Interface/Controls/UI/ScalingViewport.cs, OpenDreamClient/Interface/Controls/UI/Splitter.cs, OpenDreamClient/Interface/Controls/UI/VerbPanelGrid.cs, OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs, OpenDreamClient/Interface/InterfaceElement.cs, Resources/OpenDream/DefaultInterface.dmf, TestGame/TestInterface.dmf
Our CHILD control now uses a custom Splitter control rather than the SplitContainer provided by RT. This simplifies a lot of the code in `ControlChild` and allows us to more closely emulate BYOND appearance and behavior.
It now also has a color and border to more clearly separate panes.
Before:
After:
I also made the `top`/`bottom` attributes alias to `left`/`right` as they do in BYOND. This fixes the top-left Text and Info buttons on Paradise.
=> Improvements to the CHILD control

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Instead of returning null on a null center, we now return an empty list (parity)! Truly we are in the future.
=> Range and Orange return empty list on null center.

OpenDreamClient/EntryPoint.cs, OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/DreamManager.Connections.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamRuntime/Rendering/ServerAppearanceSystem.cs, OpenDreamShared/Dream/ColorMatrix.cs, OpenDreamShared/Dream/IconAppearance.cs, OpenDreamShared/Network/Messages/MsgAllAppearances.cs, OpenDreamShared/Rendering/SharedAppearanceSystem.cs
The AllAppearancesEvent was changed to a custom NetMessage that doesn't include values that haven't changed from the default. This greatly reduces the amount of data the client needs to download to have all the appearances.
=> Reduce size of appearances being sent over the network

Content.Tests/DMProject/Tests/Operators/Overloads/complex_numbers.dm, DMCompiler/Compiler/DM/DMParser.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Objects/Types/DreamList.cs, OpenDreamRuntime/Objects/Types/DreamObjectMatrix.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
I swore I wouldn't do this again, but here we are.
Implements +, -, *,/, and | operator overloads because they were very easy.
I'm gonna do it in small parts this time. Next PR I'll clean up some of DMOpcodeHandler
Cleans up the emitted warning so that it tells you what operator is not implemented ie 
```
Warning OD0000 at Camera.dm:132:18: operator"" overloads are not implemented. They will be defined but never called.
```
=> Implement a few easy operator overloads

DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/Optimizer/PeepholeOptimizations.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs
`(PushReferenceValue, Return) -> ReturnReferenceValue`
Per my frequency analysis this pattern occurs ~16k times in Paradise and ~25k times in goon and TG. It is a top-ten offender on all codebases tested.
However, this optimization is heavily kneecapped by #1842 which causes it to only be applied 664 times in Paradise bytecode. Once that issue is fixed this will become much more significant, as a large number of procs will no longer modify their stack when they return.
=> Peephole optimize proc returns

OpenDreamClient/Rendering/DreamViewOverlay.cs
Overlays without `RESET_TRANSFORM` were always using their parent icon's transform without input from their own. Now the two are multiplied.
This fixes parallax on Paradise:
https://github.com/OpenDreamProject/OpenDream/assets/30789242/1c289eb9-13a7-4911-9e5c-a3a32c0a92a8
=> Fix transforms on overlays

Content.IntegrationTests/DMProject/Tests/range.dm, OpenDreamRuntime/DreamMapManager.cs, TestGame/code.dm
closes https://github.com/OpenDreamProject/OpenDream/issues/1688. apparently it is parity to grow and then shrink
=> handles shrinking maxx/y

OpenDreamClient/Interface/Controls/ControlBrowser.cs
#1839 gave browsers a gray background since apparently CEF renders transparently.
=> Give browser controls a white background

Content.Tests/DMProject/Tests/Image/mutableappearance_arguments.dm, DMCompiler/DMStandard/Types/Mutable_Appearance.dm, OpenDreamRuntime/Procs/DMProc.cs
Fixes things like `new /mutable_appearance(icon = 'abc.dmi', icon_state = "abc")`
This was breaking global init on tgstation.
=> Fix /mutable_appearance/New() named args

Content.Tests/DMProject/Tests/Operators/Overloads/complex_numbers.dm, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DreamPath.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Objects/Types/DreamObjectMatrix.cs, OpenDreamRuntime/Procs/AssignRefProcState.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
implements `operator*=` and `operator/=`, with appropriate calls to `operator*` and `operator/` when needed
=> Implement multiplyref & divideref operator overloads

OpenDreamRuntime/Objects/DreamIcon.cs, OpenDreamRuntime/Objects/Types/DreamObjectIcon.cs, OpenDreamRuntime/Objects/Types/DreamObjectImage.cs
In the following code:
```
var/icon/I1 = new /icon('icons.dmi')
I1.DrawBox("#ff0000", 0, 0, 16, 16)
var/icon/I2 = new /icon(I1)
```
`new /icon(I1)` would generate I1's entire DMI and use that to create `I2`. Now it instead only copies the queued operations. This massively improves its performance and memory usage (several GBs over /tg/ init, and more over the round).
=> Optimize `new /icon(icon)`

DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/DM/DMProc.cs, DMCompiler/Optimizer/AnnotatedByteCodeWriter.cs, DMCompiler/Optimizer/AnnotatedBytecode.cs, DMCompiler/Optimizer/AnnotatedBytecodeSerializer.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/ProcDecoder.cs
Fixes #154
Each DMProcState now has 16 slots for enumerators instead of them being a stack. Opcodes using enumerators must refer to which slot they're using.
=> Fix `goto` inside multiple enumerator loops

OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Objects/Types/DreamObjectAtom.cs, OpenDreamRuntime/Objects/Types/DreamObjectFilter.cs, OpenDreamRuntime/Objects/Types/DreamObjectImage.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeHelpers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
`filters = list("type"=...)` is the same as `filters = filter("type"=...)`. Interestingly, `filters += list("type"=...)` does not work.
Fixes #1651
=> Fix `filters = list("type"=...)`

OpenDreamClient/EntryPoint.cs, OpenDreamClient/Interface/Controls/ControlBrowser.cs, OpenDreamClient/Interface/Controls/ControlWindow.cs, OpenDreamClient/Interface/Controls/InterfaceControl.cs, OpenDreamClient/Interface/DMF/DMFParser.cs, OpenDreamClient/Interface/DMF/IDMFProperty.cs, OpenDreamClient/Interface/Descriptors/InterfaceDescriptor.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/DummyDreamInterfaceManager.cs, OpenDreamClient/Interface/InterfaceElement.cs
Setting `window.location` to `byond://winget?id=output&property=size&callback=JSFunction` does a winget for `output`'s size and executes JSFunction with the result.
Other interface-related fixes:
- winget() on an invisible control no longer returns 0
- winset() on an anchored control's size/pos now more closely matches BYOND behavior
- The CVar `interface.resolutionAutoScaleEnabled` is disabled by default, which fixes weird scaling behaviors when resizing a window too small
- Size 0x0 now more closely matches BYOND behavior
This fixes tg's chat extending over the command bar.
~~Currently breaks goonstation's and paradise's interfaces. I suspect the changes to anchoring.~~ Fixed
=> Implement `byond://winget?...`

DMCompiler/Bytecode/DreamProcOpcode.cs, OpenDreamRuntime/Procs/DebugAdapter/DebugAdapter.cs, OpenDreamRuntime/Procs/DebugAdapter/DebugAdapterClient.cs, OpenDreamRuntime/Procs/DebugAdapter/DreamDebugManager.cs, OpenDreamRuntime/Procs/ProcDecoder.cs
The peephole changes brought a bunch of new opcodes that didn't get added to ProcDecoder. This fixes DMDisassembler and the VSC debugger's disassembly view.
=> Add missing instructions to ProcDecoder

Content.Tests/DMProject/Tests/Dereference/DatumIndex.dm, DMCompiler/Compiler/CompilerError.cs, DMCompiler/DM/Expressions/Dereference.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm
Closes #1876 
Invalid in BYOND 515.1641+
Don't want to make it fatal since it'd brick OD compilation of codebases targeting older versions.
=> Lint for invalid datum[] indexing

DMCompiler/DM/Builders/DMExpressionBuilder.cs
`.` had to be given the inferred type because of an inaccuracy in `[]`'s source of inferred type. This fixes that and ProcSelf no longer has a type.
=> Don't give `.` a type

Content.Tests/DummyDreamMapManager.cs, OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/DreamMapManager.cs, OpenDreamRuntime/Objects/Types/DreamList.cs, OpenDreamRuntime/Objects/Types/DreamObjectArea.cs, OpenDreamRuntime/Rendering/ServerAppearanceSystem.cs, TestGame/code.dm, TestGame/map_z1.dmm
Now fullbright can work, hooray
=> Implement `/area` appearances

OpenDreamRuntime/Objects/Types/DreamList.cs
Appears to be a no-op in BYOND:
=> Handle appending `null` to `vis_contents`

OpenDreamClient/DreamClientSystem.cs, OpenDreamClient/Input/ContextMenu/ContextMenuItem.xaml.cs, OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamClient/Rendering/DMISpriteSystem.cs, OpenDreamClient/Rendering/DreamIcon.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamClient/Rendering/RenderTargetPool.cs
DreamIcon now pools its render targets instead of holding onto them for their entire lifetime.
=> Use an IRenderTexture pool in DreamIcon

OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeWorld.cs
If you implement `/world/Error()` yourself then BYOND will only print the error to the log if you explicitly call `..()`. We copy that behavior now, allowing games to silence errors if they want to.
=> Implement `/world/Error()`'s default `..()` behavior

OpenDreamClient/Rendering/DreamPlane.cs
Use DreamIcon's `TextureRenderOffset`
=> Fix the rendering offset for more complex textures in the mouse map

Content.Tests/DMProject/Tests/Statements/Control Flow/try_catch5.dm, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs
The catch var index wasn't accounting for arguments the proc had.
=> Fix `catch` in procs with arguments

OpenDreamClient/Interface/DMF/IDMFProperty.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/DummyDreamInterfaceManager.cs
So apparently BYOND just loves being grossly inconsistent, and `winget()` calls act differently to embedded wingets.
This fixes that, and incidentally enables darkmode on goon as a side-effect
=> Implements `winget()` formatting 

OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/Objects/DreamObjectDefinition.cs, OpenDreamRuntime/Procs/Native/DreamProcNative.cs
The proc ID wasn't properly set if there was no `/world/Error()` override and `SpawnProc()` didn't work for synchronous native procs.
=> Fix default /world/Error()

OpenDreamRuntime/Objects/Types/DreamList.cs
As far as I know, a blank image `new /image` added as an overlay shouldn't inherit the parent's icon. It should only do that if you add a raw icon state as an overlay, like `"foo"`.
=> Stop image overlays with null/blank icon state from inheriting icons

OpenDreamClient/Interface/Html/HtmlParser.cs
This gives HtmlParser the ability to support HTML character entities in body text. This is primarily useful to clean up text such as "`&quot;`", "`&apos;`" ,and "`&#33;`".
This was tested with [Tomeno's OpenDream branch of Console](https://github.com/Tomeno/console/tree/opendream_cope) but with changes to interface/default.dmf reverted and then the computer_docked window deleted (it attempts to share ownership of controls). When operating a computer and "> "-commands are typed, the window no longer shows HTML entities with this patch.
...I'm sure there are simpler ways to test this, but that's where I found the issue.
=> HtmlParser: Support named entities in body text

.github/workflows/compiler-test.yml, DMDisassembler/DMDisassembler.csproj, DMDisassembler/Program.cs
Resolves #1879 but I think we should open a separate issue for modifying ProcDecoder to use OpcodeMetadataAttribute.
Changes:
- DMDisassembler's commands can now be passed as CLI arguments
- Added `crash-on-error` which is a `test-all` wrapper that kills DMDisasembler if it finds errors (to keep the GitHub Action simple)
- CI now builds `DMDisassembler` and runs `crash-on-error` on TG
=> Add CI testing for DMDisassembler

.github/workflows/build-test.yml, OpenDreamPackageTool/Program.cs
A version of the server build with `-c Tools` is helpful for our VSCode extension because it includes our DM debugger.
=> Add a Tools build to GitHub releases

Content.Tests/DMProject/Tests/SetStatements/unimplemented_with_body.dm, Content.Tests/DMProject/Tests/SetStatements/unimplemented_without_body.dm, Content.Tests/DMTests.cs, DMCompiler/Compiler/CompilerError.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DMCompiler.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm
currently some opendream_unimplemented warnings from dmstandard aren't being emitted, as we null both the Statement and SetStatement blocks if the Statement block is empty (due to having an empty proc body)
=> restores opendream_unimplemented warnings for procs with empty bodies in DMStandard

DMCompiler/DMStandard/UnsortedAdditions.dm, DMCompiler/DMStandard/_Standard.dm, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeHelpers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamRuntime/WalkManager.cs, TestGame/code.dm
- Implemented `walk()`. Including `walk(Ref, 0)` to cease any walking.
- Implemented `walk_rand()`
- Added a helper for getting a random dir
- ~~Added a `GetStep()` overload that takes dir as an integer directly, to avoid redundant casting.~~
- `speed` is now ignored in WalkManager, rather than the native walk-related procs
- Properly flags `walk_to()` as unimplemented
https://github.com/user-attachments/assets/dd802c99-afa4-4720-950f-c68563211b53
=> Implement `walk()` and `walk_rand()`

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
In `DreamProcNativeRoot.cs` there is a line used in `viewer()` and `oviewer()`:
```cs
if (Math.Abs(centerPos.X - mob.X) <= depth && Math.Abs(centerPos.Y - mob.Y) <= depth && centerPos.Z == mob.Z)
```
if you have more than one Z level, then more mobs will be outside of the Z level than in it. Therefore, you can slightly speed up the code by having the Z level check run first, and short circuit the rest of the `if` condition, evaluating it slightly faster:
```cs
if (centerPos.Z == mob.Z && Math.Abs(centerPos.X - mob.X) <= depth && Math.Abs(centerPos.Y - mob.Y) <= depth)
```
=> Slight optimisation in viewer() and oviewer()

TestGame/code.dm
The renderer tests use these procs that BYOND is missing.
=> Fix compiling TestGame in BYOND

DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DreamPath.cs
Parsing of modified types was just skipping to the next `}` disregarding that the brace could belong to something else. Now it parses the statements inside so it correctly ends at the correct `}`.
=> Smarter parsing of modified types

OpenDreamClient/Resources/DreamResourceManager.cs
Fixes this exception:
`System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\Ike\AppData\Roaming\Space Station 14\data\OpenDream\Cache\127.0.0.1:1212\browse1774779223.html'`
`:` is not a legal filepath on Windows. See [this Microsoft doc](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file) if you don't believe me.
This fixes TGUI when connecting to a local server.
=> Strip colons from the server IPs in the cache directory

OpenDreamRuntime/DreamValue.cs
Same reasoning and method as #1922, it gets rid of a warning and an indent.
=> Convert DreamValue.cs to file-scoped namespace

OpenDreamRuntime/DreamManager.Connections.cs, OpenDreamRuntime/Procs/DebugAdapter/DreamDebugManager.cs, OpenDreamRuntime/Procs/DebugAdapter/Protocol/Request.cs, OpenDreamRuntime/Procs/DebugAdapter/Protocol/RequestHotReloadInterface.cs, OpenDreamRuntime/Procs/DebugAdapter/Protocol/RequestHotReloadResource.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs
Adds hot reload commands for resources and interface to the debug adapter so they can be called by the vscode extension
=> VSCode Extension Hot Reload Enable

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
By adding `!` and `?` at strategic locations, as well as some other changes, the warnings about dereferencing/referencing of null/nullable types are removed. in (presumably) all the cases where the warning exists there are already circumstances that make it so that the errors being warned against can't happen anyway, so these shouldn't hurt. fingers crossed.
The file has gone from having 39 warnings to only 14.
Some of the warnings that are more legitimate in origin have been left in.
=> Clean up lots of warnings in DreamProcNativeRoot.cs

DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/Compiler/DM/DMParserHelper.cs, DMCompiler/Compiler/DMM/DMMParser.cs, DMCompiler/Compiler/DMPreprocessor/DMMacro.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs, DMCompiler/Compiler/Parser.cs, DMCompiler/Compiler/Token.cs
Fixes 19 warnings in the compiler (132 -> 113).
Also remove an unnecessary list copy I noticed in the DMM parser.
=> Fix nullable warnings when using token.Value

OpenDreamClient/Input/MouseInputSystem.cs, OpenDreamClient/Interface/Controls/ControlMap.cs
Resolves #1928
This implements TG's right-clicking behavior. I tested it by right clicking on a fire extinguisher cabinet repeatedly, which toggles its opened/closed state.
Shift+RMB behavior is still unimplemented, see https://github.com/OpenDreamProject/OpenDream/issues/1936
=> Implement `right-click` parameter

OpenDreamRuntime/Input/MouseInputSystem.cs, OpenDreamShared/Dream/ScreenLocation.cs
Resolves #1926 
Test code:
```
/client/New()
..()
show_popup_menus = FALSE
/client/Click(object,location,control,params)
..()
src << "[params]"
```
I clicked the left, middle, and right mouse button once each with all modifiers held. Slight differences in coordinates are due to me not clicking the exactly identical spot.
BYOND:
```
icon-x=29;icon-y=29;left=1;ctrl=1;shift=1;alt=1;button=left;screen-loc=7:29,3:29
icon-x=29;icon-y=29;middle=1;ctrl=1;shift=1;alt=1;button=middle;screen-loc=7:29,3:29
icon-x=29;icon-y=29;right=1;ctrl=1;shift=1;alt=1;button=right;screen-loc=7:29,3:29
```
OpenDream:
Note that middle-mouse is still broken in OD, ref #1925 
I converted it to a `StringBuilder` because afaict all `NameValueCollection` was doing for us was escaping the colons in `screen-loc` and we …
=> Fix remaining click param issues

DMCompiler/DM/DMObjectTree.cs, DMCompiler/DM/DMProc.cs, DMCompiler/DMCompiler.cs, DMCompiler/Json/DreamCompiledJson.cs, DMCompiler/Json/DreamMapJson.cs, DMCompiler/Json/DreamObjectJson.cs, DMCompiler/Json/DreamProcJson.cs, OpenDreamRuntime/Procs/DMProc.cs
Applies nullable flags or `required` where they make sense.
Fixes 16 warnings in the compiler (down to 97 with #1944).
=> Fix nullability warnings in JSON definitions

OpenDreamClient/Interface/DMF/DMFLexer.cs, OpenDreamClient/Interface/DMF/DMFParser.cs, OpenDreamClient/Interface/DMF/DMFWinSet.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/DummyDreamInterfaceManager.cs, OpenDreamClient/Interface/InterfaceMacro.cs
Resolves #1936 
- In the DMF, modifier keys are now treated as keys when no other key is present. This appears to be more in line with the behavior described in the ref.
- `.winset :[type].whatever` is now implemented, where `:[type]` is the default control of that type
This makes TG shift+RMB behavior functional.
RMB toggles the cabinet's open/closed state. Shift+RMB opens ye olde context menu.
https://github.com/user-attachments/assets/c4a3949a-c088-4f12-9aeb-764bb8b5227c
=> Fix modifiers as keybinds, add ".winset :type" support

DMCompiler/DM/Expressions/Binary.cs
The constant folding for `||` was always failing if the LHS was constant and false-y. Now it gives the RHS if it's also a constant.
=> Improve the or operator's constant folding

DMCompiler/Compiler/DM/AST/DMAST.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/Optimizer/AnnotatedBytecode.cs, DMCompiler/Optimizer/PeepholeOptimizations.cs, DMCompiler/Optimizer/PeepholeOptimizer.cs
Fixes several compiler warnings related to peephole optimizations and the DM parser. I also fixed 2 runtimes that would occur with DM code like:
```
switch()
if("A")
return
```
```
throw; // Lacking a value to throw
```
Brings warnings down to 78 from 97.
=> Fix compiler warnings

OpenDreamClient/EntryPoint.cs, OpenDreamClient/Resources/DreamResourceManager.cs
`EnsureCache()` wasn't being called before using `_cacheDirectory` in some cases.
Also no longer delete the cache folder on shutdown. We want to keep those files, and it didn't work in a few situations anyways.
=> Fix missing `EnsureCache()` calls

OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Has the fun effect of unindenting nearly the entire file. Aside from removing two curly braces and adding a semicolon, nothing else was changed. The diff got fucky due to all the blank lines, which is annoying. nothing should have broken though.
Did it because it was throwing a warning, and the file has 39. with this we can reduce it to 38. 👍 
Edit: the file now has 15 warnings. this PR makes it 14.
=> Convert dreamprocnativeroot.cs to file-scoped namespace

OpenDreamClient/Input/ContextMenu/ContextMenuPopup.xaml.cs, OpenDreamClient/Interface/DebugWindows/IconDebugWindow.xaml.cs, OpenDreamRuntime/AtomManager.cs, OpenDreamShared/Dream/IconAppearance.cs, OpenDreamShared/Network/Messages/MsgAllAppearances.cs
Resolves #1960 
As far as I can tell it seems to work?
=> Add `name` to `IconAppearance`, fix placeholder turf names

DMCompiler/DM/DMProc.cs
Small micro-opt I saw while browsing the code. This'll avoid some list resizing allocations.
=> Pre-allocate the `ProcArgumentJson` list for procs

OpenDreamRuntime/Objects/Types/DreamList.cs
Fixes #1967 
Fake AO can now be toggled (ignore the morbillion transparency issues, those are unrelated)
https://github.com/user-attachments/assets/808bbcb9-408a-4a68-bd97-16afc9b3de0f
=> Implement missing `GetValues()` overrides

DMCompiler/DMStandard/DefaultPragmaConfig.dm
Baystation emits this and we shouldn't error by default on code BYOND compiles.
=> Reduce `DuplicateVariable` to a warning by default

Content.Tests/DMProject/Tests/Regex/regex_start.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
A change had made `findtext()` always return 0 when used with a /regex. Now it should properly run the regex.
This fixes the map loader on TG, which was improperly treating TGM-formatted maps as BYOND-formatted DMM maps due to this:
```dm
if(findtext(tfile, matches_tgm))
map_format = MAP_TGM
else
map_format = MAP_DMM
```
=> Fix `findtext()` with /regex

Content.Tests/DMProject/Tests/Text/rawstr_parsing2.dm, DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
The first character after every newline was being thrown out.
The newline immediately after `@{"` and before `"}` was being included in the value. Those are now removed.
=> Fix lexing of long raw string values

DMCompiler/DM/DMProc.cs, OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/Procs/DMProc.cs
Local proc variables that fall out of scope during the proc were not serialized due to an overeager optimization. This reverses that.
Due to using `out Result` instead of `out var result`, indexing a list set the proc return value. This changes the variable used to avoid that. ~~i see why some codebases require explicit `this`/`src` now~~
Due to setting alpha casting a `float` to a `byte`, the new alpha value was just truncated to the least significant byte of its integer conversion, meaning setting the alpha to `256` would set it to `0`, setting it to `355` would set it to `99`, etc. Now, it's clamped between 0 and 255 before the conversion.
=> Fix issues found via Nebula testing

OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
When a variable is typed as `var/whatever/` at compiletime, the compiler allows `initial()` usage for any variable on that type. If the value in that variable is of a different type, BYOND returns null, while we currently throw a `KeyNotFoundException`. This PR makes us return null as well. This could maybe be made a config thing somehow, but... eh.
=> Fix initial() with mismatched variable and value types

Content.IntegrationTests/Content.IntegrationTests.csproj, Content.Tests/Content.Tests.csproj, Content.Tests/DMTests.cs, Content.Tests/DummyDreamMapManager.cs, DMDisassembler/DMDisassembler.csproj, OpenDreamPackageTool/OpenDreamPackageTool.csproj, OpenDreamPackaging/OpenDreamPackaging.csproj, OpenDreamRuntime/Objects/DreamIcon.cs, OpenDreamRuntime/Procs/AsyncNativeProc.cs, OpenDreamServer/OpenDreamServer.csproj, OpenDreamShared/OpenDreamShared.csproj, OpenDreamShared/Resources/DMIParser.cs
See title. Also elevates warnings to errors in all of the projects that don't currently have warnings.
=> Remove all `OpenDreamShared` and `Content.Tests` warnings

DMCompiler/Compiler/DMM/DMMParser.cs, DMCompiler/DM/DMObject.cs, DMCompiler/DreamPath.cs
Causes too much confusion between the difference of path-descendants and inheritance-descendants
=> Remove `DreamPath.IsDescendantOf()`

OpenDreamRuntime/Objects/Types/DreamObjectImage.cs
Body part overlays in TG are created with a `dir` of `NONE`, or 0. This is an ignored value in BYOND which apparently leaves the inherits-direction flag on. Fixing this causes body parts to correctly rotate with you.
=> Leave an image's `InheritsDirection` on when the provided `dir` is invalid

.github/workflows/compiler-test.yml
They run OD in CI now and also /vg/ is a good target since it's pretty divergent from other codebases.
=> Compile /vg/ in CI

OpenDreamClient/Rendering/AtomGlideSystem.cs
At some point RT changed `SetLocalPositionNoLerp()` to no longer cancel an already-active lerp. This caused RT's lerping and our gliding to fight, leading to things jarringly jumping around.
We now call `SharedTransformSystem.Reset()` before SharedTransformSystem gets a chance to run `FrameUpdate()` which disables any lerping.
=> Fix gliding

DMCompiler/DM/Builders/DMExpressionBuilder.cs
Resolves #1977 
`astOperationOffset` never reached `2`, which is the index of the `IndexOperation`. Instead it was trying to repeat the previous `FieldOperation` again.
=> Fix an issue with deref operations

DMDisassembler/DMProc.cs, DMDisassembler/Program.cs
Passing `dump-all` to the disassembler will write the disassembly of all procs to a file named `[CompiledJsonFile].dmd`.
Useful for bytecode analysis since I can no longer be bothered to maintain my annotated bytecode writer branch.
=> Add a `dump-all` command to the disassembler

OpenDreamRuntime/Objects/DreamIcon.cs
In /tg/, blending a 32x32 icon onto a 115x115 icon was causing an out of bounds error. This was because it was assumed that for every pixel in the first icon, there was also one in the second icon. Now we shrink the bounds to the smaller of the two, resulting in byond's behavior.
=> Handle `/icon.Blend()`-ing a small icon onto a bigger one

OpenDreamRuntime/DreamManager.cs
0xC is icon resources, 0x27 is supposed to be file resources.
Make them the same for now to fix the exception when trying to use 0xC.
=> Alias ref-ID `0xC` to `0x27` for now

OpenDreamClient/Interface/Controls/ControlBrowser.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs
The window argument of `browse()` can reference either a browser control directly, or a window that contains a browser control.
A `browse()` referencing a window was creating a new popup because it didn't recognize the window as a valid target. I removed the difference between popups and other windows, they are held in the same dictionary now.
This gets one step closer to tgui_say working. It no longer creates a useless popup when joining, and the only thing keeping it from fully working is that RT does not initialize the browser control until it is visible for the first time.
=> Fix a few bugs in `browse()`

Content.Tests/DMProject/Tests/Const/StaticEqualsConstVar.dm, DMCompiler/DM/Builders/DMExpressionBuilder.cs
See title. Brings Baystation from 211 errors down to 15.
I'm not entirely confident that this doesn't break things, as var parsing is a bit of a convoluted mess. I did confirm that this didn't generate any *new* errors for Baystation, and I tested that Paradise still seems to be playable.
=> Fix setting a static var to a const var

DMCompiler/DMStandard/Types/World.dm, OpenDreamRuntime/EntryPoint.cs
- Mark it as implemented
- Disable the cvar in pre-init so we actually reach `DreamObjectWorld` handling
=> `world.sleep_offline` fixes

DMCompiler/DMStandard/Types/Atoms/Turf.dm
These may be overriden on `/atom`, and their result needs respected. This fixes tg's rails allowing you to phase through them on one side.
=> Call parent in `/turf/Enter()` and `/turf/Exit()`

.github/workflows/compiler-test.yml
More baycode representation and also aurora runs OD lints as part of their CI.
=> Add Aurorastation to compiler CI

OpenDreamClient/Interface/Controls/ControlMap.cs, OpenDreamClient/Interface/Controls/ControlWindow.cs
In BYOND non-visible browser controls on secondary windows still run & execute javascript in the background. We would only start running browser controls from the first time their window was shown.
Fixing this gets tg's say window working.
Depends on https://github.com/space-wizards/RobustToolbox/pull/5489
=> Run UI controls in the background

OpenDreamRuntime/DreamValue.cs
Addresses Rider warnings for marking methods as readonly to avoid struct copies. Also addresses a bunch of other warnings and resharper issues.
=> `DreamValue` cleanup

DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/Optimizer/PeepholeOptimizations.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/ProcDecoder.cs
`PushFloat -> Return` is a common pattern in TG with 21,601 occurrences. This is mainly due to procs returning `TRUE` or `FALSE`.
This PR replaces that pattern with a new `ReturnFloat` opcode to avoid pushing to and immediately popping from the stack on all of those proc returns.
=> `ReturnFloat` peephole optimization

DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/Optimizer/PeepholeOptimizations.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/ProcDecoder.cs
`AssignPop` made it sound like it was popping from the stack, when in reality it wasn't pushing to the stack in the first place.
=> Rename `AssignPop` to `AssignNoPush`

Content.Tests/DMProject/Tests/Arg/ProcArgumentGlobal_lint.dm, DMCompiler/Compiler/CompilerError.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm
Lints for this BYOND bug: https://www.byond.com/forum/post/2830750
The following code prints `5` in BYOND but errors with `Unknown identifier "global.bar"` in OpenDream.
```
/datum/proc/foo(/var/bar = 5)
return
/proc/main()
world.log << global.bar // This prints 5 in BYOND
```
This PR doesn't replicate BYOND behavior, it just adds a lint. Ref https://github.com/OpenDreamProject/OpenDream/issues/2065 for tracking the status of replicating BYOND behavior.
Credit to @out-of-phaze for reminding me of this BYOND bug's existence.
I tested about half a dozen codebases and only found a single hit in goonstation.
=> Lint for `/var/` in proc args

DMCompiler/Optimizer/PeepholeOptimizations.cs, DMCompiler/Optimizer/PeepholeOptimizer.cs, OpenDreamRuntime/Procs/ProcDecoder.cs
This PR does a few things:
1. Fixes peephole optimizations not being applied to opcodes created by peephole optimizations. E.g.:
`PushNull -> Assign -> Pop` was being optimized to `PushNull -> AssignPop`, but the optimizer offset wasn't rolled back far enough to consider optimizing `PushNull -> AssignPop` to `NullRef`. It would only be rolled back to the new `AssignPop` opcode. This meant that the `NullRef` opcode was never used, which is now fixed.
2. Fixes a few opcodes not being implemented in `ProcDecoder`. Because a few opcodes were specific to optimizations that were never applied, they never triggered any errors in the disassembler. `DreamProcOpcode.NullRef` and `DreamProcOpcode.PushNOfStringFloats` can now be decoded.
3. Fixes `PushNOfStringFloats` only being applied to pairs of …
=> Peephole optimizer & proc decoder fixes

DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/Optimizer/PeepholeOptimizations.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/ProcDecoder.cs
There are ~10.5k usages of `Append` in Paradise bytecode. Of these, all but ~160 immediately pop the value that `Append` pushes to the stack.
This adds a simple `AppendNoPush` peephole opt and opcode, with identical behavior except the opcode handler does not push the result to the stack.
=> Add an `AppendNoPush` optimization

OpenDreamClient/EntryPoint.cs, OpenDreamClient/Input/ContextMenu/ContextMenuPopup.xaml.cs, OpenDreamClient/Interface/BrowsePopup.cs, OpenDreamClient/Interface/Controls/ControlChild.cs, OpenDreamClient/Interface/Controls/ControlTab.cs, OpenDreamClient/Interface/Controls/ControlWindow.cs, OpenDreamClient/Interface/DMF/IDMFProperty.cs, OpenDreamClient/Interface/Descriptors/InterfaceDescriptor.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/Html/HtmlParser.cs, OpenDreamClient/Interface/InterfaceElement.cs, OpenDreamClient/OpenDreamClient.csproj, OpenDreamClient/Rendering/AtomGlideSystem.cs, OpenDreamClient/Rendering/ClientImagesSystem.cs
Takes `OpenDreamClient` from 40 to 20 warnings.
I confirmed that the changes to gliding and the context menu didn't break them.
=> Halves `OpenDreamClient` warnings

DMCompiler/DM/Builders/DMASTFolder.cs, DMCompiler/Optimizer/PeepholeOptimizations.cs
Moves bitshift const folding from the old DMASTFolder to a peephole optimization.
Not particularly useful until https://github.com/OpenDreamProject/OpenDream/issues/2059 is resolved.
=> Bitshift const fold peephole opt

Content.Tests/DMProject/Tests/Dereference/RuntimeSearchOperatorLint.dm, DMCompiler/Compiler/CompilerError.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm
Adds a new stylistic pragma that emits for using the [runtime search operator](https://www.byond.com/docs/ref/#/operator/:). Disabled by default.
Requested by beestation.
=> `RuntimeSearchOperator` pragma lint

DMCompiler/DM/Builders/DMASTFolder.cs, DMCompiler/Optimizer/PeepholeOptimizations.cs
Moves more DMASTFolder operations to the peephole optimizer.
More useful once https://github.com/OpenDreamProject/OpenDream/pull/2069 is merged.
=> Bitwise const folding

DMCompiler/DMStandard/_Standard.dm
we have them right in the procparameter attribute just not here
https://github.com/OpenDreamProject/OpenDream/blob/68765936774ac55512c8812c33fbda2770f06388/OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs#L859
=> corrects DMStandard default vars for findlasttext(ex)

DMCompiler/DMStandard/_Standard.dm
more things picked up on my dm ref drudgery
per https://github.com/OpenDreamProject/OpenDream/blob/39e6af5bfb86e1cff7c501a18f2fca51400d2d5d/OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs#L942
=> marks flick() as unimplemented in dmstandard

OpenDreamRuntime/Objects/Types/DreamList.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs, OpenDreamShared/Resources/DMIParser.cs
- Implement `list() << output(...)`
- Like BYOND, the `list()` form only supports mobs and clients, not world, and is not recursive
- Fix `vars[1]` erroring instead of returning the name of the first var
- No attempt was made to match BYOND's variable order, just to do something sensible instead of erroring
- Code example: `for(var/name in (vars & data))`
- Fix `typesof("/foo/verb")` returning non-verb subtypes when there are no verbs
- Fix `Cut(2, 1)` throwing (negative count to RemoveRange) instead of doing nothing
- Fix bad offset math when DMIParser skips a `tEXt` chunk, leading to UTF-8 decode exceptions
- Fix `animate(filter, ...)` not setting LastAnimatedObject
- Animating filters still isn't implemented, but at least a chained `animate()` call doesn't error
=> Fix some sources of runtime errors

DMCompiler/Compiler/CompilerError.cs, DMCompiler/DM/Builders/DMExpressionBuilder.cs, DMCompiler/DM/Builders/DMProcBuilder.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm
Pragma `OD2212` triggers as an error when the code accesses a global var while there's an identically named local one
Closes #997
=> Fix static vars trying to reference local vars, and add pragma

DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Builders/DMExpressionBuilder.cs, DMCompiler/DM/DMValueType.cs, DMCompiler/DM/DMVariable.cs, DMCompiler/DM/Expressions/Dereference.cs, DMCompiler/DM/Expressions/LValue.cs, DMCompiler/DMStandard/Types/World.dm
`world.opendream_topic_port` was const-folding to `null` despite its value being set at runtime.
Fixes #2094
Fixes #2095
=> Add `opendream_noconstfold`, add it to some world vars

DMCompiler/Compiler/DM/AST/DMAST.Expression.cs, DMCompiler/Compiler/DM/AST/DMAST.cs, DMCompiler/Compiler/DM/DMLexer.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs, DMCompiler/Compiler/Lexer.cs
It was a bit of a mess, just a bit
=> Fix locations reporting

.github/workflows/compiler-test.yml, OpenDreamRuntime/Procs/ProcDecoder.cs
Turns out we never passed the correct arg and TG currently fails to disassemble.
=> Fix disassembler CI never failing on errors

OpenDreamRuntime/DreamMapManager.cs, OpenDreamRuntime/Objects/Types/DreamList.cs, OpenDreamRuntime/Objects/Types/DreamObjectArea.cs, OpenDreamRuntime/Objects/Types/DreamObjectTurf.cs
Adding a turf to an area's contents wouldn't remove it from its old area's contents. Fixing this fixes lavaland ruin generation on /tg/.
I also did some rewriting of map cells to make this code a little less fragile.
=> Remove a turf from an area's contents when it's added to another

OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/DreamManager.Connections.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Objects/Types/DreamObjectClient.cs, OpenDreamRuntime/Objects/Types/DreamObjectMob.cs
`mob.ckey = ...` was looping through every connection, and making the assumption that they were actively connected.
=> Fix a null reference in `mob.ckey` assignment

OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs
On my machine the `BasicReadAndWrite.dm` test would fail on subsequent runs. This was because after `fdel("savefile.sav")` executed the file would be recreated.
`Flush()` was calling `Resource!.Clear()` which calls `File.WriteAllText(_filePath, string.Empty);` which creates a new file.
Now we simply avoid flushing if the savefile file no longer exists.
=> Fix recreating deleted savefiles

Content.Tests/DMProject/Broken Tests/Expression/Constants/numeral_inf.dm, Content.Tests/DMProject/Tests/Expression/Constants/stringify_inf.dm, OpenDreamRuntime/DreamValue.cs
Some notes:
- The original unit test did not work in BYOND like... at all. Infinity is a number and only becomes `"inf"` when you try to stringify it.
- `-1#IND == 0` also doesn't pass in BYOND
- OS variation was fixed in BYOND at some point (can't be bothered to track down the build number). I confirmed I get the same result on both linux and windows.
Original test:
New test:
=> Fix stringifying infinity

OpenDreamRuntime/Procs/DllHelper.cs
I assure you people won't read the documentation about needing 64-bit DLLs.
Also makes the file not found error more explicit.
=> Explicitly remind people about 64-bit binaries in the DLL error

Content.IntegrationTests/DMProject/Tests/filter_initial.dm, Content.IntegrationTests/DMProject/code.dm, Content.IntegrationTests/DMProject/environment.dme, DMCompiler/DM/DMCodeTree.Vars.cs
Fixes #2120 
Surprisingly easy fix
=> Fix initial filter in object defs and adds test

Content.Tests/DMProject/Broken Tests/Procs/Arglist/initial.dm, Content.Tests/DMProject/Tests/Procs/Arglist/initial.dm, DMCompiler/DM/Expressions/Builtins.cs
Seems to just return the current value.
=> Implement `initial()` for `arglist()`

DMCompiler/DM/DMCodeTree.Vars.cs
Example:
```
Error OD0014 at code/modules/banners/__banner.dm:15:2: Duplicate definition of var "name_prefix"
Error OD0014 at code/game/objects/items/__item.dm:10:2: Previous definition of var "name_prefix"
```
Previously we only printed the first line. Printing both gives us parity with BYOND and is useful for fixing the error.
=> Emit location of original var def for duplicate var errors

Content.Tests/DMProject/Tests/Statements/For/reuse_decl_const.dm, Content.Tests/DMProject/Tests/Statements/For/reuse_decl_const2.dm, DMCompiler/DM/Builders/DMProcBuilder.cs, DMCompiler/DM/Expressions/LValue.cs
See included unit test for the issue this PR fixes. Previously, we only runtime errored whereas BYOND compiletime errored.
=> Compile error when outputting to const vars in `for()` loops

DMCompiler/Optimizer/PeepholeOptimizer.cs
Fixes #2130 
The `Math.Max()` didn't account for `i++` so `i` could never actually be `0` after the first iteration of the `for()` loop.
tl;dr off-by-one error
=> Fix off-by-one in peephole optimizer

DMCompiler/DM/DMProc.cs, DMCompiler/DMCompiler.cs, DMCompiler/Optimizer/BytecodeOptimizer.cs, DMCompiler/Optimizer/PeepholeOptimizer.cs
- Stops instantiating a `BytecodeOptimizer` class for every proc. One is now instantiated on `DMCompiler` and shared.
- `PeepholeOptimizer.GetOptimizations()` avoids allocating a huge list and instead just merges the first loop into the second.
- Removes `static` from the peephole optimizer. A single instance of the class is instantiated on the `BytecodeOptimizer`.
=> Optimize the peephole optimizer

Content.Tests/DMProject/Tests/Statements/extra_token_pragma.dm, Content.Tests/DMProject/Tests/Statements/thing_after_statement.dm, DMCompiler/Compiler/CompilerError.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm
Trailing `.` and `:` tokens after `if()` and `for()` statements is valid in BYOND:
We already handled `if():` so I just expanded our copium and fixed & extended a broken unit test in the process. Added the `ExtraToken` stylistic pragma for when this happens. No hits on TG/goon/para.
=> Cope with extra tokens after proc statements

DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/Optimizer/PeepholeOptimizations.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/ProcDecoder.cs
`PushReferenceValue -> PushString -> DereferenceIndex` is a pretty common pattern in TG. This combines them into one new `IndexRefWithString` opcode.
The new opcode occurs 6,170 times in TG. This means a pretty decent reduction in pushing/popping the stack.
I joined TG and confirmed it didn't seem to explode, and I could still run around.
=> `IndexRefWithString` peephole opt

DMDisassembler/Program.cs
This adds a `stats` command to the disassembler which can be extended to provide various info about the bytecode. For now I've added a `procs-by-type` argument which prints the number of proc declarations on each type in descending order.
I've also spruced up the `help` command with the ability to take a `command` argument to learn more about a specific command.
Here's an excerpt from TG:
```
Counting all proc declarations by type. This may take a moment.
Type: Proc Declarations
<global>: 1595
/datum/controller/global_vars: 979
/client: 504
/mob/living: 441
/atom: 359
/mob: 328
/mob/living/carbon: 184
/atom/movable: 131
/obj/item: 128
/mob/living/carbon/human: 101
```
=> Adds a system for printing stats to the disassembler

DMCompiler/DM/Builders/DMExpressionBuilder.cs
Fix more cases where inferredPath isn't passed. I checked and made sure it's valid in BYOND these places (even if it'd be nonsensical type-abused code like `var/obj/O = rgb(__IMPLIED_TYPE__ == /obj ? 255 : 0, 127, 127)`) too.
no Ike i'm not going to write unit tests for all of these, your goddamn unit test is "my Nebula PR not failing because of this" >:(
=> Fix more cases where inferredPath isn't passed

.github/workflows/lint.yml
should run the lint when you mark it as ready for review
note: needs testing because it's basically impossible to test git workflows?
=> Don't run lint on draft PRs

DMCompiler/Optimizer/PeepholeOptimizations.cs
`if()`/`else` blocks with a `return` in the `if()` are left with a dead `Jump` opcode that can never be reached. 
This peephole optimization deals with that and removes over 900 `Jump` opcodes from TG.
I tested that TG doesn't explode with these changes.
=> Remove `Jump` after `Return`

Content.Tests/DMProject/Tests/Regex/regex_find_replace.dm, OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs
This was subtly breaking DMM suite when there was a cell with more than one var-edited string var, which caused **one** tile to fail to load properly on goon and made the nuclear reactor control computer not work on devtest.
What a ride that was.
=> Fix off-by-one in regex replace and add test

OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamShared/Dream/ScreenLocation.cs
`LEFT`/`RIGHT`/`TOP`/`BOTTOM` are no longer the same as  `WEST`/`EAST`/`NORTH`/`SOUTH`
They take rendered icon size into account instead of the map's icon size.
Fixes tg's lobby menu
Partially addresses #1773, the icons aren't kept on the edge if the map's parent control is smaller than the map itself.
=> Implement the `screen_loc` edge anchors

.github/workflows/compiler-test.yml
Apparently writing "requires X" in a PR desc will make it try to pull that PR for the submodule, but it doesn't seem to work.
=> Remove the submodule dependencies thing

DMDisassembler/DMProc.cs, DMDisassembler/Program.cs
`stats opcode-count` will now print the number of occurrences of every opcode in a disassembly file.
Example from TG:
```
> stats opcode-count 
Counting all opcode occurrences. This may take a moment.
Opcode: Count
PushReferenceValue: 251,825
Call: 140,603
PushFloat: 119,568
Pop: 118,163
PushString: 110,316
JumpIfFalse: 106,655
AssignNoPush: 102,418
PushRefAndDereferenceField: 75,681
Jump: 64,159
DereferenceCall: 57,392
[snip]
```
I manually verified about 20 of them against the `.dmd` file with Notepad++'s `Count` and the numbers all matched.
Also changed `procs-by-type` to print commas in its output to make it easier to read.
=> Adds an opcode count stat to the disassembler

DMCompiler/Json/DreamProcJson.cs
I see no reason to allocate a morbillion classes on the heap for what could easily be structs. I don't have dotmemory anymore to measure the exact memory alloc reduction, but not allocating all of these classes will definitely be less memory.
Also converts `set;` to `init;` everywhere the IDE suggested, and fixed a warning for a missing `Equals()`.
Tested that TG doesn't explode with these changes.
=> Convert some ProcJson classes to structs

OpenDreamClient/Interface/DummyDreamInterfaceManager.cs
We needed to acknowledge the load interface network message before the player was joined to the game
=> Fix integration test not creating a client

DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/Compiler/DM/AST/DMAST.ProcStatements.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Builders/DMProcBuilder.cs, DMCompiler/DM/DMProc.cs, DMCompiler/DMStandard/UnsortedAdditions.dm, OpenDream.sln.DotSettings, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/DreamManager.Connections.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamShared/Network/Messages/MsgLink.cs
Implements enough of `link()` to allow opening website links on a client's machine. This allows the github, forum, and other buttons that most SS13 codebases have to work.
Fixes #193
=> Implement `usr << link()`

OpenDreamClient/Interface/DreamStylesheet.cs, OpenDreamClient/Interface/Prompts/ListPrompt.cs, OpenDreamClient/Interface/Prompts/TextPrompt.cs, TestGame/code.dm
Title. Makes them look like what they would look on windows and adds a generic input() test for testgame
does not include style (drop shadow box) for TextEdit
=> update input() style

OpenDreamClient/Interface/DreamInterfaceManager.cs
In BYOND, calling `link()` with a `byond://` server address will cause the client to connect to that server. Similarly, we now support connecting to other RT/SS14 servers via `ss14://` and `ss14s://`
Note that you _must_ join the initial game via the SS14 launcher for server hop (redial) to work; RT doesn't allow it from e.g. your dev TestGame server that you connected to directly from the client.
https://github.com/user-attachments/assets/f1639e50-e7df-4d0b-a3e3-8ae6736a3541
=> Server hop support in `link()`

OpenDream.sln.DotSettings
Disable the lint that triggers on this:
```cs
if (...)
return 1;
else
return 2;
```
=> Disable the ConvertIfStatementToConditionalTernaryExpression lint

DMCompiler/Compiler/DM/AST/DMAST.ObjectStatements.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Builders/DMCodeTreeBuilder.cs
=> Fix var blocks creating an empty type named `var`

DMCompiler/Compiler/DM/AST/DMAST.ObjectStatements.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Builders/DMCodeTreeBuilder.cs
Fixes these two scenarios:
```dm
/type { }
```
```dm
/type {; a = b}
```
=> Fix empty braced object blocks and add null object statements

OpenDreamClient/Interface/Descriptors/InterfaceDescriptor.cs
`winclone()` was failing because lookup was failing because we were using `Name` instead of `Id` for the search.
=> Fix text box on goon by fixing element lookup

OpenDreamClient/Input/ContextMenu/VerbMenuPopup.xaml.cs
Redundant check that makes it impossible to _ever_ apply a verb to the mob it came from. Unless there's multiple arguments I guess?
Just the target type check is fine. I think.
=> Fix self-targeting verbs

DMCompiler/DM/DMCodeTree.Vars.cs, DMCompiler/DM/DMObject.cs
This code now correctly sets `/a/b`'s var to `null`:
```dm
/a
var/foo = list(1, 2)
/a/b
foo = null
```
It was previously kept as `list(1, 2)` because the init proc was left as-is.
=> Fix overriding runtime-initialized vars with constants

OpenDreamClient/Interface/DebugWindows/IconDebugWindow.xaml.cs, OpenDreamClient/Interface/Html/HtmlParser.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamClient/Rendering/MapTextRenderer.cs, OpenDreamRuntime/Objects/Types/DreamObjectMovable.cs
Maptext is now run through our HTML parser and does rendering similar to RT's rich text. There is still plenty left in the way of CSS support, but this gets a reasonable result.
=> Rich text rendering and HTML parsing for maptext

OpenDreamClient/Interface/Html/HtmlParser.cs, OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs
OnNewAppearance no longer initializes an appearance if the MsgAllAppearances hasn't been received yet.
I also made some logs less spammy.
=> Fix an error in `OnNewAppearance()`

OpenDreamClient/Rendering/ClientAppearanceSystem.cs
This was causing issues if an appearance had overlays that in turn had overlays that hadn't been loaded yet.
Should finally fix Goonstation rejoining.
=> Make overlay-resolves and load-callbacks separate passes

OpenDreamClient/Rendering/DreamPlane.cs
Mouse map rendering was using `GetTexture()` which will do a full re-render of a sprite if it's more complicated. We already keep a reference to the texture drawn in the current frame, so use that instead.
This also allows less calls to `UseShader()` since GetTexture was sometimes changing the shader.
=> Avoid full-rendering sprites a second time in the mouse map

OpenDreamClient/Rendering/DMISpriteSystem.cs, OpenDreamClient/Rendering/DreamViewOverlay.TileVisibility.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs
On my less-powerful laptop this shaves off many milliseconds on most frames. It also saves on kilobytes of memory allocations per frame.
=> Avoid recalculating tile visibility when nothing is changing

DMCompiler/Compiler/CompilerError.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/DMCompiler.cs, DMCompiler/DMStandard/DefaultPragmaConfig.dm
Doing `#define FILE_DIR "nonexistent/folder/"` would cause the compiler to crash when a resource tried to resolve its path. Now it is ignored and emits an `InvalidFileDirDefine` warning.
=> Fix a crash with invalid `FILE_DIR` defines

DMCompiler/DMStandard/UnsortedAdditions.dm
it is, we've got a test for it and everything
=> mark `issaved()` as implemented

DMCompiler/DMStandard/Types/Sound.dm, OpenDreamClient/Audio/DreamSoundEngine.cs, OpenDreamClient/Audio/IDreamSoundEngine.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamShared/Network/Messages/MsgSound.cs
https://www.byond.com/docs/ref/#/sound/var/offset
https://github.com/OpenDreamProject/OpenDream/issues/2194
Tested it to confirm it works. Didn't test what BYOND does when given non-numbers.
=> Implement `/sound.offset`

.github/workflows/compiler-test.yml, Content.Tests/DMProject/Tests/Builtins/sign.dm, DMCompiler/DMStandard/_Standard.dm, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
https://www.byond.com/docs/ref/#/proc/sign
=> Implement `sign()`

Content.Tests/DMProject/Tests/Builtins/astype.dm, DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/Compiler/DM/AST/DMAST.ExpressionBinary.cs, DMCompiler/Compiler/DM/AST/DMAST.ExpressionUnary.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Builders/DMExpressionBuilder.cs, DMCompiler/DM/DMProc.cs, DMCompiler/DM/Expressions/Builtins.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs
https://www.byond.com/docs/ref/#/proc/astype
=> Implement `astype()`

DMCompiler/DM/DMObjectTree.cs, DMCompiler/DMStandard/Types/Vector.dm, DMCompiler/DMStandard/_Standard.dm, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Objects/Types/DreamObjectVector.cs, OpenDreamRuntime/Procs/DreamProcArguments.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
An initial implementation of `/vector` that supports all its vars and `json_encode(vector)`. Currently doesn't include anything for operators, procs, or for loops.
=> Initial vector implementation

OpenDreamClient/Interface/Controls/ControlLabel.cs
* Panel styling like background color
* Text color
* Text alignment
=> Add support for more label styling

Content.Tests/DMProject/Tests/Builtins/params2list.dm, Content.Tests/DMProject/Tests/List/AssocListCombine.dm, Content.Tests/DMProject/Tests/List/ListCut.dm, Content.Tests/DMProject/Tests/Operators/equivalence.dm, OpenDreamRuntime/Objects/Types/DreamList.cs
=> Implement 516 behavior for `~=` and `~!`

Content.Tests/DMProject/Tests/Builtins/values_cut.dm, Content.Tests/DMProject/Tests/Builtins/values_dot.dm, Content.Tests/DMProject/Tests/Builtins/values_product.dm, Content.Tests/DMProject/Tests/Builtins/values_sum.dm, DMCompiler/DMStandard/_Standard.dm, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Implements:
- `values_dot()` - https://www.byond.com/docs/ref/#/proc/values_dot
- `values_product()` - https://www.byond.com/docs/ref/#/proc/values_product
- `values_sum()` - https://www.byond.com/docs/ref/#/proc/values_sum
- `values_cut_under()` - https://www.byond.com/docs/ref/#/proc/values_cut_under
- `values_cut_over()` - https://www.byond.com/docs/ref/#/proc/values_cut_over
=> Implement 516 `values_` procs

OpenDreamClient/Input/MouseInputSystem.cs, OpenDreamClient/Rendering/ClientScreenOverlaySystem.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamShared/Dream/MouseOpacity.cs
Don't render maptext if it's empty or whitespace.
Fixes backpack items being unclickable on Paradise, though not by fixing the core issue. A second render, maptext, was resetting LastRenderedTexture.
=> Avoid rendering an empty maptext

Content.Tests/DMProject/Tests/Builtins/lerp.dm, DMCompiler/DMStandard/_Standard.dm, OpenDreamRuntime/DreamValue.cs, OpenDreamRuntime/Procs/Native/DreamProcNative.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Implements `lerp()` for nums. Other arg types like vectors are a future PR's problem.
=> Partial `lerp()` implementation

OpenDreamClient/Rendering/DreamViewOverlay.cs
RobustToolbox now keeps the shader as part of `RenderInRenderTarget()`'s state. This means once `RenderInRenderTarget()` returns, the old shader is put back. This unveiled a bug in our renderer that would reuse the old shader for the final render of a plane.
This fixes the dark HUD on Paradise.
=> Reset shader before final plane render

OpenDreamClient/Rendering/DreamViewOverlay.cs
Overlays/Underlays on a different plane than their parent atom are treated as having the `KEEP_APART` flag.
Fixes overlay lights on /tg/ from just applying a bright image. They still don't work, the plane they're rendered onto isn't having any effect. /tg/'s documentation implies that the plane should render onto the game plane, though the game plane is much higher than the overlay lighting plane so I have no idea how that's supposed to be the case.
The lighting plane _is_ supposed to be masked by the overlay lighting plane, which would produce an effect. But the plane's filters don't seem to be applying.
=> Overlays on a different plane are `KEEP_APART`

OpenDreamClient/Rendering/DreamViewOverlay.cs
When sorting sprites, try to keep sprites with the same icon resource grouped together. This causes sprites with the same texture to render together which RT batches more efficiently.
=> Group sprite renders by icon

OpenDreamClient/Rendering/DreamViewOverlay.cs
These vis contents weren't rendering because they weren't attached to the map.
Was the last issue keeping tg's parallax from working.
=> Fix vis_contents not working on screen objects

OpenDreamClient/Audio/DreamSoundEngine.cs, OpenDreamClient/Resources/DreamResourceManager.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs
The server now uses MD5 hashes to help prevent creating exact copies of DMIs generated with `/icon`. This saves ~10MB during /tg/ init alone in resources that would have to be sent to the client otherwise.
=> Avoid creating duplicate icon resources

OpenDreamPackaging/DreamPackaging.cs, OpenDreamRuntime/DreamAczProvider.cs, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs
Allows resources created at runtime (like `/icon`) to be downloaded by the launcher. This makes for a nicer experience than downloading them after connecting while sitting on a blank screen. Also means not downloading them again if you reconnect.
=> Include runtime-generated resources in ACZ

OpenDreamClient/Input/ContextMenu/ContextMenuItem.xaml.cs, OpenDreamClient/Input/ContextMenu/ContextMenuPopup.xaml.cs, OpenDreamClient/Rendering/DMISpriteComponent.cs, OpenDreamClient/Rendering/DMISpriteSystem.cs, OpenDreamClient/Rendering/DreamIcon.cs, OpenDreamClient/Rendering/DreamPlane.cs, OpenDreamClient/Rendering/DreamViewOverlay.TileVisibility.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamShared/Dream/DreamFilter.cs
* ProcessSprites ignores sprites outside the viewport's AABB, greatly reducing the time processing & rendering them
* Ping-Pong rendering now only uses the minimum necessary texture size, reducing the amount of work done
* Objects with render targets now render to a texture the size of their DMI frames, rather than the size of the whole viewport
* Avoid duplicating blend mode shaders when the parameters are the default, reducing allocations and greatly improving RT's batching
* Avoid unnecessarily clearing render targets, reducing RT's render command flushing
* Appearances with simple colors (not a color matrix) no longer do a ping-pong render
On my laptop, goes from ~22FPS observing on /tg/ to ~55FPS.
=> Rendering optimizations

Content.Tests/DummyDreamMapManager.cs, OpenDreamRuntime/DreamManager.Connections.cs, OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/Map/DreamMapManager.cs, OpenDreamRuntime/Objects/Types/DreamObjectWorld.cs, OpenDreamRuntime/Resources/DreamResource.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs
/tg/ must request `world.tick_usage` a bajillion times or something, because it spends 6.5 seconds of init on it:
I swapped it from using RT's `IGameTiming.RealTime` stopwatch to `Environment.TickCount64` which is performing much better:
=> Optimize `world.tick_usage`

Content.Tests/DMProject/Tests/Loop/ForAssoc.dm, DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/DM/Builders/DMProcBuilder.cs, DMCompiler/DM/DMProc.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/DreamEnumerators.cs, OpenDreamRuntime/Procs/ProcDecoder.cs
https://www.byond.com/docs/ref/#/proc/for/list
=> Implement `for(k,v in L)` syntax

DMCompiler/DMStandard/Types/Atoms/_Atom.dm, DMCompiler/DMStandard/Types/Client.dm, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/Input/MouseInputSystem.cs
https://github.com/OpenDreamProject/OpenDream/issues/2194
Implements `DblClick()` for `/client` and `/atom`. This enables ghosts to jump to turf or orbit things on Paradise:
https://github.com/user-attachments/assets/f88812a7-584c-464e-9b4d-7123cfc99f17
=> Implement `DblClick()`

DMCompiler/Compiler/DM/DMLexer.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/Compiler/DM/DMParserHelper.cs, DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs, DMCompiler/Compiler/Lexer.cs, DMCompiler/Compiler/Parser.cs
i think it's fair enough to let consumers use these so i can crawl the ast for https://github.com/OpenDreamProject/od-dm-reference and like language servers in the future. and other things
=> public compiler/lexer/preproc

Content.Tests/DMProject/Tests/Procs/final_proc.dm, Content.Tests/DMProject/Tests/Procs/final_proc2.dm, Content.Tests/DMProject/Tests/Procs/final_proc3.dm, DMCompiler/Compiler/DM/AST/DMAST.ObjectStatements.cs, DMCompiler/DM/DMCodeTree.Procs.cs, DMCompiler/DM/DMProc.cs
Resolves #2160
Only difference from BYOND afaict is that I put both proc declaration locations in 1 error message instead of emitting 2 separate errors.
=> Implement `/proc/final/`

OpenDreamClient/Interface/Controls/ControlInfo.cs, OpenDreamClient/Interface/Controls/ControlOutput.cs
By default, text-color is being read from the .DMF file, but not being applied in parts of the UI, even though background color is.
This is problematic when the background color is dark, as text-color defaults to black.
This PR makes the UI system correctly apply text-color as well.
=> Fixes DMF text-color not applying to statpanel / output

DMCompiler/DMCompiler.cs, OpenDreamRuntime/Resources/DreamResourceManager.cs
The way the DMF is loaded by the server was changed and caused the hybrid-acz assumptions to break because an extra resource was loaded before the rest. The DMF is now loaded under the same process as the rest of the resources.
=> Fix an always-tripped debug assert

OpenDreamClient/Interface/DMF/DMFLexer.cs
Fixes Daedalus' DMF parsing. It had `splitter = 94.9`.
=> Allow float DMF values

DMCompiler/Optimizer/BytecodeOptimizer.cs
Only create a dictionary when necessary, which reduces the number of dicts allocated by ~150k.
Also avoids/short circuits the last instruction enumeration whenever it won't do anything.
=> Optimize `RemoveUnreferencedLabels()`

DMCompiler/DM/Expressions/Builtins.cs
this allows chained astype expressions to work, such as this: `return astype(owner, /datum/mind)?.current`
=> Properly assign return type for `astype`

OpenDreamPackageTool/ServerPackaging.cs
Didn't test this after changing the import resolver to use `AppContext.GetData("NATIVE_DLL_SEARCH_DIRECTORIES")`, which apparently does not include the `runtimes/` folder after OD is packaged with `Robust.Server`.
=> Fix the location of the byondapi library in linux releases

OpenDreamClient/Interface/DebugWindows/MacrosWindow.cs
For when your game has many, many macros
Also shuffles the execute button to the left to prevent the need to horizontally scroll on a large macro
=> Make macros in showmacros tables scrollable

Content.Tests/DMProject/Tests/Preprocessor/Include/duplicate_include.dm, DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs
Just needed to parse out the path operator.
Fixes #2283
=> Duplicate `#include` fix

.github/workflows/build-test.yml, Content.Tests/DMTests.cs, DMCompiler/DMCompiler.cs, DMCompiler/Optimizer/BytecodeOptimizer.cs, DMCompiler/Program.cs
Resolves #1377 
Adds a `--no-opts` compiler arg which prevents the BytecodeOptimizer from running. The compiler will emit a forced warning when this happens.
CI also now reruns all unit tests with `--no-opts` after the initial test run passes.
The second commit intentionally causes CI to fail if `--no-opts` is used just to ensure the CI actually works.
=> Add a compiler arg to disable optimizations

DMCompiler/DM/DMCodeTree.Vars.cs
This code currently errors on master:
```
/datum/foo
var/alist/preference_settings_client = alist()
```
`Error OD0011 at code.dm:354:41: Invalid initial value for "preference_settings_client"`
This PR fixes that.
=> Fix `alist()` in obj definitions

Content.Tests/DMProject/Tests/Operators/bitshift_large.dm, Content.Tests/DMProject/Tests/Operators/valid_and_null_assign_const.dm, Content.Tests/DMProject/Tests/Operators/valid_and_null_const.dm, DMCompiler/DM/Expressions/Binary.cs, DMCompiler/Optimizer/PeepholeOptimizations.cs, DMCompiler/SharedOperations.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
BYOND zeros out the top 8 bits after a bit shift because everything is a 32 bit float
This modifies our `<<`, `>>`, and `<<=`, `>>=` operators to do that too
=> Fix bit-shift operators to match BYOND

Content.Tests/DMProject/Tests/Builtins/callee.dm, DMCompiler/Bytecode/DMReference.cs, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Builders/DMExpressionBuilder.cs, DMCompiler/DM/DMObjectTree.cs, DMCompiler/DM/DMProc.cs, DMCompiler/DM/Expressions/LValue.cs, DMCompiler/DMStandard/Types/Callee.dm, DMCompiler/DMStandard/_Standard.dm, DMCompiler/DreamPath.cs, DMCompiler/Optimizer/AnnotatedByteCodeWriter.cs, DMCompiler/Optimizer/AnnotatedBytecodeSerializer.cs, OpenDreamRuntime/DreamThread.cs, OpenDreamRuntime/Objects/DreamObject.cs, OpenDreamRuntime/Objects/DreamObjectTree.cs, OpenDreamRuntime/Objects/Types/DreamObjectCallee.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
`caller` also compiles now, but the runtime always gives `null`.
=> Implement `callee`

.github/workflows/compiler-test.yml, DMCompiler/DMCompiler.cs
We've introduced some of 516's breaking changes, like render_source anchoring to the bottom left instead of the center. I think it makes sense at this point to make this our version.
=> Update default `DM_VERSION` and `DM_BUILD` to 516.1655

OpenDreamClient/Input/MouseInputSystem.cs, OpenDreamClient/Interface/Controls/ControlMap.cs, OpenDreamClient/Interface/DreamInterfaceManager.cs, OpenDreamClient/Interface/DummyDreamInterfaceManager.cs, OpenDreamClient/Rendering/AtomGlideSystem.cs, OpenDreamClient/Rendering/ClientAppearanceSystem.cs, OpenDreamClient/Rendering/DMISpriteSystem.cs, OpenDreamClient/Rendering/DreamIcon.cs, OpenDreamClient/Rendering/DreamPlane.cs, OpenDreamClient/Rendering/DreamViewOverlay.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/Objects/DreamIcon.cs, OpenDreamRuntime/Objects/Types/DreamObjectIcon.cs, OpenDreamRuntime/Objects/Types/DreamObjectMovable.cs, OpenDreamRuntime/Objects/Types/DreamObjectWorld.cs, OpenDreamShared/Network/Messages/MsgUpdateClientInfo.cs
You can now set `world.icon_size` to values other than 32.
Paradise on 16, for example:
=> Implement integer `world.icon_size` values

DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/Optimizer/CompactorOptimizations.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/ProcDecoder.cs
This is the 8th most common opcode pattern in Paradise:
`PushFloat -> AssignNoPush`
It's essentially every time there is a wall of vars assigned float values:
```
engine = 1
hull = 1
electronics = 1
```
This PR adds a new optimization:
```csharp
// PushFloat [float]
// AssignNoPush [ref]
// -> PushFloatAssign [float] [ref]
// or if there's multiple
// -> NPushFloatAssign [count] [float] [ref] ... [float] [ref]
```
The new opt happens ~13.8k times on Paradise, about 600 of which are `NPushFloatAssign`
=> `PushFloatAssign` Optimization

OpenDreamRuntime/DreamManager.cs, OpenDreamRuntime/Objects/Types/DreamList.cs, OpenDreamShared/OpenDreamCVars.cs
Keep a list to reuse later if it can hold at least ~~2048~~ a configurable amount of elements. Paradise was using `block()` to grab a large list of turfs thousands of times during init, allocating gigabytes. This optimizes that.
=> Reuse large lists

OpenDreamRuntime/Objects/Types/DreamObjectRegex.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Fixes https://github.com/OpenDreamProject/OpenDream/issues/1785
Using a `/regex` in `findtext()` would not update the regex object's vars. Now it does.
The original issue was slightly misleading, this was the real root cause. I tested that there is no more maploader runtime spam in daedalus.
=> Fix various `/regex` vars not being updated when used in `findtext()`

DMCompiler/Bytecode/StringFormatEncoder.cs, DMCompiler/Compiler/DM/DMParserHelper.cs, DMCompiler/DM/DMProc.cs, OpenDreamClient/Interface/Controls/ControlOutput.cs, OpenDreamClient/Interface/Controls/UI/AppearanceControl.cs, OpenDreamClient/Interface/Controls/UI/OutputControl.cs, OpenDreamClient/Interface/Html/HtmlParser.cs, OpenDreamClient/Interface/Html/Tags/TagIcon.cs, OpenDreamClient/Rendering/DreamIcon.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamShared/Dream/StringFormatting.cs
Allows inlining an atom's icon anywhere you can use HTML in the DMF
Examples from Exadv1's Console:
=> Implement `"\icon[atom]"`

OpenDreamRuntime/Procs/ProcDecoder.cs
Fixes disassembling procs with `alist(...)`
=> Fix disassembling `CreateStrictAssociativeList`

Content.Tests/DMProject/Tests/Statements/extra_token_lookahead.dm, DMCompiler/Compiler/DM/DMParser.cs
Closes #2233
Syntax seen in the wild at https://github.com/Baystation12/Baystation12/blob/b51d6e29b2301b6c81bebb997f009f11b3e7dc16/packs/deepmaint/generator/jp_dungeon_gen.dm#L138
=> Lookahead in front of extra tokens to determine consumption

DMCompiler/Bytecode/DMReference.cs, DMCompiler/Bytecode/DreamProcOpcode.cs, DMCompiler/DM/Builders/DMProcBuilder.cs, DMCompiler/DM/DMProc.cs, OpenDreamRuntime/DreamReference.cs, OpenDreamRuntime/Objects/Types/DreamAssocList.cs, OpenDreamRuntime/Objects/Types/DreamList.cs, OpenDreamRuntime/Objects/Types/IDreamList.cs, OpenDreamRuntime/Procs/DMOpcodeHandlers.cs, OpenDreamRuntime/Procs/DMProc.cs, OpenDreamRuntime/Procs/DreamEnumerators.cs
Fix #2360
Fix #2361
Creating a list enumerator now copies that list's associated values, if it has any. The EnumerateNoAssign opcode also no longer uses a DreamReference to grab the list, removing the need for an LValue.
Potentially room for optimization here, as always copying the associated values regardless of loop type is a bit much. Trying to get goonstation compiling again though.
=> Fix some issues with key-value loops

OpenDreamRuntime/AtomManager.cs, OpenDreamRuntime/ByondApi/ByondApi.Functions.cs, OpenDreamRuntime/DreamConnection.cs, OpenDreamRuntime/Objects/Types/DreamList.cs, OpenDreamRuntime/Objects/Types/DreamObjectAtom.cs, OpenDreamRuntime/Objects/Types/DreamObjectClient.cs, OpenDreamRuntime/Objects/Types/DreamObjectFilter.cs, OpenDreamRuntime/Objects/Types/DreamObjectImage.cs, OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs, OpenDreamRuntime/Objects/Types/DreamObjectTurf.cs, OpenDreamRuntime/Procs/DebugAdapter/DreamDebugManager.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeList.cs, OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
#2363 broke list enumeration on special lists because it started enumerating on `DreamList`'s internal `_values` array which special lists don't use.
I moved every `GetValues()` implementation to `EnumerateValues()` instead, as a step towards making every list implement IDreamList instead of inheriting DreamList.
=> Fix `for(var/V in list)` for special lists

OpenDreamRuntime/Procs/ProcDecoder.cs
Fixes disassembling opcodes produced by `for (var/key,value in list)`. Changes to the opcode weren't reflected in the decoder.
Recent changes to /tg/ were triggering an error because of this.
=> Fix decoding the `EnumerateAssoc` opcode

Content.Tests/DMProject/Tests/Call/call_no_params.dm, Content.Tests/DMProject/Tests/Dereference/deref_no_ident.dm, Content.Tests/DMProject/Tests/Procs/pick_no_arg.dm, Content.Tests/DMProject/Tests/SetStatements/no_identifier.dm, Content.Tests/DMProject/Tests/Statements/ControlFlow/goto_no_label.dm, Content.Tests/DMProject/Tests/Statements/ControlFlow/trycatch_no_body.dm, Content.Tests/DMProject/Tests/Statements/Switch/no_cases.dm, Content.Tests/DMProject/Tests/Statements/Switch/no_expression.dm, Content.Tests/DMProject/Tests/Statements/Switch/no_upper_limit.dm, Content.Tests/DMProject/Tests/Statements/While/do_while_no_body1.dm, Content.Tests/DMProject/Tests/Statements/While/do_while_no_body2.dm, Content.Tests/DMProject/Tests/Statements/While/while_no_body.dm, Content.Tests/DMProject/Tests/Tree/upward_search_no_path.dm, DMCompiler/Compiler/DM/DMParser.cs, DMCompiler/DM/Builders/DMProcBuilder.cs
- Add a bunch of random tests to improve codecov
- Fix a few cases where error handling would actually result in additional parser errors
- Improve the wording of some errors to be more accurate
- Fix a parity break in switch cases. `switch(foo) if()` is effectively a no-op AFAICT; it is not equivalent to `if(null)` nor `if("")`. We were treating it as an error; I converted it to a pragma.
- Fix a parity break in path search:
=> Misc DMParser Tests & Fixes

DMCompiler/DMStandard/Types/World.dm
think this was just an oversight since it is very implemented
=> mark `/world/Error()` as implemented
