- OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
Fixes #11 
Not sure if there's other chars I should add.
> Ignore spaces after multiline comments

- DMCompiler/DM/Visitors/DMASTSimplifier.cs
Dipping my toes into DMASTSimplifier.
> Implement spawn, goto, and label simplifiers

- OpenDreamClient/Interface/Elements/ElementInfo.cs
- OpenDreamClient/Interface/InterfaceHelpers.cs
- OpenDreamClient/Interface/Prompts/NumberPrompt.cs
- OpenDreamClient/Net/ClientConnection.cs
- OpenDreamClient/Renderer/DreamRenderer.cs
- OpenDreamClient/Renderer/SharpGLControl.cs
Commit messages explain the changes, just small tweaks.
Mainly just null propagation and switch expressions again.
Avoiding the empty array allocation like before.
> small client tweaks

- DMCompiler/DM/DMObject.cs
- DMCompiler/DM/DMObjectTree.cs
- DMCompiler/DM/DMProc.cs
- DMCompiler/DM/Visitors/DMASTSimplifier.cs
- DMCompiler/DM/Visitors/DMVisitorObjectBuilder.cs
- DMCompiler/DM/Visitors/DMVisitorProcBuilder.cs
- DMCompiler/Program.cs
each commit details the tweaks, just small stuff
* Fixed typo
* Did some null propagation and checks
* Index from end expressions vs manual length decrease
> Small compiler tweaks

- OpenDreamClient/Interface/DreamInterface.cs
- OpenDreamClient/Interface/Prompts/MessagePrompt.cs
- OpenDreamClient/Interface/Prompts/NumberPrompt.cs
- OpenDreamClient/Interface/Prompts/PromptWindow.cs
- OpenDreamClient/Interface/Prompts/TextPrompt.cs
- OpenDreamServer/Dream/Procs/DreamProcInterpreterOpcodes.cs
- OpenDreamServer/Net/DreamConnection.cs
- OpenDreamShared/Net/Packets/PacketPrompt.cs
- TestGame/code.dm
If not set, defaults to `OpenDream` for the Titles.
~~Still trying to figure out how to implement it on `Prompt`'s creators.~~
> Prompt window Title setting

- DMCompiler/DMStandard/_Standard.dm
- OpenDreamServer/Dream/Procs/Native/DreamProcNative.cs
- OpenDreamServer/Dream/Procs/Native/DreamProcNativeRoot.cs
- TestGame/code.dm
Since md5() can take a file or a text we first try to load the arg as a file converted to a string (largely copying file2text), then if that's null we just hash the arg string directly.
> Implements md5()

- DMCompiler/copy_standard.bat
This allows IDEs like Rider to execute it in the build process, as an external tool.
> Adds a batch script to copy DMStandard to the bin

- DMCompiler/DMStandard/Types/World.dm
> "Implements" world/Repop()

- OpenDreamServer/Dream/Objects/DreamList.cs
- OpenDreamServer/Dream/Objects/DreamObject.cs
- TestGame/code.dm
I think this is all that was needed?
according to http://www.byond.com/docs/ref/#/datum/var/vars
> implements GetValues() for datum.vars list

- DMCompiler/DMStandard/_Standard.dm
- OpenDreamServer/Dream/Procs/Native/DreamProcNative.cs
- OpenDreamServer/Dream/Procs/Native/DreamProcNativeRoot.cs
Rewritten in C#, tell me if you'd rather I kept it in DM.
https://secure.byond.com/docs/ref/#/proc/oviewers
Closes: #83
> Adds oviewers() implementation

- DMCompiler/DMStandard/_Standard.dm
- OpenDreamServer/Dream/Procs/Native/DreamProcNative.cs
- OpenDreamServer/Dream/Procs/Native/DreamProcNativeRoot.cs
Took me a while to debug due to well I didnt know OD would freak out with verbs as the same name of the proc
> Implement ArcSin

- OpenDreamServer/Dream/Objects/DreamList.cs
> Adds support for the null index in DreamLists

- OpenDreamServer/Dream/DreamValue.cs
> Revert "Eliminates boxing on equality for DreamValue"

- DMCompiler/DMStandard/Types/World.dm
- OpenDreamServer/Dream/Objects/MetaObjects/DreamMetaObjectWorld.cs
- OpenDreamServer/Net/DreamServer.cs
- OpenDreamServer/Program.cs
No setting yet - plan to do setting of port/address via DreamServer arguments in separate PR
> Adds world.address/port/url implementation

- OpenDreamServer/Dream/Objects/DreamObject.cs
- OpenDreamServer/Resources/DMMParser.cs
- OpenDreamShared/Compiler/DM/DMLexer.cs
- OpenDreamShared/Compiler/DM/DMParser.cs
- OpenDreamShared/Compiler/DMF/DMFParser.cs
- OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
title, also makes purposefully empty statements more clear with blocks.
> Removes some empty statements

- OpenDreamShared/Dream/IconAppearance.cs
> fixes typo in "fuchsia"

- DMCompiler/DMStandard/Types/World.dm
- OpenDreamRuntime/DreamRuntime.cs
- TestGame/code.dm
Not sure if this is the best way to handle it, but it seems to work.
Fixes #78
> Adds `world.cpu`

- .github/workflows/compiler-test.yml
Compiles modified TG at the end of unit testing. See https://github.com/wixoaGit/tgstation
> Add TG to the CI

- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> Decompressed arcsin but without a merge conflict

- README.md
> Adds the discord to the readme

- DMCompiler/DM/Expressions/Binary.cs
- DMCompiler/DM/Visitors/DMVisitorExpression.cs
- OpenDreamShared/Compiler/DM/DMAST.cs
- OpenDreamShared/Compiler/DM/DMParser.cs
> Implements `%=`

- DMCompiler/DM/DMProc.cs
- DMCompiler/DM/Expressions/Builtins.cs
- DMCompiler/DM/Expressions/Dereference.cs
- DMCompiler/DM/Expressions/LValue.cs
- DMCompiler/DM/Visitors/DMVisitorExpression.cs
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
- OpenDreamRuntime/Procs/DMProc.cs
- OpenDreamShared/Compiler/DM/DMAST.cs
- OpenDreamShared/Compiler/DM/DMParser.cs
- OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
Fixes #75 
This is largely a copypaste of `Initial()` so let me know if any code is unnecessary.
Doesn't support `var/const` or `var/tmp`.
> Adds `issaved()`

- DMCompiler/DM/Visitors/DMVisitorExpression.cs
> Fix empty `[]`

- DMCompiler/DMStandard/Defines.dm
- DMCompiler/DMStandard/Types/Atoms/Mob.dm
See title.
See https://github.com/wixoaGit/OpenDream/issues/77 and  https://github.com/wixoaGit/OpenDream/issues/72
> Placeholder `var/sight` and `var/see_in_dark`

- .gitignore
So that you can compile with dream maker and not have to worry about accidentally committing them
> Added byond compiler output files to gitignore

- DMCompiler/DM/DMProc.cs
- DMCompiler/DM/Visitors/DMVisitorProcBuilder.cs
**Disclaimer: I have no idea if this works.**
I have not actually tested this with sample DM code.
> Implement goto and label in DMVisitorProcBuilder and DMProc

- OpenDreamShared/Compiler/DM/DMLexer.cs
See http://www.byond.com/docs/ref/#/DM/text/macros
Fixes https://github.com/wixoaGit/OpenDream/issues/140
> Adds missing valid escapes

- DMCompiler/DMStandard/Types/Client.dm
- OpenDreamRuntime/DreamRuntime.cs
- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectClient.cs
Closes #184 
According to the docs the value is null until the handshake is done: http://www.byond.com/docs/ref/#/client/var/connection
> Adds client/connection

- DMCompiler/DMStandard/_Standard.dm
- OpenDreamRuntime/Procs/Native/DreamProcNative.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Closes #187
Do you want tests for these?
> Implemented hascall()

- OpenDreamRuntime/DreamRuntime.cs
Also pre-allocates a capacity of 1.
> Makes AtomToAppearance a regular dictionary

- DMCompiler/DMStandard/_Standard.dm
> Implemented step_rand and get_step_rand

- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMovable.cs
Fixes #178 
Also converts elseif chains to switches.
> Adds initial `locs` support

- DMCompiler/DMStandard/_Standard.dm
> Adds placeholder `ohearers()`

- OpenDreamClient/Dream/DreamStateManager.cs
- OpenDreamClient/OpenDream.cs
- OpenDreamClient/Renderer/DreamRenderer.cs
- OpenDreamRuntime/DreamStateManager.cs
- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs
- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMob.cs
- OpenDreamShared/Dream/DreamDeltaState.cs
- OpenDreamShared/Dream/DreamFullState.cs
- OpenDreamShared/Net/Packets/PacketDeltaGameState.cs
- OpenDreamShared/Net/Packets/PacketFullGameState.cs
> Implements actual invisibility

- OpenDreamClient/Interface/Controls/ControlMap.cs
- OpenDreamClient/Interface/DreamInterface.cs
- OpenDreamClient/Renderer/DreamRenderer.cs
Correct me if I'm wrong, but `HasFlag()` uses boxing, which is slow.
> Removes every `HasFlag()`

- DMCompiler/Program.cs
Just mentions the DME name when you start compiling and mentions how long it takes
> Adds some basic info to the console when compiling

- Content.Server/DM/AsyncNativeProc.cs
- Content.Server/DM/DMOpcodeHandlers.cs
- Content.Server/Dream/NativeProcs/DreamProcNative.cs
- Content.Server/Dream/NativeProcs/DreamProcNativeWorld.cs
- DMCompiler/DMStandard/Types/World.dm
Also `world.Export()` since I wanted it to test with.
> [Robust] Implement AsyncNativeProc yielding.

- OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessor.cs
It's really annoying having to do this every time I want to mess with a real codebase. Tested and working.
> Implements placeholder `#if`

- DMCompiler/DMStandard/Defines.dm
- DMCompiler/DMStandard/Types/Regex.dm
- OpenDreamRuntime/Procs/Native/DreamProcNative.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Closes #274
It's weird but that's how BYOND does it
> Implemented REGEX_QUOTE, REGEX_QUOTE_REPLACEMENT

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Solves a lot of exceptions running NTstation
> CreateObject now attempts to convert a string to a path

- DMCompiler/DMStandard/Defines.dm
Closes #177 
It was surprisingly easy.
> Implements ASSERT()

- DMCompiler/DMStandard/Types/World.dm
> Adds score and medal procs

- DMCompiler/DM/Visitors/DMVisitorProcBuilder.cs
- OpenDreamRuntime.Tests/DMProject/code.dm
- OpenDreamRuntime.Tests/UnitTest1.cs
- OpenDreamShared/Compiler/DM/DMParser.cs
These are valid in DM, ran into them here:
https://github.com/vgstation-coders/vgstation13/blob/8cb508bbbcde3a67869c86797a88ff6c13a930b7/code/__HELPERS/text.dm#L534
> Support for for-loops without initializer or incrementor

- DMCompiler/DMStandard/Types/Matrix.dm
- OpenDreamRuntime.Tests/DMProject/code.dm
- OpenDreamRuntime.Tests/UnitTest1.cs
Closes #330
Closes #328
Closes #303
Closes #272
> Implemented most matrix operations

- DMCompiler/DMStandard/_Standard.dm
> Adds step_away()

- OpenDreamShared/Dream/DreamPath.cs
Credit to PJB. Tested on stripped TG.
> Optimize Normalize()

- OpenDreamShared/Compiler/DM/DMParser.cs
- OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
> Adds `command_text` astype

- DMCompiler/DM/DMProc.cs
- DMCompiler/DM/Expressions/Binary.cs
- DMCompiler/DM/Visitors/DMVisitorExpression.cs
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
- OpenDreamRuntime/Procs/DMProc.cs
- OpenDreamShared/Compiler/DM/DMAST.cs
- OpenDreamShared/Compiler/DM/DMLexer.cs
- OpenDreamShared/Compiler/DM/DMParser.cs
- OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
- OpenDreamShared/Compiler/Token.cs
- OpenDreamShared/Compiler/TokenHelper.cs
- OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
> Implements list equivalence

- OpenDreamShared/Compiler/DM/DMParser.cs
- OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
> Adds sound and icon astypes

- OpenDreamShared/Compiler/DM/DMParser.cs
> Switch cases ignore trailing commas

- DMCompiler/DM/DMObject.cs
- DMCompiler/DM/Visitors/DMVisitorProcBuilder.cs
- OpenDreamShared/Compiler/DM/DMLexer.cs
- OpenDreamShared/Compiler/DM/DMParser.cs
- OpenDreamShared/Dream/DreamPath.cs
> Implements implicit `in world` loops

- OpenDreamShared/Compiler/DMF/DMFLexer.cs
- OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
- OpenDreamShared/Compiler/Lexer.cs
> Removes pointless `CreateToken()`s

- OpenDreamShared/Compiler/DM/DMParser.cs
- OpenDreamShared/Dream/DreamPath.cs
Fixes some number of errors in all codebases
> Adds support for `var/thing[]` lists in object definitions

- OpenDreamShared/Compiler/DM/DMParser.cs
Fixes #388 
Tested on a while loop, didn't test a for loop.
> Adds support for bodyless for/while loops

- OpenDreamShared/Compiler/DM/DMParser.cs
> Converts Whitespace() to use a readonlyspan

- DMCompiler/DMStandard/Types/Mutable_Appearance.dm
http://www.byond.com/docs/ref/#/mutable_appearance/var
> Adds vars to `mutable_appearance`

- DMCompiler/Compiler/DM/DMASTHelper.cs
> Fixes the compiler on the RT branch

- OpenDreamShared/Compiler/DM/DMParser.cs
> Let labels start with colons

- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs
wixoa found it I'm just webediting it in
> [RT] Fix overlay removal

- OpenDreamClient/Interface/Controls/ScalingViewport.cs
Changes the stretch mode and render scale to not make the viewport blurry.
> [RT] Removes viewport blurriness

- DMCompiler/DM/Visitors/DMASTSimplifier.cs
test case:
```
#include "map.dmm"
#include "interface.dmf"
/world/New()
var/x = 0
var/sv = 548
switch(sv)
if(5 || x)
ASSERT(0)
if(0 && x)
ASSERT(0)
if("a" || x)
ASSERT(0)
if("" && x)
ASSERT(0)
if(5.5 || x)
ASSERT(0)
if(0.0 && x)
ASSERT(0)
shutdown()
```
> switch case simplification and boolean short circuiting

- .github/workflows/build-test.yml
- .github/workflows/compiler-test.yml
- DMCompiler/DMCompiler.csproj
- DMCompiler/copy_standard.bat
- OpenDreamClient/OpenDreamClient.csproj
- OpenDreamClient/Rendering/DMISpriteComponent.cs
- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs
- OpenDreamRuntime/OpenDreamRuntime.csproj
- OpenDreamServer/OpenDreamServer.csproj
- OpenDreamShared/OpenDreamShared.csproj
See title. Only issue I can find is UIs being messed up:
Not sure what's going on there.
> [RT] Bumps everything to .NET 6 and RT 0.7.x

- DMCompiler/Compiler/DMM/DMMParser.cs
- DMCompiler/DM/DMObject.cs
- DMCompiler/DM/Expressions/Dereference.cs
- DMCompiler/DM/Expressions/Procs.cs
- DMCompiler/Program.cs
- OpenDreamShared/Compiler/DM/DMParser.cs
- OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessor.cs
Reduces most of the console clutter when you're trying to fix actual compilation errors.
> Adds an arg to suppress unimplemented warnings

- DMCompiler/DM/DMObject.cs
- DMCompiler/DM/DMObjectTree.cs
- DMCompiler/DM/DMProc.cs
- DMCompiler/DM/Visitors/DMProcBuilder.cs
- DMCompiler/DM/Visitors/DMVisitorExpression.cs
Paradise will now compile without throwing a real exception, minus #470 and #471 which need to be fixed anyways.
> More robust exception handling

- OpenDreamShared/Compiler/DM/DMLexer.cs
- OpenDreamShared/Compiler/DM/DMParser.cs
- OpenDreamShared/Compiler/Token.cs
Survived basic testing as both a local var name and as the builtin proc.
Fixes #470
> Makes it possible to name vars newlist

- DMCompiler/DMStandard/Defines.dm
- OpenDreamShared/Compiler/DM/DMParser.cs
- OpenDreamShared/Dream/DreamPath.cs
This adds every unknown define in Paradise and also fixes `var/thing[]` handling.
> Stub a ton of defines and fix list handling

- DMCompiler/DM/DMExpression.cs
- DMCompiler/DM/DMObjectTree.cs
- DMCompiler/DM/Expressions/Builtins.cs
- DMCompiler/DM/Expressions/Constant.cs
- DMCompiler/DM/Expressions/Dereference.cs
- DMCompiler/DM/Expressions/LValue.cs
- DMCompiler/DM/Expressions/Procs.cs
- DMCompiler/DM/Visitors/DMASTSimplifier.cs
- DMCompiler/DM/Visitors/DMObjectBuilder.cs
- DMCompiler/DM/Visitors/DMProcBuilder.cs
- DMCompiler/DM/Visitors/DMVisitorExpression.cs
- OpenDreamShared/Compiler/CompilerError.cs
- OpenDreamShared/Compiler/DM/DMAST.cs
- OpenDreamShared/Compiler/DM/DMASTHelper.cs
- OpenDreamShared/Compiler/DM/DMParser.cs
- OpenDreamShared/Compiler/DMPreprocessor/DMMacro.cs
- OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessor.cs
- OpenDreamShared/Compiler/Lexer.cs
- OpenDreamShared/Compiler/Location.cs
- OpenDreamShared/Compiler/Token.cs
This code is a mixture of Willox's code, duct tape, and prayer. 
It can definitely be improved but also this was a real pain just to get this far so anything else is being punted to future PRs.
> Adds error info to the DMAST

- DMCompiler/DM/DMProc.cs
- DMCompiler/DM/Expressions/Procs.cs
It won't get you to the exact line but it will get you the file and proc block.
> Adds a semiaccurate location for missing procs

- OpenDreamRuntime/Objects/DreamList.cs
Partially addresses the first point in https://github.com/wixoaGit/OpenDream/issues/342
> DreamList.Create() no longer calls InitSpawn()

- DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
> Add support for nested comments

- OpenDreamRuntime/DreamManager.cs
> Invalid JSON nukes the server

- OpenDreamShared/Dream/DreamPath.cs
Should improve #498 and generally somewhat speed up DreamPath
> Reduce amount of allocations and speed up DreamPath

- DMCompiler/DM/DMObjectTree.cs
> Fix a specific case of upward searching an absolute path

- DMCompiler/DM/DMProc.cs
- OpenDreamRuntime/Objects/DreamObjectTree.cs
- OpenDreamShared/Json/DreamObjectJson.cs
> Don't serialize true WaitFor

- DMCompiler/DMStandard/Types/Atoms/_Atom.dm
- OpenDreamRuntime/Objects/DreamObjectTree.cs
> Implements default `atom/var/text`, attempt 3

- DMCompiler/DMStandard/_Standard.dm
- DMCompiler/copy_standard.sh
- TestGame/code.dm
Also it adds a shellscript for easily copying the DMStandard folder, golly gee i was sure fucking confused why my changes didnt do anything till i noticed that damn bat file!
> Adds a helper shell script to copy DMStandard to the right folder just in case you are using emacs or whatever

- OpenDreamClient/EntryPoint.cs
- OpenDreamClient/Interface/DreamStylesheet.cs
- OpenDreamClient/Program.cs
- OpenDreamServer/server_config.toml
- Resources/manifest.yml
> Robust update, branding stuff, re-disable prediction

- DMCompiler/DM/DMProc.cs
- DMCompiler/DM/Expressions/Procs.cs
Title, fixes #575
~~Unsure if bringing of IsOverride outside the AST level is correct~~ seems like it is
> Basic impl of supercall in non-override error

- OpenDreamServer/server_config.toml
Nukes most of the PVS streaming troubles.
> Triples the PVS entity budgets

- DMCompiler/DM/Visitors/DMObjectBuilder.cs
- DMCompiler/DMStandard/Defines.dm
- DMCompiler/DMStandard/Types/Generator.dm
- DMCompiler/DMStandard/UnsortedAdditions.dm
`http://www.byond.com/docs/ref/#/{notes}/generators`
> Stubs generators

- DMCompiler/DMStandard/Defines.dm
- DMCompiler/DMStandard/Types/Atoms/Movable.dm
- DMCompiler/DMStandard/Types/List.dm
- DMCompiler/DMStandard/Types/Particles.dm
- DMCompiler/DMStandard/Types/Regex.dm
- DMCompiler/DMStandard/UnsortedAdditions.dm
- DMCompiler/DMStandard/_Standard.dm
See title.
Also #includes the generator stub and fixes some inconsistent indentation.
> Stubs a bunch of things TG uses

- OpenDreamClient/Interface/Controls/ControlWindow.cs
> Fix menu names starting with &

- DMCompiler/DM/DMProc.cs
- DMCompiler/DM/Visitors/DMProcBuilder.cs
- DMCompiler/DMStandard/Types/Client.dm
- OpenDreamClient/Interface/Controls/ControlButton.cs
- OpenDreamClient/Interface/Controls/ControlInfo.cs
- OpenDreamClient/Interface/DreamInterfaceManager.cs
- OpenDreamClient/Interface/DreamStylesheet.cs
- OpenDreamClient/Interface/DummyDreamInterfaceManager.cs
- OpenDreamRuntime/DreamConnection.cs
- OpenDreamRuntime/DreamThread.cs
- OpenDreamShared/Dream/Procs/ProcAttributes.cs
- OpenDreamShared/Interface/ControlDescriptors.cs
- OpenDreamShared/Json/DreamProcJson.cs
- OpenDreamShared/Network/Messages/MsgUpdateAvailableVerbs.cs
- TestGame/code.dm
Also makes ProcAttributes both work again and not be unnecessarily serialized.
I also improved the interface a bit and fixed the initial tab not being updated until after switching tabs,
Pics of the DMF improvements (most/all of those verbs don't actually have their name set, I promise it does work):
> Implements verb name, category, and hidden & improves the interface

- DMCompiler/Compiler/DM/DMParser.cs
> Fixes `\...` parsing

- OpenDreamRuntime/Objects/DreamObject.cs
Can someone test it on ss13 and tell me if it crashes and burns? thanks in advance!
> Adds support for sort of hard deletions

- DMCompiler/DM/DMProc.cs
- DMCompiler/DM/Visitors/DMProcBuilder.cs
- OpenDreamShared/Dream/Procs/ProcAttributes.cs
- OpenDreamShared/Json/DreamProcJson.cs
> Implements `background`

- OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs
Closes #636 
Untested because I suck at regex.
> Implements nonglobal regex replace, fixes `end` arg

- README.md
> Make the .NET 6 requirement more obvious

- DMCompiler/Compiler/DM/DMAST.cs
- DMCompiler/Compiler/DM/DMParser.cs
- DMCompiler/DM/Visitors/DMVisitorExpression.cs
`new record_found.fields["species"]`
> Adds support for new on a listindex

- DMCompiler/Compiler/DM/DMParser.cs
- DMCompiler/DM/Visitors/DMVisitorExpression.cs
Shaves off ~100 MB and 1-2 seconds from Paradise compilation.
> Misc cleanup + allow `null` in typepaths

- DMCompiler/DM/Expressions/Dereference.cs
Closes https://github.com/wixoaGit/OpenDream/issues/528
Supercedes https://github.com/wixoaGit/OpenDream/pull/667
Tested and working.
> Fixes ternary derefs in a better way

- OpenDreamClient/Rendering/DreamViewOverlay.cs
> Nuke a ton of DreamViewOverlay allocs

- DMCompiler/DMStandard/Types/Atoms/_Atom.dm
- DMCompiler/DMStandard/Types/Client.dm
TG uses at least one of these.
> Stub a bunch of mouse procs

- DMCompiler/DM/Expressions/Dereference.cs
> Fix list BinaryAnd deref

- DMCompiler/DMStandard/Types/List.dm
- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectList.cs
> Declare `type` on `/list`

- DMCompiler/DM/Visitors/DMObjectBuilder.cs
> Pass proc info down DMObjectBuilder

- DMCompiler/DM/Expressions/Builtins.cs
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
```
/proc/_pick(...)
return pick(arglist(args))
```
> Fix `pick(arglist(args))`

- DMCompiler/DMStandard/UnsortedAdditions.dm
> Stub `obounds()`

- DMCompiler/DM/Expressions/Builtins.cs
- DMCompiler/DM/Expressions/Dereference.cs
> Stop incorrectly warning for list indexes of `vars`

- OpenDreamClient/Rendering/DMISpriteComponent.cs
- OpenDreamClient/Rendering/DreamViewOverlay.cs
Not sure how much value it is at this stage.
> Render perf optimisations

- OpenDreamRuntime/DreamValue.cs
Closes #713 
Icon code really isn't my thing but I assume this is correct.
> Adds icon serialization

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Fixes enough runtimes to get paradise's character creator working (when combined with savefiles).
> Add icon support to BrowseResource

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> Fix a funky assoc list declaration

- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Also made it a switch to go faster.
> Decode null json values

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> Implement string sorting

- DMCompiler/Compiler/DM/DMParser.cs
> Fixes ternaries with constants for B

- DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs
> Remove newline check from macro args

- OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs
Closes #638 
I did basic testing with strings, procs, and just passing null. But I did not come up with every imaginable case, hence the TODOs.
> Implement proc regex replace

- DMCompiler/DMStandard/Types/Client.dm
- DMCompiler/DMStandard/Types/Particles.dm
- DMCompiler/DMStandard/Types/Sound.dm
Stubs every var Goon uses that isn't already stubbed.
> Stub misc vars

- DMCompiler/DM/Visitors/DMObjectBuilder.cs
> Fix setting a static var to an addition of static vars

- DMCompiler/DM/Visitors/DMObjectBuilder.cs
`var/static/list/list_symptoms = typesof(/datum/symptom) - /datum/symptom`
> Fix static var subtraction

- DMCompiler/Compiler/DM/DMAST.cs
- DMCompiler/Compiler/DM/DMParser.cs
- DMCompiler/DM/Visitors/DMASTSimplifier.cs
- DMCompiler/DM/Visitors/DMProcBuilder.cs
- DMCompiler/DM/Visitors/DMVisitorExpression.cs
this happens occasionally in the unmodified ss13 repos, where the statement expression has side effects as well
> for loop edge case handling

- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Matches ref & BYOND behavior. Also tested it.
> Make clamp min/max unordered

- DMCompiler/DMStandard/Types/Client.dm
- DMCompiler/DMStandard/UnsortedAdditions.dm
Only unstubbed things in Yogs.
> Stub `gradient()` and `show_verb_panel`

- README.md
I'm so tired of this coming up because people don't want to spend more than 10 seconds learning about the project.
> Clarifies BYOND compatibility in the README

- DMCompiler/DM/Visitors/DMProcBuilder.cs
While I was thumbing through the code, I found that there wasn't really any typechecking done on switch ranges.
I checked MoMMI and it seems this bug does indeed also exist in DM 514, but wixoa agreed that there should be at least a warning, if not an error, for this behaviour, so I went ahead and added it.
I do not know of any repository which actually makes use of this bug as it exists in DM, so for now this PR marks most cases as being an honest error.
-  Added some exceptions for trying to make a switch-case's range's bounds be anything other than numbers. Nulls are coerced into the value 0 with a compiler warning, and anything else causes a compiletime error.
> Fixes invalid switch-case ranges not causing warnings/errors

- OpenDreamClient/Interface/Prompts/NumberPrompt.cs
aka `input() as num`
<details>
<summary>GIF Comparison</summary>
OLD:<br>
<br><br>
NEW:<br>
</details>
this is so all of you stop harassing me about not contributing 😭
> Adds number input validation to NumberPrompt

- DMCompiler/DM/Visitors/DMProcBuilder.cs
> Fix else blocks not defining a scope

- Content.Tests/DMProject/Tests/List/ListDerefJoin.dm
- DMCompiler/Compiler/DM/DMParser.cs
- DMCompiler/DM/Expressions/Dereference.cs
Fixes #808 
Not sure if this is the cleanest way to do it, but it works
> Fixes `list().Join()`

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
- OpenDreamRuntime/Procs/DMProc.cs
> Fix procs on deleted objects continuing to run

- DMCompiler/DMStandard/Types/Atoms/_Atom.dm
- DMCompiler/DMStandard/Types/Client.dm
- /atom/proc/MouseDown
- /client/proc
- MouseDown
- AllowUpload
- Command
- Import
- CheckPassport
- SendPage
- GetAPI
- SetAPI
> Add missing /client proc stubs

- DMCompiler/DMStandard/Types/Particles.dm
Saw the todo and some ??? so I decided to add some of what I know
> Add some particle internal working detail comments

- OpenDream.sln
- OpenDreamClient/Input/MouseInputSystem.cs
- OpenDreamClient/Interface/Controls/ScalingViewport.cs
- OpenDreamClient/Rendering/DMISpriteComponent.cs
- OpenDreamClient/States/Connecting/ConnectingState.cs
- OpenDreamClient/States/InGameState.cs
- OpenDreamClient/States/MainMenu/MainMenuState.cs
- OpenDreamRuntime/DreamMapManager.cs
- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectTurf.cs
- OpenDreamShared/Network/Messages/MsgAckLoadInterface.cs
- OpenDreamShared/Network/Messages/MsgAlert.cs
- OpenDreamShared/Network/Messages/MsgBrowse.cs
- OpenDreamShared/Network/Messages/MsgBrowseResource.cs
- OpenDreamShared/Network/Messages/MsgLoadInterface.cs
- OpenDreamShared/Network/Messages/MsgOutput.cs
- OpenDreamShared/Network/Messages/MsgPrompt.cs
- OpenDreamShared/Network/Messages/MsgPromptList.cs
- OpenDreamShared/Network/Messages/MsgPromptResponse.cs
- OpenDreamShared/Network/Messages/MsgRequestResource.cs
- OpenDreamShared/Network/Messages/MsgResource.cs
- OpenDreamShared/Network/Messages/MsgSelectStatPanel.cs
- OpenDreamShared/Network/Messages/MsgSound.cs
- OpenDreamShared/Network/Messages/MsgTopic.cs
- OpenDreamShared/Network/Messages/MsgUpdateAvailableVerbs.cs
- OpenDreamShared/Network/Messages/MsgUpdateStatPanels.cs
- OpenDreamShared/Network/Messages/MsgWinExists.cs
- OpenDreamShared/Network/Messages/MsgWinSet.cs
Pretty sure everything is working. Please check if you happen to know some delicate bits that might break.
~~Do not merge yet, as we're still relying on a branch which I've PR'd upstream but is not merged yet. (https://github.com/space-wizards/RobustToolbox/pull/3484)~~ Merge now plz.
> Update RT to latest

- OpenDream.sln.DotSettings
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
`fcopy()` can take a savefile as a Src arg
> Allow using a savefile in `fcopy()`

- DMCompiler/DMStandard/Types/Mutable_Appearance.dm
`/mutable_appearance/New()` can take an icon file
> Allow using a file to create `/mutable_appearance`

- DMCompiler/Compiler/DM/DMLexer.cs
- DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs
- DMCompiler/DMCompiler.cs
- OpenDreamShared/Compiler/Parser.cs
- OpenDreamShared/Compiler/ParserHelper.cs
These tiny changes shave about ~1050 ms off of TG compilation, bringing it from ~10.8 seconds to ~9.7 seconds on my computer.
> Misc Compiler Optimizations

- OpenDreamRuntime/Procs/ProcDecoder.cs
This opcode no longer has any operands
> Fix decoding of the `Initial` opcode

- DMCompiler/DMStandard/Types/Icon.dm
- OpenDreamClient/Rendering/DMISpriteComponent.cs
- OpenDreamClient/Rendering/DreamViewOverlay.cs
- OpenDreamClient/Resources/ResourceTypes/DMIResource.cs
- OpenDreamRuntime/Objects/DreamIcon.cs
- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMovable.cs
- OpenDreamRuntime/Procs/Native/DreamProcNative.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeIcon.cs
Allows `/icon` objects to be resized.
Part of an attempt to get Paradise's clicking to work.
> Implement '/icon.Scale()'

- DMCompiler/DM/Visitors/DMProcBuilder.cs
Fixes a mistake in #956, oops.
> Fix `continue` in while loops

- OpenDreamRuntime/Procs/DreamProcArguments.cs
Adds some useful helpers to try and get values without having to worry about certain derefs
> Add `TryGetNamedArgument` and `TryGetPositionalArgument` to `DreamProcArguments`

- DMCompiler/DMStandard/Types/World.dm
- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectWorld.cs
Closes #861 
Confirmed it worked by comparing it to the PID in Task Manager.
> Implement `world.process`

- OpenDreamRuntime/Procs/DMProc.cs
- OpenDreamShared/Dream/DreamPath.cs
Converts proc property accessing to the new method of getting procs, `DreamValue.TryGetValueAsProc()`.
> Fix proc property accessing

- DMCompiler/DM/Expressions/Binary.cs
- DMCompiler/DM/Expressions/Constant.cs
> one-sided const-eval for `&&` and `||`

- DMCompiler/DMStandard/Types/Savefile.dm
- OpenDreamRuntime/DreamValue.cs
- OpenDreamRuntime/Procs/Native/DreamProcNative.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs
- OpenDreamRuntime/Resources/DreamResourceManager.cs
- OpenDreamRuntime/Resources/IconResource.cs
This implements `ExportText()` just enough to get `icon2base64()` working.
Also gets json deserialization for /icon working.
> Implement `/savefile.ExportText()` just enough for `icon2base64()`

- DMCompiler/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
- OpenDreamShared/Compiler/Lexer.cs
> Use the new .NET 7 ASCII helpers

- DMCompiler/DMStandard/Types/Atoms/Mob.dm
- DMCompiler/DMStandard/Types/Generator.dm
- DMCompiler/DMStandard/Types/Sound.dm
- DMCompiler/DMStandard/UnsortedAdditions.dm
Move some goon compile errors to unimplemented warnings instead
> Add a few missing unimplemented placeholders

- OpenDream.sln.DotSettings
- OpenDreamClient/Input/DreamMacroManager.cs
- OpenDreamClient/Rendering/ClientAppearanceSystem.cs
- OpenDreamRuntime/AtomManager.cs
- OpenDreamRuntime/DreamManager.Connections.cs
- OpenDreamRuntime/DreamManager.cs
- OpenDreamRuntime/DreamValue.cs
- OpenDreamRuntime/EntryPoint.cs
- OpenDreamRuntime/IDreamManager.cs
- OpenDreamRuntime/Input/DreamCommandSystem.cs
- OpenDreamRuntime/Objects/DreamList.cs
- OpenDreamRuntime/Objects/DreamObjectTree.cs
- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectClient.cs
- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMovable.cs
- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectSavefile.cs
- OpenDreamRuntime/Procs/AsyncNativeProc.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
- OpenDreamRuntime/Procs/NativeProc.cs
- OpenDreamRuntime/Rendering/DMISpriteComponent.cs
Also fix some deprecation and nullable warnings
> Update to RobustToolbox v0.81.0.0

- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
fix https://github.com/OpenDreamProject/OpenDream/issues/1042
> fix(NativeProc_isloc): return False if one of args is null

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
fix https://github.com/OpenDreamProject/OpenDream/issues/903
> fix(PickUnweighted): throw exception on empty list()

- OpenDreamClient/Interface/Controls/ControlWindow.cs
- OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs
- OpenDreamClient/Interface/DreamInterfaceManager.cs
Windows can run commands when closed.
> Implement `on-close` DMF attribute

- OpenDreamClient/Interface/InterfaceMacro.cs
The `+UP` in macros would be stripped so they would be treated as regular macros. This fixes that.
> Fix `+UP` macros

- DMCompiler/DMStandard/Types/Client.dm
https://www.byond.com/docs/ref/#/client/var/lazy_eye
> Stub `client.lazy_eye`

- DMCompiler/DMStandard/Types/Mutable_Appearance.dm
Credit to @out-of-phaze. They just didn't make the PR.
> Add path support for `mutable_appearance/New()`

- DMCompiler/DMStandard/_Standard.dm
- OpenDreamRuntime/Procs/Native/DreamProcNative.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Rewrites the `get_dir()` builtin as a native proc
Performance before:
After:
> Rewrite `get_dir()` builtin in C#

- DMCompiler/DMStandard/_Standard.dm
- OpenDreamRuntime/Procs/Native/DreamProcNative.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Rewrites the `get_step()` builtin as a native proc
Performance before:
After:
> Rewrite `get_step()` builtin in C#

- Content.Tests/DMProject/Tests/Math/Infinity.dm
- DMCompiler/DM/Expressions/Constant.cs
- DMCompiler/DMCompiler.cs
- OpenDreamRuntime/Objects/DreamObjectTree.cs
- OpenDreamShared/Json/DreamObjectJson.cs
> Allow positive/negative infinity to be encoded in compiler output

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Following Willox's advice, switching the order of these two conditionals fixed blending colors onto icons via the append operator.
> Fix icon color blending via append operator

- Content.Tests/DMProject/Tests/Builtins/JsonEncode.dm
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
BYOND just turns it into a string.
> Implement json encoding a proc

- Content.Tests/DMProject/Tests/Builtins/__PROC__.dm
- Content.Tests/DMProject/Tests/Builtins/__TYPE__.dm
- DMCompiler/DM/Expressions/Builtins.cs
- DMCompiler/DM/Visitors/DMVisitorExpression.cs
> Replace `opendream_procpath` with BYOND 515 equivalents

- OpenDreamRuntime/DreamThread.cs
> Increase the max stack depth to 400

- Content.Tests/DMProject/Tests/Special Procs/nameof/nameof.dm
- Content.Tests/DMProject/Tests/Special Procs/nameof/nameof_error.dm
- DMCompiler/Compiler/DM/DMAST.cs
- DMCompiler/Compiler/DM/DMParser.cs
- DMCompiler/DM/DMExpression.cs
- DMCompiler/DM/DMProc.cs
- DMCompiler/DM/Expressions/Builtins.cs
- DMCompiler/DM/Expressions/Constant.cs
- DMCompiler/DM/Expressions/LValue.cs
- DMCompiler/DM/Visitors/DMObjectBuilder.cs
- DMCompiler/DM/Visitors/DMVisitorExpression.cs
Closes #1115 
Let me know if you think of other expressions that I missed, but the ref isn't super detailed.
> Implements `nameof()`

- OpenDream.sln
RobustToolbox added a new project that needs to be added to the solution.
> Add `Robust.Shared.CompNetworkGenerator` project to the solution

- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
A `/client` can be used as the first argument in an `alert()` call.
> Fix using a client as the first arg to `alert()`

- OpenDreamRuntime/DreamManager.cs
- OpenDreamRuntime/IDreamManager.cs
Ok yeah this should be good now I hope 🙏 Yell at me if not.
> Appearance ref implementation

- OpenDreamClient/Interface/Prompts/ListPrompt.cs
- OpenDreamClient/Interface/Prompts/NumberPrompt.cs
- OpenDreamClient/Interface/Prompts/PromptWindow.cs
- OpenDreamClient/Interface/Prompts/TextPrompt.cs
You can now press enter to finish input prompts.
Bothered me during the playtest.
> Add an enter shortcut to input prompts

- OpenDreamRuntime/Objects/DreamList.cs
Optimize `DreamList.CreateCopy()` by creating the associative value dictionary directly rather than going through `SetValue()`
Before:
After:
Should fix #1120 when merged in combination with #1212
> Optimize `DreamList.CreateCopy()`

- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
also adds a TODO about lowercase named arguments
> clamp rgb() arguments

- .editorconfig
Update the editorconfig to better reflect some of the code styles used in the codebase
> Update the editorconfig

- OpenDreamRuntime/DreamValue.cs
Basic Paradise init comparisons show a consistent ~2 second speedup
> Speed up some DreamObject casts

- OpenDreamRuntime/Rendering/DMISpriteComponent.cs
Moves the `ServerAppearanceSystem.AddAppearance()` call from `SetAppearance()` to `GetComponentState()` which reduces the amount of interim appearances being added to the appearances list.
Before:
After:
> Optimize `DMISpriteComponent.SetAppearance()`

- README.md
A lot of people seem to have the misconception that OpenDream should more or less work "out of the box" in its current state and/or have QoL features that simply don't exist yet, and I want to hammer home the point that this is not (yet) the case.
> Emphasize the state of the project in the readme

- Content.Tests/DMProject/Tests/Text/StringInterpolation8.dm
- DMCompiler/Compiler/DM/DMParserHelper.cs
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
- OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
postPrefix is kinda cursed but also its the most sane way to do this.
> Implements \roman \Roman macros

- Content.Tests/DMProject/Tests/Preprocessor/Include/simple_include.dm
- Content.Tests/DMProject/Tests/Preprocessor/Include/test_module/test_file_to_include.dm
- Content.Tests/DMProject/Tests/Preprocessor/Include/whitespace_before_include.dm
- DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs
> fix(DMPreprocessor): skip whitespaces before #include

- Content.Tests/DMProject/Tests/Statements/Control Flow/try_catch3.dm
- DMCompiler/Compiler/DM/DMParser.cs
> Support for braced blocks in try-catch statements

- OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectMob.cs
The ckey PR got merged moments before I pushed this last commit 😭
> ckey assignment

- Content.Tests/DMProject/Tests/Expression/String/unicode.dm
- DMCompiler/Compiler/DM/DMLexer.cs
- DMCompiler/Compiler/DM/DMParserHelper.cs
* Add to DMParser logic for Unicode macroses parsing
* Fix Unicode unittests
fix  #1239
> feat(DMParser): implement Unicode macroses parsing

- OpenDreamRuntime/Objects/DreamObjectDefinition.cs
- OpenDreamRuntime/Objects/Types/DreamList.cs
> Don't include root-level global vars in `/datum.vars`

- OpenDreamRuntime/Resources/DreamResource.cs
This just appends an empty line to the file.
> Fix `file << null`

- DMCompiler/Compiler/DM/DMAST.cs
- DMCompiler/Compiler/DM/DMParser.cs
- DMCompiler/DM/DMProc.cs
- DMCompiler/DM/Visitors/DMASTSimplifier.cs
- DMCompiler/DM/Visitors/DMProcBuilder.cs
- DMCompiler/DMStandard/UnsortedAdditions.dm
- OpenDreamClient/Interface/DreamInterfaceManager.cs
- OpenDreamClient/Resources/ResourceTypes/DreamResource.cs
- OpenDreamRuntime/DreamConnection.cs
- OpenDreamRuntime/DreamManager.Connections.cs
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
- OpenDreamRuntime/Procs/DMProc.cs
- OpenDreamShared/Dream/Procs/DreamProcOpcode.cs
- OpenDreamShared/Network/Messages/MsgFtp.cs
> Implement `usr << ftp()`

- Content.Tests/DMProject/Tests/Expression/Derefs/new_deref.dm
- DMCompiler/DM/Expressions/Builtins.cs
> Implement `Path` for `NewPath` class

- DMCompiler/DMStandard/Defines.dm
- OpenDream.sln.DotSettings
- OpenDreamRuntime/Procs/Native/DreamProcNative.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeWorld.cs
Just return the column names in a list, or an empty array if the format is json.
> Return bare-minimum in `world.Profile()`

- OpenDreamRuntime/DreamConnection.cs
This reverts a recent change that broke mob assignment.
> Fix mob assignment

- DMCompiler/DM/Expressions/Constant.cs
Fixed some exceptions that could occur if the output dir was the working directory or root
> Fix some exceptions that can happen when looking for a resource

- Content.Tests/DMProject/Tests/Expression/Derefs/new_fuzzy_deref.dm
- DMCompiler/DM/Visitors/DMVisitorExpression.cs
> Fuzzy search for `new` on non-explicit type

- OpenDreamRuntime/DreamManager.cs
- OpenDreamRuntime/DreamThread.cs
- OpenDreamRuntime/IDreamManager.cs
- OpenDreamRuntime/Objects/DreamObjectTree.cs
- OpenDreamRuntime/Procs/AsyncNativeProc.cs
- OpenDreamRuntime/Procs/DMProc.cs
- OpenDreamRuntime/Procs/NativeProc.cs
> Add support for procs to `ref()`

- OpenDreamRuntime/DreamMapManager.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeHelpers.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
- OpenDreamShared/Dream/ViewAlgorithm.cs
Hooks up the [visibility algorithm](https://github.com/OpenDreamProject/OpenDream/pull/1299) to the `view()` and `oview()` procs.
> Use the visibility algorithm in `view()` and `oview()`

- OpenDreamClient/EntryPoint.cs
- OpenDreamClient/Interface/Controls/ControlBrowser.cs
- OpenDreamClient/Rendering/ClientAppearanceSystem.cs
- OpenDreamClient/Rendering/DMISpriteComponent.cs
- OpenDreamClient/Resources/DreamResourceManager.cs
- OpenDreamRuntime/DreamValue.cs
- OpenDreamRuntime/EntryPoint.cs
> Update RT to v0.121

- OpenDream.sln.DotSettings
- OpenDreamClient/Input/MouseInputSystem.cs
- OpenDreamClient/Interface/Controls/ControlMap.cs
- OpenDreamClient/Interface/DreamInterfaceManager.cs
- OpenDreamClient/Interface/InterfaceMacro.cs
- OpenDreamClient/Interface/OpenDreamKeyFunctions.cs
- OpenDreamRuntime/Input/MouseInputSystem.cs
- OpenDreamShared/Input/SharedMouseInputSystem.cs
> Add support for middle mouse clicks

- OpenDreamRuntime/Objects/Types/DreamList.cs
Loops like `for (var/i in area)` should contain turf contents in addition to turfs.
This fixes light switches, area power updates, and likely a bunch of other things.
Fixes #1004
Resolves #1068
> Include turf contents in area contents

- Content.Tests/DMProject/Tests/Builtins/JsonEncode.dm
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
- Fixes #1330 
Keep in mind that we need to get around decoding them as well, which is not implemented in this PR
> JSON-encoding Infinity & NaN

- OpenDreamClient/Interface/Controls/ControlInfo.cs
- OpenDreamRuntime/DreamConnection.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
- OpenDreamShared/Network/Messages/MsgUpdateStatPanels.cs
> Use a grid layout in stat panels

- OpenDreamClient/Input/MouseInputSystem.cs
- OpenDreamClient/Interface/Controls/ControlInfo.cs
- OpenDreamRuntime/DreamConnection.cs
- OpenDreamRuntime/Input/MouseInputSystem.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
- OpenDreamShared/Input/SharedMouseInputSystem.cs
- OpenDreamShared/Network/Messages/MsgUpdateStatPanels.cs
If you give `stat()` an atom value then it's clickable in the stat panel.
> Make atoms in stat panels clickable

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Fixes `to_chat(world, ...)` in SS13
> Fix `world << output(...)`

- DMCompiler/DM/DMObjectTree.cs
- DMCompiler/DM/Expressions/Constant.cs
- DMCompiler/DMCompiler.cs
- OpenDream.sln
- OpenDreamClient/Rendering/DMISpriteComponent.cs
- OpenDreamClient/Resources/DreamResourceManager.cs
- OpenDreamPackaging/DreamPackaging.cs
- OpenDreamPackaging/OpenDreamPackaging.csproj
- OpenDreamPackaging/Program.cs
- OpenDreamRuntime/DreamMagicAczProvider.cs
- OpenDreamRuntime/DreamManager.cs
- OpenDreamRuntime/OpenDreamRuntime.csproj
- OpenDreamRuntime/Resources/DreamResourceManager.cs
- OpenDreamShared/Json/DreamCompiledJson.cs
:tada:
Means resource downloads won't suck for the next playtest.
Fixes #603
> Resource fixes, ACZ resources

- OpenDreamRuntime/DreamValue.cs
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Credit to moony who is just too lazy to PR it.
The typechecking was redundant.
Completely untested.
> Optimize `Increment`/`Decrement`/`Negate`

- OpenDream.sln.DotSettings
- OpenDreamClient/Input/MouseInputSystem.cs
- OpenDreamClient/Rendering/DMISpriteComponent.cs
- OpenDreamClient/Rendering/DreamPlane.cs
- OpenDreamClient/Rendering/DreamViewOverlay.cs
- OpenDreamRuntime/AtomManager.cs
- OpenDreamShared/Dream/IconAppearance.cs
Some general cleanup and optimization of the renderer. Reduces allocations by several hundred KiB per frame. Also reduces some `RenderInRenderTarget()` calls.
> Cleanup & optimize the renderer a bit

- OpenDreamRuntime/Objects/Types/DreamObjectRegex.cs
Any character except a letter or line break
> Add support for `\L` in regex

- Content.Tests/DMProject/Tests/Operators/Remove.dm
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
`null` is treated as 0 on either side of `-=`
> Implement `null -= ...`

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> Implement equality comparison between objects and procs

- DMCompiler/DMStandard/Types/World.dm
- OpenDreamRuntime/DreamManager.Connections.cs
- OpenDreamRuntime/DreamManager.cs
- OpenDreamRuntime/OpenDreamRuntime.csproj
- OpenDreamRuntime/Procs/Native/DreamProcNativeWorld.cs
Note that this only implements raw functionality and does not implement the encrypted Topic protocol because I don't know if anyone has ever figured that one out
Closes https://github.com/OpenDreamProject/OpenDream/issues/1341
> Add Topic/Export capabilities

- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Giving `fcopy_rsc()` an `/icon` would give you null. Now it properly creates a resource out of it.
> Fix `fcopy_rsc(icon(...))`

- DMCompiler/DMStandard/Types/World.dm
- OpenDreamRuntime/DreamManager.Connections.cs
- OpenDreamRuntime/DreamManager.cs
- OpenDreamRuntime/OpenDreamRuntime.csproj
- OpenDreamRuntime/Procs/Native/DreamProcNativeWorld.cs
Reverts OpenDreamProject/OpenDream#1382
I need to add tcp delegating to RT, this is currently nonfunctional in Linux because it doesn't support socket bind sharing
> Revert "Add Topic/Export capabilities"

- README.md
cvars are confusing for my smol brain
> Update README.md with easier command line

- DMCompiler/DMStandard/Types/Client.dm
- OpenDream.sln.DotSettings
- OpenDreamClient/Interface/Controls/ControlMap.cs
- OpenDreamClient/Interface/DreamInterfaceManager.cs
- OpenDreamClient/Interface/DummyDreamInterfaceManager.cs
- OpenDreamClient/Rendering/DreamViewOverlay.cs
- OpenDreamRuntime/DreamConnection.cs
- OpenDreamRuntime/DreamManager.Connections.cs
- OpenDreamRuntime/Objects/Types/DreamObjectClient.cs
- OpenDreamRuntime/Objects/Types/DreamObjectWorld.cs
- OpenDreamShared/Dream/ScreenLocation.cs
- OpenDreamShared/Dream/ViewRange.cs
- OpenDreamShared/Network/Messages/MsgUpdateClientInfo.cs
View range isn't hardcoded to 15x15 anymore.
Fixes #761
Fixes #243
> Add support for `client.view`

- OpenDreamRuntime/Objects/Types/DreamList.cs
- OpenDreamRuntime/Objects/Types/DreamObjectMovable.cs
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Setting a movable's loc to an area will move it to the area's first turf.
Also fixed `locate(...) in world`
> Fix `loc = locate(/area)`

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
- OpenDreamRuntime/Resources/DreamResourceManager.cs
- OpenDreamShared/Resources/DMIParser.cs
> Support using `.png` files as icons

- Content.Tests/DMProject/Tests/Regex/regex_l_test.dm
- OpenDreamRuntime/Objects/Types/DreamObjectRegex.cs
Should fully replicate byond. I wonder if we could have our own regex parser
> Simplifies regex replacement for \L and \l

- OpenDreamRuntime/Objects/Types/DreamObjectWorld.cs
> Implemented world.timezone

- OpenDreamClient/Rendering/DreamViewOverlay.cs
Prevents the master rendering plate from capturing all the clicks in BeeStation and tg
> Implement `PASS_MOUSE`

- OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs
https://www.byond.com/docs/ref/#/{skin}/param/background-color
`none` is a valid value for background-color, so I add a custom deserialiser which allows that since the default one throws an error on "none".
> Add `none` color support

- Content.Tests/DMProject/Tests/Text/num2text.dm
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Treat negative values as 0 (as in no padding)
> Handle a negative Digits arg in `num2text()`

- OpenDreamRuntime/Procs/Native/DreamProcNativeRegex.cs
The search position was not advancing when the match was empty (leading to an infinite loop). Now it's always advanced by a minimum of 1.
> Handle zero-length matches in global regexes

- OpenDreamClient/Interface/DebugWindows/MacrosWindow.cs
- OpenDreamClient/Interface/InterfaceMacro.cs
Add a debug command that shows you the game's current macro sets and lets you execute them.
> Add a `showmacros` command

- OpenDreamClient/Interface/DreamInterfaceManager.cs
- TestGame/code.dm
windows
The IDs of all windows, separated by semicolons.
panes 
The IDs of all panes, separated by semicolons.
menus
The IDs of all menus, separated by semicolons.
macros
The IDs of all macro sets, separated by semicolons.
> `winget("windows"/"panes"/"menus"/"macros")`

- OpenDreamRuntime/DreamManager.Connections.cs
- Wrap in try/catch, warn on error.
- Properly Dispose() the accepted socket!
- Add sequence and completion debug logging.
> Makes processing world/Topic()s safer

- OpenDreamRuntime/DreamManager.Connections.cs
> Properly handle async state when processing /world/Topic()

- DMCompiler/DMStandard/Types/World.dm
See #1420
These should be redone in a way so that we can't forget to mark them like this
> world.timezone is implemented

- OpenDreamShared/OpenDreamCVars.cs
This requires https://github.com/space-wizards/RobustToolbox/pull/4493
> Fix typedef of TopicPort cvar

- DMCompiler/DMStandard/_Standard.dm
- OpenDreamRuntime/DreamConnection.cs
- OpenDreamRuntime/Objects/DreamObject.cs
- OpenDreamRuntime/Objects/DreamObjectDefinition.cs
- OpenDreamRuntime/Objects/DreamObjectTree.cs
- OpenDreamRuntime/Objects/Types/DreamObjectMovable.cs
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
- OpenDreamRuntime/Procs/Native/DreamProcNative.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeHelpers.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
- OpenDreamRuntime/Procs/NativeProc.cs
- OpenDreamRuntime/Procs/ProcScheduler.Delays.cs
- OpenDreamRuntime/ServerContentIoC.cs
- OpenDreamRuntime/WalkManager.cs
- TestGame/code.dm
> Add a framework for walks, implement `walk_towards()`

- .github/workflows/test-tgs.yml
Old branch is now merged into V6 and deleted
> Switch TGS target branch to V6

- DMCompiler/Program.cs
possibly resolves #1229 (?) Only adds --help on DMCompiler
> Add --help for DMCompiler

- OpenDreamRuntime/DreamManager.Connections.cs
This should fix the TGS test issues
> Fix Topic calls dropping partial packets

- .github/workflows/test-tgs.yml
For https://github.com/wixoa/OpenDreamFork
> Fix TGS test on non-`OpenDream` named repos

- OpenDreamClient/States/DreamUserInterfaceStateManager.cs
Makes the SS14 launcher redial the server after a disconnect.
Closes #1520
> Attempt to reconnect after a disconnect

- OpenDreamRuntime/AtomManager.cs
- OpenDreamRuntime/Objects/DreamObjectTree.cs
- OpenDreamRuntime/Objects/Types/DreamObjectAtom.cs
- OpenDreamRuntime/Objects/Types/DreamObjectMovable.cs
Moved `name`, `desc`, and `screen_loc` initialization from the constructor to `Initialize()`
> Fix `new /turf(loc)` not updating name and desc

- OpenDreamRuntime/EntryPoint.cs
Lets the server still shutdown cleanly
> Put a try/catch around savefile flushing on shutdown

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> default pick weight

- Content.Tests/DMProject/Tests/Builtins/isnull.dm
- OpenDreamRuntime/DreamValue.cs
> Fix isnull

- DMCompiler/Compiler/DM/DMAST.cs
> Recursive constant list

- .github/workflows/test-tgs.yml
Use `${{ github.token }}` instead of a repo secret.
> Use github token in TGS tests

- .github/workflows/pr-labeler.yml
Should stop the size labelling job running on master I think
> Conditional labelling

- .github/boring-cyborg.yml
https://github.com/marketplace/boring-cyborg-add-labels-to-prs-based-on-filepaths
Need to configure the Boring Cyborg github app
> Automatic Labeling 

- Resources/keybinds.yml
debug overlay is 
```
shift + F3
```
console is 
```
shift + `
```
goon uses backtick and F3 for stuff
> Add shift to debug console keybinds

- Content.Tests/DummyDreamMapManager.cs
- OpenDreamRuntime/DreamMapManager.cs
- OpenDreamRuntime/Objects/Types/DreamObjectWorld.cs
i think! i don't have much experience with C#, so i'm probably screwing some syntax, apologies
> implements `world.maxx` and `world.maxy`

- Content.Tests/DMProject/Tests/Procs/return_type.dm
- DMCompiler/Compiler/DM/DMParser.cs
- DMCompiler/DM/DMValueType.cs
Doesn't do anything with the info currently.
> Parse proc return types

- OpenDreamClient/Input/ContextMenu/VerbMenuPopup.xaml
- OpenDreamClient/Input/ContextMenu/VerbMenuPopup.xaml.cs
Is not BYOND parity. Is annoying on goon.
> Remove description from rightclick menu

- Content.Tests/DMProject/Tests/Savefile/BasicReadAndWrite.dm
- OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs
Fixes https://github.com/OpenDreamProject/OpenDream/issues/1708
> Converts empty strings to `null` in savefile serialization

- Content.Tests/DMProject/Tests/Statements/Control Flow/try_catch4.dm
- OpenDreamRuntime/DreamManager.cs
- OpenDreamRuntime/Objects/Types/DreamObjectException.cs
> `exception.name` can be a datum

- OpenDreamRuntime/Procs/DebugAdapter/DebugAdapterClient.cs
Fixes #1628 
TL;DR `NetworkStream.Peek()` blocks on an empty stream, even though it shouldn't. So instead we just set a readtimeout and eat the error if it happens. Shouldn't happen often.
> Fix debug server hanging forever on a blocking `peek()`

- OpenDreamClient/Interface/Controls/ControlChild.cs
- OpenDreamClient/Interface/Controls/ControlWindow.cs
- OpenDreamClient/Interface/Controls/InterfaceControl.cs
just needed a little sort first
> Fix child element resizing for panes

- DMCompiler/DM/Builders/DMProcBuilder.cs
- OpenDreamClient/Input/ContextMenu/VerbMenuPopup.xaml.cs
- OpenDreamRuntime/ServerVerbSystem.cs
- OpenDreamShared/Dream/VerbSystem.cs
> implement `popup_menu`

- Content.Tests/DMProject/Tests/Math/modulus.dm
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Fixes #1744 and #1582 which is a dup
> Fix modulo

- DMCompiler/DMStandard/Types/Client.dm
I'm surprised this didn't come up sooner tbh.
https://www.byond.com/docs/ref/#/client/proc/RenderIcon
> Stub `client.RenderIcon()`

- .editorconfig
- OpenDream.sln.DotSettings
> Throws a warning for block-scoped namespaces

- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> Handle `null` in `hascall()`

- OpenDreamRuntime/DreamMapManager.cs
a few less compile warnings is always good, right?
> removes obsolete MapManager methods

- OpenDreamClient/EntryPoint.cs
- OpenDreamClient/Input/MouseInputSystem.cs
Fixes the crash with the mousemap on dodgy graphics drivers
> Update RT to 223.1.2

- OpenDreamRuntime/Objects/Types/DreamList.cs
Doing `atom.filters += null` is ignored, and `atom.filters[i] = null` removes the filter.
> Handle adding/setting null on a filters list

- .github/workflows/compiler-test.yml
Makes it easier to see actual issues.
> Pass ` --suppress-unimplemented` to the compiler workflow

- .editorconfig
- OpenDream.sln.DotSettings
- OpenDreamClient/Program.cs
Multiple blank lines are a common style issue in PRs, so I want ReSharper to catch these.
> Set max blank lines in ReSharper and Rider formatting to 1

- Content.Tests/DMProject/Tests/Special Procs/initial/initial_parent_type.dm
- Content.Tests/DMProject/Tests/Special Procs/initial/initial_type.dm
- OpenDreamRuntime/Objects/DreamObject.cs
> Handle `initial(type)` and `initial(parent_type)`

- OpenDream.sln.DotSettings
- OpenDreamShared/Dream/IconAppearance.cs
Sandbox doesn't like these apparently
> Fix sandbox violations

- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> Handle nulls in all equality comparisons

- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
Hoorah, we now do opaque blocking and also check on only our zlevel.
Fixes #1586
Fixes #1589
> Improves viewers and oviewers.

- OpenDreamClient/Interface/BrowsePopup.cs
- OpenDreamClient/Interface/Controls/ControlWindow.cs
- OpenDreamClient/Interface/Controls/InterfaceControl.cs
- OpenDreamClient/Interface/DMF/IDMFProperty.cs
- OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs
size should be formatted as `XxY`, pos should be `X,Y`
> Add proper size and pos formatting to DMF properties

- DMCompiler/Optimizer/PeepholeOptimizer.cs
Peephole optimizations weren't getting applied if the opcodes were at the end of the proc or came before a non-instruction like a label.
Fixes #1842
> Fix peephole optimizations in a few important scenarios

- .github/workflows/pr-labeler.yml
> fixes the workflow node deprecations and shit

- DMCompiler/DM/Builders/DMASTFolder.cs
- DMCompiler/DM/Expressions/Dereference.cs
- DMCompiler/DM/Expressions/LValue.cs
- DMCompiler/DMStandard/Types/Datum.dm
- DMCompiler/Optimizer/PeepholeOptimizations.cs
- DMCompiler/Optimizer/PeepholeOptimizer.cs
1. `EmitPushValue()` now pushes constants instead of references when possible (in line with BYOND)
2. Peephole optimizer now attempts to const-fold various arithmetic operators
3. Things covered by the above have been removed from the old AST folder
> Peephole Const Folding - Part 1

- OpenDreamClient/Interface/DreamInterfaceManager.cs
Basic implementation of `.output`
Fixes the stat panel's dark mode in tg
> Implement `.output` client command

- OpenDreamClient/Interface/DMF/DMFLexer.cs
- OpenDreamClient/Interface/DMF/IDMFProperty.cs
- OpenDreamClient/Interface/DreamInterfaceManager.cs
string + char now trips the sandbox
> Fix sandbox errors in .NET 8.0.300

- OpenDreamRuntime/Objects/DreamObject.cs
- OpenDreamRuntime/Objects/Types/DreamList.cs
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
Clean up the opcode handler a bit too.
> Fix `initial(path.parent_type)` and `initial(path.type)`

- OpenDreamClient/Rendering/DreamPlane.cs
- OpenDreamClient/Rendering/DreamViewOverlay.cs
Something is still fucky with filters, I'm not sure what but it's a separate issue to this.
Fixes #1855
> FIxed transforms applying to mousemaps

- Content.Tests/DMProject/Tests/Preprocessor/Conditional/nested_if9.dm
- DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs
Creating this pr just in case my fix isnt as bad as I think
closes #1885
> Fix: excess tab after #if (#1885)

- DMCompiler/DMStandard/Types/Client.dm
- OpenDreamClient/Input/MouseInputSystem.cs
- OpenDreamClient/Interface/DreamInterfaceManager.cs
- OpenDreamClient/Interface/DummyDreamInterfaceManager.cs
- OpenDreamRuntime/DreamConnection.cs
- OpenDreamRuntime/Objects/Types/DreamObjectClient.cs
- OpenDreamShared/Network/Messages/MsgUpdateClientInfo.cs
- TestGame/code.dm
You can't really tell but I am right clicking while it's disabled and the menu is not showing, as expected:
https://github.com/OpenDreamProject/OpenDream/assets/5714543/e3d038c0-e032-444e-8978-1c53040b6172
Closes #183
> Implement `client.show_popup_menus`

- OpenDreamRuntime/DreamManager.cs
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
I also gave filters their own ref ID. These two changes fix several cases in tg's view variables.
> Fix `istype(..., appearance)`

- OpenDreamClient/Rendering/DreamViewOverlay.cs
- TestGame/renderer_tests.dm
holy shit I fucking got it
Fixes #1729
Paradise:
Goon:
> Fix goon layering issue

- OpenDreamClient/Interface/DreamInterfaceManager.cs
Saw this show up a few times in the logs.
https://www.byond.com/docs/ref/#/proc/winget
> Implement special `winget` for `url`

- DMCompiler/DMStandard/_Standard.dm
Resolves https://github.com/OpenDreamProject/OpenDream/issues/1956
https://secure.byond.com/docs/ref/index.html#/proc/noise_hash
> Stub `noise_hash()`

- Content.Tests/DMProject/Tests/Database/error.dm
- Content.Tests/DMProject/Tests/Database/no_entries.dm
- Content.Tests/DMProject/Tests/Database/open_and_open.dm
- Content.Tests/DMProject/Tests/Database/read.dm
- Content.Tests/DMProject/Tests/Database/too_many_or_few_params.dm
- OpenDreamRuntime/Objects/Types/DreamObjectDatabase.cs
- OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
the databases were not being fdeld() as the connection pool to them still existed
> fix database tests not cleaning up properly

- OpenDreamClient/Interface/Controls/ControlBrowser.cs
An exception in here isn't caught by RT and will crash without being logged.
> Surround CEF RequestHandler with a try/catch

- OpenDreamClient/Rendering/DreamIcon.cs
- Calculate every displayed frame from game tick zero rather than the last updated tick.
- Reduce loops required to catch up by calculating the module of the total animation delay.
- Fix `DirtyTexture()` being called too aggressively.
Fixes #1176
> Fixes animations being desynced

- OpenDreamRuntime/DreamConnection.cs
- OpenDreamRuntime/Objects/Types/DreamObjectClient.cs
bug, makes joining goon real slow for some reason, throws a bunch of debug asserts.
> fix null statpanel

- .github/workflows/compiler-test.yml
cm has an od linter, and is a bit of a weird codebase because... it's cm, so it seems decent enough to test against
also ike said i should
> test cm in od ci

- Content.Tests/DummyDreamMapManager.cs
- OpenDreamRuntime/DreamMapManager.cs
- OpenDreamRuntime/Objects/Types/DreamList.cs
- OpenDreamRuntime/Objects/Types/DreamObjectArea.cs
These vars are equal to the coordinates of the area's lowest turf (lowest z, then lowest y, then lowest x)
> Implement /area's `x`/`y`/`z` vars

- OpenDreamClient/Rendering/DreamPlane.cs
> Fix mousemap rendering

- OpenDreamRuntime/Objects/Types/DreamObjectRegex.cs
A regex could contain `[\l]`. We would replace that with `[[a-zA-Z]]` which is a broken regex. We don't insert those extra brackets anymore.
This fixes admin configuration on tg.
> Fix regex `\l` inside brackets

- OpenDreamRuntime/Objects/Types/DreamObjectRegex.cs
> Cope with \L in regex brackets

- OpenDreamClient/Interface/Controls/ControlWindow.cs
Fixes the size of various UIs like TG's Say popup.
> Apply UIScale to ControlWindow size

- OpenDreamRuntime/Objects/Types/DreamObjectMob.cs
- TestGame/code.dm
- TestGame/map_z1.dmm
Aka fix weird bugs with ghost roles and shit in SS13, where things happen but you never actually get moved to the newly spawned mob
> Fix mob key not accepting canonized keys

- OpenDreamClient/Interface/DMF/IDMFProperty.cs
Fixes the DMF failing to load.
> Fix DMF property strings being null

- Content.Tests/DMProject/Tests/Tree/upward_search_path3.dm
> Unit test for upward path search without LHS

- OpenDreamRuntime/AtomManager.cs
- OpenDreamRuntime/Objects/Types/DreamList.cs
BYOND just gives you a normal list populated with the overlays/underlays appearances
> Implement `atom.appearance.overlays`

- Content.Tests/DMProject/Tests/Builtins/__IMPLIED_TYPE__.dm
- DMCompiler/DM/Builders/DMExpressionBuilder.cs
> Fix __IMPLIED_TYPE__ in proc arguments

- Content.Tests/DMProject/Tests/List/ListAppendSelf.dm
- OpenDreamRuntime/Objects/Types/DreamList.cs
Fixes #2149, the runtime that  was caused by appending a list to itself by appending a copy of the list instead.
> List append self

- Content.Tests/DMProject/Tests/Statements/VarDecl/cant_override_final.dm
- DMCompiler/Compiler/CompilerError.cs
- DMCompiler/Compiler/DM/AST/DMAST.ObjectStatements.cs
- DMCompiler/Compiler/DM/DMPath.cs
- DMCompiler/DM/DMCodeTree.Vars.cs
- DMCompiler/DM/DMObjectTree.cs
- DMCompiler/DM/DMVariable.cs
> Add support for `final` on object vars

- OpenDreamClient/Rendering/DreamViewOverlay.cs
stuff in `vis_contents` was ignoring the `invisibility` value, this adds that check to `ProcessIconComponents()`
> Fix `vis_contents` invisibility

- .github/workflows/compiler-test.yml
Detects what just happened, in case of regression
> Add relative path compiler test

- OpenDreamClient/Rendering/DreamIcon.cs
Was destroying performance on /tg/
> Fix a missed RenderTargetPool return

- Content.Tests/DMProject/Tests/Statements/VarDecl/global_whitespace.dm
- DMCompiler/Compiler/DM/DMParser.cs
> Fix parsing global var decls with whitespace

- Resources/keybinds.yml
> Fix the middle mouse keybind

- DMCompiler/DM/DMCodeTree.Vars.cs
> Disallow var defines on /world and /list

- DMCompiler/DMStandard/Types/Sound.dm
> Stub 516 `/sound` vars

- OpenDreamClient/Interface/Html/HtmlParser.cs
> Adds html parser check for void elements

- Content.Tests/DMProject/Tests/List/ListSplice.dm
- DMCompiler/DMStandard/Types/List.dm
- OpenDreamRuntime/Procs/Native/DreamProcNative.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeList.cs
https://github.com/OpenDreamProject/OpenDream/issues/2194
https://www.byond.com/docs/ref/#/list/proc/Splice
> Implement `list.Splice()`

- OpenDreamShared/OpenDreamShared.csproj
Fixes #2223
Thanks @PJB3005  <3
> Fix autogenerated component state stuff

- DMCompiler/DMStandard/Types/Atoms/_Atom.dm
> Stub 516 `/atom` vars

- OpenDreamClient/Interface/Controls/ControlWindow.cs
- OpenDreamClient/Interface/DebugWindows/MacrosWindow.cs
- OpenDreamClient/Interface/DreamInterfaceManager.cs
- OpenDreamClient/Interface/InterfaceMacro.cs
sets the DMF value `focus` on windows where appropriate, and activates the appropriate macroset
> Implement focus and macro selection for windows

- OpenDreamClient/DreamClientSystem.cs
- OpenDreamClient/Input/ContextMenu/ContextMenuPopup.xaml.cs
- OpenDreamClient/Input/MouseInputSystem.cs
- OpenDreamClient/Interface/Controls/ControlMap.cs
- OpenDreamClient/Interface/Controls/ControlWindow.cs
- OpenDreamClient/Interface/Controls/InterfaceControl.cs
- OpenDreamClient/Interface/Controls/UI/ScalingViewport.cs
- OpenDreamClient/Interface/Descriptors/ControlDescriptors.cs
- OpenDreamClient/Interface/DreamInterfaceManager.cs
Gets the hover tooltip in the bottom left working on tg and Paradise. Goon's remains broken because the event doesn't bubble up to parent panes/windows.
Fixes #1092
> Implement the `on-status` DMF event

- OpenDreamClient/Rendering/DreamPlane.cs
- OpenDreamClient/Rendering/DreamViewOverlay.cs
- OpenDreamClient/Resources/ResourceTypes/DMIResource.cs
* Render a plane's filters when it's rendered to a render target
* Fix planes not rendering to a render target when also rendering to the map
This gets tg's emissive lighting and flashlights to work
> Some plane fixes

- DMCompiler/DMCompiler.cs
It was previously possible to make a codebase fail OD compilation by making `UnimplementedAccess` an error but passing `--suppress-unimplemented` hid the problem. Now `--suppress-unimplemented` emits the warning code for the pragma, so if it's raised to an error it'll still cause compilation to fail no matter what.
Prevents https://github.com/ParadiseSS13/Paradise/pull/28837 from happening again.
I also improved exception handling for when a warning code isn't present in the dictionary.
Requires https://github.com/Aurorastation/Aurora.3/pull/20683 to be merged because they made the same mistake.
> Change `--suppress-unimplemented` to emit the pragma's warning code

- DMCompiler/Json/DreamCompiledJson.cs
- DMDisassembler/DMDisassembler.csproj
- DMDisassembler/DMProc.cs
- DMDisassembler/DMType.cs
- DMDisassembler/Program.cs
Resolves #2068 
Also converted some lists to arrays while I was here.
> Enable nullable in the disassembler

- DMCompiler/Optimizer/AnnotatedByteCodeWriter.cs
Hopefully reduces allocs in the compiler.
> Nuke a bunch of Stack<> allocs

- DMCompiler/Optimizer/PeepholeOptimizer.cs
> Don't rebuild the opt tree on every proc

- Content.Tests/DMProject/Tests/Operators/output_float.dm
- OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> Implement `<<` output on floats

- DMCompiler/DM/Builders/DMProcBuilder.cs
- DMCompiler/DM/DMProc.cs
DMProc grows ever larger and more confusing
Set statements are now handled when DMProc is created instead of as part of code compiling. This fixes some sets (such as opendream_unimplemented) not being set yet depending on code order.
> Make set statements independent of compile order

- .github/workflows/compiler-test.yml
Does what it says on the tin. Curse of pointer usage and modified types upon ye.
> adds Daedalus to the compile tests

- OpenDreamClient/EntryPoint.cs
> Bump RT to 255.1.0

- OpenDreamClient/Rendering/DreamViewOverlay.cs
Fixes https://github.com/OpenDreamProject/OpenDream/issues/2247
Only the 3 MouseOpacity changes were me rest was automatic stuff
> Overlays/Underlays inherit mouse_opacity

- OpenDreamClient/Interface/DreamInterfaceManager.cs
- TestGame/code.dm
> Winget DPI

- OpenDreamPackageTool/ServerPackaging.cs
- OpenDreamRuntime/ByondApi/ByondApi.Trampoline.cs
- OpenDreamRuntime/DreamManager.cs
- OpenDreamRuntime/OpenDreamRuntime.csproj
- OpenDreamRuntime/Procs/DMOpcodeHandlers.CallExt.cs
> Include the byondapi DLL in releases

- Content.Tests/DMProject/BrokenTests/Statements/ControlFlow/sleep/no_paren.dm
- Content.Tests/DMProject/Tests/Statements/ControlFlow/sleep/no_paren.dm
> Make `no_paren.dm` pass

- OpenDreamRuntime/Objects/Types/DreamList.cs
> implement `datum.vars.Find()`

- OpenDreamRuntime/DreamManager.cs
Should return null, not throw an index error
> fix bad proc refs throwing an error

- OpenDreamRuntime/Objects/DreamObject.cs
Pretty sure this is necessary :)
gonna let the test suite run, my steamdeck is mad.
> Fix the `vars` list of objects not being freed on del.

- OpenDreamRuntime/DreamConnection.cs
- OpenDreamRuntime/Objects/Types/DreamObjectWorld.cs
- OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
The params arg can be a list which is converted using `list2params()` for you. TG uses this when your client is on v516 now, so this fixes connecting to the server.
I also fixed a bunch of ReSharper warnings in DreamProcNativeRoot.cs while I was there.
> Implement `winset(x, y, list())`

- OpenDreamServer/OpenDreamServer.csproj
- OpenDreamServer/server_config.toml
Partially reverts https://github.com/OpenDreamProject/OpenDream/pull/1502
Makes it easier for noobs; makes it easier for me to explain how to change config to noobs.
> Re-add example config

- Content.Tests/DMProject/Tests/List/ListNegativeSizePragma.dm
- DMCompiler/Compiler/CompilerError.cs
- DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs
- DMCompiler/DMCompiler.cs
- DMCompiler/Json/DreamCompiledJson.cs
- OpenDreamRuntime/DreamManager.cs
- OpenDreamRuntime/Objects/Types/DreamList.cs
> Implements optional exceptions configured by pragma

- OpenDreamClient/Interface/Controls/UI/AppearanceControl.cs
- OpenDreamClient/Rendering/DreamIcon.cs
- TestGame/code.dm
compiles, fixes filters, i don't know where AppearanceControls are used so i can't comment on those
> Make AppearanceControl work in worldspace

- DMCompiler/DMStandard/Types/Client.dm
- DMCompiler/DMStandard/Types/PixLoc.dm
- DMCompiler/DMStandard/UnsortedAdditions.dm
- DMCompiler/DMStandard/_Standard.dm
Stub `/pixloc` and its vars, as well as `bound_pixloc()`
Also stub some bounds vars on `/client` (`bounds`, `bound_x`, `bound_y`, `bound_width`, `bound_height`)
> Stub some pixloc things

- .github/codecov.yml
- .github/workflows/build-test.yml
- Content.IntegrationTests/Content.IntegrationTests.csproj
- Content.Tests/Content.Tests.csproj
- Directory.Packages.props
Adds code coverage reports using https://about.codecov.io/
@wixoaGit  you'll need to create a free open source account and add a github secret token `CODECOV_TOKEN`
config settings go in `.github/codecov.yml`
> Add code coverage reports

- .codecov.yml
Don't cover Tests, Packaging, or Server
> Add ignore rules to .codecov.yml
